/**
 * Sunny System Awareness — the GLOBAL KNOWLEDGE / CONNECTIVITY GAP REGISTRY (every domain, not only Projects).
 *
 * Permanent rule (Owner, 2026-09-25): SUNNY KNOWS EVERYTHING REDBLOODS KNOWS. "Redbloods knows it but Sunny cannot
 * see it" is never an accepted final state — every such case is a registered gap with a reason and what would close
 * it. Only real secrets / access material are INTENTIONALLY_SECRET. Pure data; served through system_awareness.
 */

export type GapClass =
  | "DATA_NOT_RECORDED"        // Redbloods itself never stores it
  | "DATA_MODEL_GAP"           // stored, but without a stable relationship / id
  | "CAPABILITY_GAP"           // Redbloods has it, Sunny's read path cannot reach it yet
  | "AMBIGUOUS_IDENTITY"       // who / which entity is not deterministic
  | "CONFLICTING_SOURCES"      // two sources disagree
  | "INTENTIONALLY_SECRET"     // credentials / bearer access material — only the existence + health is knowledge
  | "TEMPORARILY_UNAVAILABLE"  // exists but a source may be down / cleared
  | "LEGACY_CONFLICT"          // an old surface still computes it differently
  | "SYSTEM_BEHAVIOR_GAP"      // the app itself behaves in a way that loses / corrupts meaning
  | "OWNER_DECISION_REQUIRED"  // the meaning is a policy only the Owner can set
  | "FUTURE_PRIMITIVE_REQUIRED"; // Sunny knows the action but no approved typed primitive exists yet

/** Knowledge disposition (Sunny's side). */
export type GapStatus = "CLOSED_NOW" | "PARTIALLY_CLOSED" | "DATA_NOT_RECORDED" | "FUTURE_SCHEMA_REQUIRED" | "CONFLICT_REQUIRES_OWNER_DECISION" | "SECURITY_REMEDIATION_REQUIRED" | "OPEN";

/** What the APPLICATION would need (separate from Sunny's knowledge). Never done inside a knowledge mission. */
export type AppRemediation = "NONE" | "SCHEMA_CHANGE" | "BUG_FIX_MISSION" | "SECURITY_FIX" | "OWNER_DECISION" | "OWNER_INPUT" | "OAUTH_OR_INTEGRATION_APPROVAL";

export interface KnowledgeGap {
  id: string;
  domain: string;
  entityType: string;
  class: GapClass;
  description: string;
  redbloodsKnows: string;
  sunnyKnows: string;
  why: string;
  wouldClose: string;
  relationshipsAffected: readonly string[];
  risk: "LOW" | "MEDIUM" | "HIGH";
  ownerImpact: string;
  futureActionImpact: string;
  status: GapStatus;
  appRemediation: AppRemediation;
  /** Where Sunny reads what it does know (capability[:mode/section]). */
  sunnyReadsVia: readonly string[];
  /** The item from the 92671ee report this disposes of (if inherited). */
  inherited92671ee?: string;
}

const G = (g: KnowledgeGap) => g;

export const KNOWLEDGE_GAPS: readonly KnowledgeGap[] = [
  // ── inherited from the Projects Deep Brain report (92671ee) ──
  G({ id: "PRJ_NOTES_NOT_READ", domain: "PROJECTS", entityType: "project", class: "CAPABILITY_GAP", inherited92671ee: "project notes not read",
    description: "Project notes and the other project-linked free text", redbloodsKnows: "project notes, financial notes, send-log notes, meeting notes, task descriptions, engineer instructions / comments / target notes, Victor review notes, Red Films director / photographer notes, release blocker / next action, clip / album / budget notes",
    sunnyKnows: "all of it, on demand, with provenance (OWNER_TEXT — never a canonical fact)", why: "earlier safe-read deliberately excluded free text", wouldClose: "project_view section notes (bounded per project)",
    relationshipsAffected: ["project → notes"], risk: "LOW", ownerImpact: "Sunny can quote what was written about a project", futureActionImpact: "a future UPDATE_PROJECT_NOTES primitive can preview the exact text", status: "CLOSED_NOW", appRemediation: "NONE", sunnyReadsVia: ["project_view:notes"] }),
  G({ id: "PRJ_FILES_NOT_READ", domain: "PROJECTS", entityType: "project file", class: "CAPABILITY_GAP", inherited92671ee: "project files not read",
    description: "The project's file / material list", redbloodsKnows: "name, category, version, track, size / duration, upload time, source (upload / intake / mix copy / work materials), Dropbox path, share link",
    sunnyKnows: "every entry's metadata, categories, versions, dates and source; the folder it lives in. Share links / tokens withheld (bearer access)", why: "earlier safe-read excluded paths and links", wouldClose: "project_view section files (links redacted)",
    relationshipsAffected: ["project → files", "engineer version → project file copy"], risk: "LOW", ownerImpact: "Sunny can answer 'what files exist / which version is latest'", futureActionImpact: "file actions stay DESTRUCTIVE / EXTERNAL_EFFECT class", status: "CLOSED_NOW", appRemediation: "NONE", sunnyReadsVia: ["project_view:files"] }),
  G({ id: "PRJ_WORK_MATERIALS_NOT_READ", domain: "PROJECTS", entityType: "work materials", class: "CAPABILITY_GAP", inherited92671ee: "work_materials not read",
    description: "BPM / key / instructions for the engineer", redbloodsKnows: "the work-materials object on the project", sunnyKnows: "all of it", why: "excluded earlier", wouldClose: "project_view section materials",
    relationshipsAffected: ["project → engineer"], risk: "LOW", ownerImpact: "Sunny knows what the engineer was told", futureActionImpact: "UPDATE_WORK_MATERIALS", status: "CLOSED_NOW", appRemediation: "NONE", sunnyReadsVia: ["project_view:materials"] }),
  G({ id: "PRJ_DROPBOX_FOLDER", domain: "FILES_DROPBOX", entityType: "project folder", class: "CAPABILITY_GAP", inherited92671ee: "dropbox_folder not read",
    description: "Where the project's files live and whether the folder is frozen", redbloodsKnows: "the frozen folder (or none → computed from the current artist + name); the live Dropbox listing lives in Dropbox",
    sunnyKnows: "the folder path, whether it is frozen (unfrozen = future uploads move on an artist change), and every file Redbloods recorded", why: "a LIVE Dropbox listing needs the Dropbox credential at read time (refreshing it writes the stored token); Sunny's read path is credential-free",
    wouldClose: "an Owner-approved read-only Dropbox listing primitive that never persists refreshed tokens", relationshipsAffected: ["project → Dropbox folder"], risk: "LOW", ownerImpact: "files uploaded straight to Dropbox (outside Redbloods) are invisible to Sunny and to Redbloods' own file list", futureActionImpact: "none (read)", status: "PARTIALLY_CLOSED", appRemediation: "OAUTH_OR_INTEGRATION_APPROVAL", sunnyReadsVia: ["project_view:files"] }),
  G({ id: "PRJ_SHOW_LINK", domain: "SHOWS", entityType: "show", class: "DATA_MODEL_GAP", inherited92671ee: "shows ↔ projects not linked",
    description: "Shows never reference a project (rehearsal sessions carry the show but no project; show money has no project)", redbloodsKnows: "the show's artist as a client id + text", sunnyKnows: "ARTIST-LEVEL context: shows of the same artist (never claimed as the project's shows)",
    why: "no column links a show to a project or release", wouldClose: "a nullable show → project / release link (schema change, Owner decision)", relationshipsAffected: ["project ↔ show", "release ↔ show"], risk: "LOW",
    ownerImpact: "'which show promotes this song' is unknown to Redbloods itself", futureActionImpact: "a future LINK_SHOW_TO_RELEASE primitive needs the schema first", status: "FUTURE_SCHEMA_REQUIRED", appRemediation: "SCHEMA_CHANGE", sunnyReadsVia: ["project_view:show_context"] }),
  G({ id: "PRJ_CLIENT_IDENTITY", domain: "CLIENTS", entityType: "client", class: "AMBIGUOUS_IDENTITY", inherited92671ee: "client ↔ project name-only",
    description: "Projects carry the client only as artist TEXT", redbloodsKnows: "artist text; id bridges on proposals (client + linked project), meetings (client + project), Red Films (client + project), send log (recipient client + project)",
    sunnyKnows: "TEXT_MATCH by exact token + DERIVED corroboration from every id bridge, and conflicts when a bridge names a different client", why: "projects have no client id; screens even disagree on case sensitivity",
    wouldClose: "a project → client id (schema change) or Owner-confirmed identity (P2)", relationshipsAffected: ["project ↔ client"], risk: "MEDIUM", ownerImpact: "renames / typos silently detach projects from clients", futureActionImpact: "client-targeted actions need a deterministic identity first", status: "PARTIALLY_CLOSED", appRemediation: "SCHEMA_CHANGE", sunnyReadsVia: ["client_view:projects", "project_view:people", "project_view:graph"] }),
  G({ id: "PRJ_PARENT_BY_NAME", domain: "PROJECTS", entityType: "parent project", class: "DATA_MODEL_GAP", inherited92671ee: "parent project name-only",
    description: "Parent project is free text ('אלבום: X', 'EP: X', a name, or ללא שיוך)", redbloodsKnows: "the text", sunnyKnows: "the text + the project(s) whose name matches exactly (TEXT_MATCH) + children pointing at this project by name",
    why: "typed by hand, no picker, no id", wouldClose: "a parent project id (schema change)", relationshipsAffected: ["project → parent", "parent → children"], risk: "LOW", ownerImpact: "renaming an album orphans its songs", futureActionImpact: "SET_PARENT_PROJECT", status: "FUTURE_SCHEMA_REQUIRED", appRemediation: "SCHEMA_CHANGE", sunnyReadsVia: ["project_view:graph"] }),
  G({ id: "PRJ_CALENDAR_LIVE", domain: "GOOGLE_CALENDAR", entityType: "calendar event", class: "CAPABILITY_GAP", inherited92671ee: "Google Calendar beyond sessions not read",
    description: "Live Google Calendar content", redbloodsKnows: "the Calendar page reads every calendar live from Google; Redbloods records store event ids",
    sunnyKnows: "the LIVE calendar (all calendars: titles, times, descriptions, locations, attendees + responses, organizer, recurrence, status, type, free / busy, holidays, untitled events) through the trusted MAIN integration, linked to Redbloods with explicit quality, plus availability", why: "closed 2026-09-25 (Sunny live calendar)",
    wouldClose: "—", relationshipsAffected: ["project → calendar events", "session / meeting / show → calendar event"], risk: "LOW", ownerImpact: "Sunny sees what the Owner's Calendar shows", futureActionImpact: "calendar writes stay future EXTERNAL_EFFECT primitives", status: "CLOSED_NOW", appRemediation: "NONE", sunnyReadsVia: ["calendar", "project_view:calendar"] }),
  G({ id: "PRJ_RED_FILMS_CREW", domain: "RED_FILMS", entityType: "crew", class: "DATA_MODEL_GAP", inherited92671ee: "Red Films crew not read",
    description: "Who shot / directed / edited", redbloodsKnows: "photographer / director / editor NAMES and notes as free text on the production; budget-item vendor names", sunnyKnows: "all of it as OWNER_TEXT (CREW_IDENTITY_TEXT, not an identity)",
    why: "crew are text, not people records", wouldClose: "crew as client / person ids (schema change)", relationshipsAffected: ["production → crew"], risk: "LOW", ownerImpact: "the same photographer under two spellings is two people", futureActionImpact: "crew payment actions need ids", status: "PARTIALLY_CLOSED", appRemediation: "SCHEMA_CHANGE", sunnyReadsVia: ["project_view:red_films"] }),
  G({ id: "PRJ_WAITING_ON", domain: "PROJECTS", entityType: "blocker", class: "DATA_NOT_RECORDED", inherited92671ee: "waiting for client / artist not recorded",
    description: "Who the project is waiting on", redbloodsKnows: "send-log entries (recipient role / name / status / follow-up), engineer status (חזר = back with the Owner), open mix comments, Victor work state + reviews, release blocker / responsible text",
    sunnyKnows: "every one of those signals with its evidence; Owner-taught PROJECT_BLOCKER knowledge", why: "no field says 'waiting for client / artist' unless the Owner logged a send", wouldClose: "the Owner logging sends / teaching blockers (no schema needed)",
    relationshipsAffected: ["project → waiting party"], risk: "MEDIUM", ownerImpact: "unlogged waits look like silence", futureActionImpact: "LOG_PROJECT_SEND", status: "PARTIALLY_CLOSED", appRemediation: "OWNER_INPUT", sunnyReadsVia: ["project_view:waiting"] }),
  G({ id: "PRJ_PRICE_UNKNOWN", domain: "FINANCE", entityType: "agreed price", class: "DATA_NOT_RECORDED", inherited92671ee: "19 open projects PRICE_UNKNOWN",
    description: "Open projects without an agreed price", redbloodsKnows: "production check 2026-09-25: of 20 open non-priced projects, 17 have no price in ANY source (no setting, proposal, transaction or production price); one has only a clip price; one stores price 0; one is a label project",
    sunnyKnows: "the per-project evidence (setting, proposal, transactions, production price) and why the verdict exists", why: "the price was never entered", wouldClose: "the Owner entering prices in Redbloods (never into P2)",
    relationshipsAffected: ["project → money"], risk: "MEDIUM", ownerImpact: "debt is UNKNOWN, not zero", futureActionImpact: "SET_PROJECT_AGREED_PRICE (FINANCIAL)", status: "DATA_NOT_RECORDED", appRemediation: "OWNER_INPUT", sunnyReadsVia: ["project_view:money"] }),
  G({ id: "PRJ_PRICE_ZERO", domain: "FINANCE", entityType: "agreed price", class: "CONFLICTING_SOURCES",
    description: "A price stored as 0 (and a Red Films production at 0)", redbloodsKnows: "agreedPrice = 0", sunnyKnows: "the value and that 0 is treated as 'no price' by the Finance Brain but as 'has setting' by other screens",
    why: "0 can mean free work, unknown, or a placeholder", wouldClose: "Owner decision: finance exception (free) vs. real price", relationshipsAffected: ["project → money"], risk: "LOW", ownerImpact: "unclear if money is owed", futureActionImpact: "SET_FINANCE_EXCEPTION or SET_PROJECT_AGREED_PRICE", status: "CONFLICT_REQUIRES_OWNER_DECISION", appRemediation: "OWNER_DECISION", sunnyReadsVia: ["project_view:money"] }),
  G({ id: "PRJ_ORPHAN_FINANCE_SETTINGS", domain: "FINANCE", entityType: "finance setting", class: "SYSTEM_BEHAVIOR_GAP", inherited92671ee: "9 orphan finance settings",
    description: "Price settings whose project no longer exists", redbloodsKnows: "9 rows (2026-09-25)", sunnyKnows: "the count and that they are ignored by the Finance Brain", why: "older delete paths / manual deletes left them",
    wouldClose: "a cleanup mission (Owner-approved)", relationshipsAffected: ["finance setting → project"], risk: "LOW", ownerImpact: "none today", futureActionImpact: "none", status: "CLOSED_NOW", appRemediation: "BUG_FIX_MISSION", sunnyReadsVia: ["system_awareness:project_model/integrity"] }),
  G({ id: "PRJ_UNFROZEN_FOLDERS", domain: "FILES_DROPBOX", entityType: "project folder", class: "SYSTEM_BEHAVIOR_GAP", inherited92671ee: "12 unfrozen Dropbox folders",
    description: "Projects whose folder is computed, not frozen", redbloodsKnows: "12 projects (2026-09-25)", sunnyKnows: "per project: frozen or not (project_view files.folderFrozen)", why: "folders freeze only on the first rename",
    wouldClose: "freeze-on-create (bug-fix mission)", relationshipsAffected: ["project → folder"], risk: "MEDIUM", ownerImpact: "an artist change moves future uploads", futureActionImpact: "CHANGE_PROJECT_ARTIST must disclose the folder move", status: "CLOSED_NOW", appRemediation: "BUG_FIX_MISSION", sunnyReadsVia: ["project_view:files"] }),
  G({ id: "PRJ_FINANCE_CONFLICTS", domain: "FINANCE", entityType: "project money", class: "LEGACY_CONFLICT", inherited92671ee: "finance conflicts C1–C17",
    description: "Screens compute project money differently (currencies mixed, exception ignored, 'expected' defined differently)", redbloodsKnows: "C1–C17", sunnyKnows: "every conflict and the canonical rule; project_view uses only the canonical rule",
    why: "legacy surfaces", wouldClose: "fix missions per conflict (Owner-approved)", relationshipsAffected: ["project → money"], risk: "MEDIUM", ownerImpact: "two screens can show two balances", futureActionImpact: "financial primitives preview the canonical verdict", status: "CONFLICT_REQUIRES_OWNER_DECISION", appRemediation: "BUG_FIX_MISSION", sunnyReadsVia: ["system_awareness:project_model/money"] }),
  G({ id: "PRJ_PAGE_LOAD_WRITES", domain: "SESSIONS", entityType: "session / project", class: "SYSTEM_BEHAVIOR_GAP", inherited92671ee: "page-load side effects",
    description: "Opening pages writes data (sessions auto-marked held by the device clock; legacy drawer overwrites start dates)", redbloodsKnows: "the behavior", sunnyKnows: "every page-load write and its risk", why: "implementation behavior",
    wouldClose: "bug-fix mission", relationshipsAffected: ["session status", "project start date"], risk: "MEDIUM", ownerImpact: "'held' may be wrong when a device clock is wrong", futureActionImpact: "none", status: "CLOSED_NOW", appRemediation: "BUG_FIX_MISSION", sunnyReadsVia: ["system_awareness:project_model/side_effects"] }),
  G({ id: "PRJ_PROPOSAL_CONVERT_NON_ATOMIC", domain: "PROPOSALS", entityType: "proposal → project", class: "SYSTEM_BEHAVIOR_GAP", inherited92671ee: "proposal conversion non-transactional",
    description: "Conversion is several writes; it also overwrites the whole finance setting", redbloodsKnows: "behavior", sunnyKnows: "behavior + the resulting link", why: "implementation", wouldClose: "bug-fix mission (atomic conversion)",
    relationshipsAffected: ["proposal → project"], risk: "MEDIUM", ownerImpact: "a failed conversion can leave a project without its proposal link / price", futureActionImpact: "CONVERT_PROPOSAL must be atomic before delegation", status: "CLOSED_NOW", appRemediation: "BUG_FIX_MISSION", sunnyReadsVia: ["system_awareness:action_inventory"] }),
  G({ id: "PRJ_STATUS_NOT_VALIDATED", domain: "PROJECTS", entityType: "status", class: "SYSTEM_BEHAVIOR_GAP", inherited92671ee: "status not server-validated",
    description: "Any status text is accepted", redbloodsKnows: "behavior (production: 0 non-vocabulary statuses)", sunnyKnows: "behavior + production count", why: "no server check", wouldClose: "bug-fix mission",
    relationshipsAffected: [], risk: "LOW", ownerImpact: "a typo would hide a project from every 'active' view", futureActionImpact: "UPDATE_PROJECT_STATUS validates against the vocabulary", status: "CLOSED_NOW", appRemediation: "BUG_FIX_MISSION", sunnyReadsVia: ["system_awareness:project_model/vocabularies"] }),
  G({ id: "PRJ_DELETE_NON_ATOMIC", domain: "PROJECTS", entityType: "project delete", class: "SYSTEM_BEHAVIOR_GAP", inherited92671ee: "project delete not transactional",
    description: "Delete is part app, part DB cascade, part left behind", redbloodsKnows: "behavior", sunnyKnows: "exactly what is deleted / changed / left behind", why: "implementation", wouldClose: "bug-fix mission",
    relationshipsAffected: ["every project link"], risk: "HIGH", ownerImpact: "orphans after deletes", futureActionImpact: "DELETE_PROJECT is DESTRUCTIVE class; preview must list what stays", status: "CLOSED_NOW", appRemediation: "BUG_FIX_MISSION", sunnyReadsVia: ["system_awareness:action_inventory"] }),
  G({ id: "PRJ_CONCURRENT_FILE_WRITES", domain: "FILES_DROPBOX", entityType: "project files", class: "SYSTEM_BEHAVIOR_GAP", inherited92671ee: "concurrent file-write risk",
    description: "The file list is read-modify-written without a lock", redbloodsKnows: "behavior", sunnyKnows: "behavior; a file missing from the list may still exist in Dropbox", why: "implementation", wouldClose: "bug-fix mission",
    relationshipsAffected: ["project → files"], risk: "MEDIUM", ownerImpact: "two parallel uploads can lose one entry", futureActionImpact: "file primitives must serialize", status: "CLOSED_NOW", appRemediation: "BUG_FIX_MISSION", sunnyReadsVia: ["project_view:files"] }),
  // ── discovered in this mission ──
  G({ id: "PRJ_HISTORY_NOT_RECORDED", domain: "PROJECTS", entityType: "project history", class: "DATA_NOT_RECORDED",
    description: "Status / deadline / price / artist history", redbloodsKnows: "only the current value + last updated time; append-only history exists only for Sunny deadline actions; the send log is dated but editable",
    sunnyKnows: "current state, last update, send-log timeline, Sunny action decisions / outcomes, project bell notifications that still exist", why: "the app overwrites fields in place", wouldClose: "a project change log (schema change)",
    relationshipsAffected: [], risk: "MEDIUM", ownerImpact: "'when did this change / who changed it' is unanswerable", futureActionImpact: "every Sunny primitive already writes append-only events", status: "DATA_NOT_RECORDED", appRemediation: "SCHEMA_CHANGE", sunnyReadsVia: ["project_view:history"] }),
  G({ id: "PRJ_NOTIFICATIONS_CLEARED", domain: "PUSH_NOTIFICATIONS", entityType: "notification", class: "TEMPORARILY_UNAVAILABLE",
    description: "Owner bell notifications are deleted every Friday", redbloodsKnows: "recent notifications with their project", sunnyKnows: "the ones that still exist", why: "weekly cleanup",
    wouldClose: "keeping notification history (Owner decision)", relationshipsAffected: ["project → notifications"], risk: "LOW", ownerImpact: "old alerts are gone", futureActionImpact: "none", status: "PARTIALLY_CLOSED", appRemediation: "OWNER_DECISION", sunnyReadsVia: ["project_view:notifications"] }),
  G({ id: "PRJ_FILE_CONTENTS", domain: "FILES_DROPBOX", entityType: "file content", class: "CAPABILITY_GAP",
    description: "The contents of files (audio, documents, the artist-portal sketch manifest)", redbloodsKnows: "files live in Dropbox; Redbloods stores metadata", sunnyKnows: "metadata only",
    why: "content needs a live Dropbox read (same credential issue as the listing); audio is binary", wouldClose: "an Owner-approved read-only Dropbox content primitive for text documents", relationshipsAffected: [], risk: "LOW", ownerImpact: "Sunny cannot read a lyric sheet or brief document", futureActionImpact: "none", status: "OPEN", appRemediation: "OAUTH_OR_INTEGRATION_APPROVAL", sunnyReadsVia: [] }),
  G({ id: "PRJ_EXPENSE_ORPHANS_ON_DELETE", domain: "FINANCE", entityType: "engineer expense", class: "SYSTEM_BEHAVIOR_GAP",
    description: "Deleting an engineer work (directly or via the send log) leaves its expense", redbloodsKnows: "behavior", sunnyKnows: "behavior", why: "implementation", wouldClose: "bug-fix mission",
    relationshipsAffected: ["engineer work → expense"], risk: "MEDIUM", ownerImpact: "expenses without work", futureActionImpact: "DESTRUCTIVE preview must disclose it", status: "CLOSED_NOW", appRemediation: "BUG_FIX_MISSION", sunnyReadsVia: ["system_awareness:action_inventory"] }),
  G({ id: "PRJ_MEETING_EVENT_ORPHANS", domain: "MEETINGS", entityType: "meeting event", class: "SYSTEM_BEHAVIOR_GAP",
    description: "Editing / deleting a meeting leaves its Google event unchanged", redbloodsKnows: "behavior", sunnyKnows: "behavior", why: "implementation", wouldClose: "bug-fix mission",
    relationshipsAffected: ["meeting → calendar event"], risk: "LOW", ownerImpact: "stale calendar events", futureActionImpact: "UPDATE_MEETING must sync the event", status: "CLOSED_NOW", appRemediation: "BUG_FIX_MISSION", sunnyReadsVia: ["system_awareness:action_inventory"] }),
  G({ id: "CAL_UNTRACKED_EVENTS_TEXT_ONLY", domain: "GOOGLE_CALENDAR", entityType: "calendar event", class: "DATA_MODEL_GAP",
    description: "Events created directly in Google have no stored Redbloods link", redbloodsKnows: "only event ids of records it created", sunnyKnows: "a TEXT_MATCH / AMBIGUOUS / UNLINKED classification for them",
    why: "nothing links a manual Google event to a project", wouldClose: "creating sessions / meetings from Redbloods (stores the id) or a future LINK_EVENT primitive", relationshipsAffected: ["calendar event → project / client"], risk: "LOW", ownerImpact: "manual events relate to projects only by their title", futureActionImpact: "a future link primitive", status: "PARTIALLY_CLOSED", appRemediation: "OWNER_INPUT", sunnyReadsVia: ["calendar"] }),
  G({ id: "CAL_WEEK_UTC_WINDOW", domain: "GOOGLE_CALENDAR", entityType: "calendar page", class: "SYSTEM_BEHAVIOR_GAP",
    description: "The Calendar page's week starts at 00:00 UTC (03:00 Israel)", redbloodsKnows: "behavior", sunnyKnows: "behavior; Sunny's own reads use Israel-time windows", why: "implementation", wouldClose: "bug-fix mission",
    relationshipsAffected: [], risk: "LOW", ownerImpact: "events between 00:00 and 03:00 on the first day of the week can be missing on the Calendar page", futureActionImpact: "none", status: "CLOSED_NOW", appRemediation: "BUG_FIX_MISSION", sunnyReadsVia: ["system_awareness:rules"] }),
  G({ id: "CAL_GOOGLE_TASKS_AND_HIDDEN", domain: "GOOGLE_CALENDAR", entityType: "calendar", class: "CAPABILITY_GAP",
    description: "Google Tasks items, hidden calendars and free/busy-only calendars", redbloodsKnows: "the Calendar page shows neither", sunnyKnows: "neither (same as the Calendar page); Redbloods tasks are read from Redbloods",
    why: "parity with what the Owner's Redbloods Calendar shows", wouldClose: "an Owner decision to include them", relationshipsAffected: [], risk: "LOW", ownerImpact: "tasks created only in Google Tasks are invisible", futureActionImpact: "none", status: "OPEN", appRemediation: "OWNER_DECISION", sunnyReadsVia: [] }),
  // ── Owner operating model (2026-09-25): what the Owner's way of working needs that Redbloods does not record ──
  G({ id: "OWN_P2_NO_PERSONAL_EVENT_KIND", domain: "SUNNY_CORE", entityType: "owner knowledge kind", class: "DATA_MODEL_GAP",
    description: "No Owner-knowledge kind can say 'this recurring calendar event is personal context' (e.g. a driving-license course)", redbloodsKnows: "the event itself (live calendar, UNLINKED)", sunnyKnows: "that the event occupies time; it treats unlinked events as personal / availability-only by rule — but cannot persist the Owner's classification of a specific event",
    why: "the ten P2 kinds cover entities, roles, relationships, blockers, follow-ups, vendor commitments, release priority, reported payments, friction and policy candidates — none fits a personal calendar classification", wouldClose: "a bounded kind (e.g. PERSONAL_CONTEXT_EVENT with a recurring-event id and no business link) — schema + Owner approval", relationshipsAffected: ["calendar event → personal"], risk: "LOW", ownerImpact: "the Owner may have to repeat that such an event is personal", futureActionImpact: "none", status: "FUTURE_SCHEMA_REQUIRED", appRemediation: "SCHEMA_CHANGE", sunnyReadsVia: ["calendar"] }),
  G({ id: "OWN_POLICY_CANDIDATE_TOO_WEAK", domain: "SUNNY_CORE", entityType: "owner operating rule", class: "DATA_MODEL_GAP",
    description: "Owner-CONFIRMED operating rules have no P2 home: WORKING_POLICY_CANDIDATE is a candidate (review after 30 days) with six areas only", redbloodsKnows: "the rules, as a versioned system contract (operating_model)", sunnyKnows: "every confirmed rule with provenance OWNER_CONFIRMED and its date",
    why: "storing a confirmed rule as a 'candidate' would weaken it; storing it as free text is forbidden", wouldClose: "kept as a versioned system contract (changed only through a reviewed code change with the Owner) — or, if the Owner wants to edit rules from the app, a confirmed-policy kind (schema)", relationshipsAffected: [], risk: "LOW", ownerImpact: "rule changes go through Claude Code, not the app", futureActionImpact: "none", status: "PARTIALLY_CLOSED", appRemediation: "OWNER_DECISION", sunnyReadsVia: ["operating_model:rules"] }),
  G({ id: "OWN_DEAL_TERMS_NOT_RECORDED", domain: "FINANCE", entityType: "project deal terms", class: "DATA_NOT_RECORDED",
    description: "Advance amount / percentage and the milestone for the remaining payment (mix, delivery, release) per deal", redbloodsKnows: "the agreed price and income rows (received / expected) — not the agreed payment structure", sunnyKnows: "whether any income was received on a progressed project (advance evidence present / missing) — never the expected advance",
    why: "Redbloods has no deal-terms field", wouldClose: "per-project payment terms (advance + milestone) — schema + Owner approval", relationshipsAffected: ["project → payment schedule"], risk: "MEDIUM", ownerImpact: "Sunny can flag a missing advance but not say how much is due now", futureActionImpact: "a collection reminder primitive would need the terms", status: "DATA_NOT_RECORDED", appRemediation: "SCHEMA_CHANGE", sunnyReadsVia: ["client_view:money", "system_awareness:client_model", "operating_model:project", "finance_receivables"] }),
  G({ id: "OWN_OUTSIDE_COMMUNICATION", domain: "SUNNY_CORE", entityType: "communication", class: "CAPABILITY_GAP",
    description: "WhatsApp / phone / in-person communication with clients, artists and the team", redbloodsKnows: "only what is recorded in the app (send log, comments, uploads)", sunnyKnows: "that outside communication exists (Owner rule) — so in-app ball-holder evidence is never conclusive",
    why: "no integration; privacy-sensitive", wouldClose: "an Owner-approved integration, or the Owner telling Sunny (P2 blocker / follow-up)", relationshipsAffected: ["project → who holds the ball"], risk: "MEDIUM", ownerImpact: "Sunny may ask 'was this handled outside Redbloods?'", futureActionImpact: "none", status: "OPEN", appRemediation: "OAUTH_OR_INTEGRATION_APPROVAL", sunnyReadsVia: ["operating_model:project"] }),
  G({ id: "OWN_DEADLINE_KIND_NOT_RECORDED", domain: "PROJECTS", entityType: "project deadline", class: "DATA_NOT_RECORDED",
    description: "Whether a project's deadline is a firm client commitment, a soft target or a stale date", redbloodsKnows: "one deadline date per project", sunnyKnows: "the Owner rule (normally a client commitment) + the historical-debt cutoff (2026-09-25)",
    why: "a single date field", wouldClose: "a deadline-kind field, or the Owner answering per project", relationshipsAffected: ["project → client commitment"], risk: "LOW", ownerImpact: "Sunny asks when a date looks stale instead of assuming", futureActionImpact: "UPDATE_PROJECT_DEADLINE already exists", status: "PARTIALLY_CLOSED", appRemediation: "OWNER_INPUT", sunnyReadsVia: ["operating_model:project"] }),
  G({ id: "OWN_PROTECTED_LABEL_ARTIST", domain: "LABEL_ARTISTS", entityType: "label artist", class: "DATA_MODEL_GAP",
    description: "'Protected growth track' is not a stored attribute", redbloodsKnows: "the label roster", sunnyKnows: "the Owner rule: every roster artist (Shalev Tasama, Avi Molla) is a protected growth track",
    why: "roster membership is the only signal", wouldClose: "nothing needed while the rule covers the whole roster; a per-artist flag if the Owner ever distinguishes", relationshipsAffected: [], risk: "LOW", ownerImpact: "none today", futureActionImpact: "none", status: "CLOSED_NOW", appRemediation: "NONE", sunnyReadsVia: ["operating_model:rules", "label_roster"] }),
  G({ id: "OWN_PERSONAL_SOURCES", domain: "GOOGLE_CALENDAR", entityType: "personal source", class: "CAPABILITY_GAP",
    description: "Personal context outside the Google calendar (other calendars, reminders, notes)", redbloodsKnows: "nothing", sunnyKnows: "only the connected Google calendar",
    why: "not connected", wouldClose: "only if the Owner connects and approves a source", relationshipsAffected: [], risk: "LOW", ownerImpact: "personal commitments that are not in the calendar are invisible", futureActionImpact: "none", status: "OPEN", appRemediation: "OAUTH_OR_INTEGRATION_APPROVAL", sunnyReadsVia: [] }),
  // ── Clients + Proposals Deep Brain (2026-09-25) ──
  G({ id: "CLI_NO_LEAD_ENTITY", domain: "CLIENTS", entityType: "lead", class: "DATA_MODEL_GAP",
    description: "There is no lead / opportunity entity (source, channel, interest, stage)", redbloodsKnows: "a client record, an open proposal, a meeting or free text", sunnyKnows: "a DERIVED pre-project opportunity (client with an open proposal / meeting and no project); never a lead stage or likelihood",
    why: "the app never modelled leads", wouldClose: "a lead model — schema + Owner approval (only if the Owner wants lead management)", relationshipsAffected: ["lead → client → proposal"], risk: "LOW", ownerImpact: "early conversations exist only outside Redbloods", futureActionImpact: "CREATE_LEAD would need the model", status: "OPEN", appRemediation: "SCHEMA_CHANGE", sunnyReadsVia: ["client_portfolio", "system_awareness:client_model"] }),
  G({ id: "CLI_CONTACT_AND_REPLIES_NOT_RECORDED", domain: "PROPOSALS", entityType: "follow-up contact", class: "DATA_NOT_RECORDED",
    description: "Follow-up calls / messages and client replies to a proposal", redbloodsKnows: "only the follow-up date, the status label and the last-updated time", sunnyKnows: "'the recorded follow-up date passed' — never 'the Owner did not follow up'",
    why: "no contact log; WhatsApp / phone are outside Redbloods", wouldClose: "a contact / reply log (schema) or the Owner telling Sunny", relationshipsAffected: ["proposal → contact history"], risk: "MEDIUM", ownerImpact: "Sunny may ask whether contact happened outside the system", futureActionImpact: "LOG_CONTACT would need the model", status: "DATA_NOT_RECORDED", appRemediation: "SCHEMA_CHANGE", sunnyReadsVia: ["client_view:proposals", "client_portfolio:follow_ups"] }),
  G({ id: "CLI_PROPOSAL_CHANGE_HISTORY", domain: "PROPOSALS", entityType: "proposal history", class: "DATA_NOT_RECORDED",
    description: "Changes to a proposal's amount / status / follow-up / notes (and client field changes — clients have no updated_at)", redbloodsKnows: "created / sent / last updated only", sunnyKnows: "a timeline of recorded dates only (never reconstructed changes)",
    why: "no audit trail", wouldClose: "an append-only change log (schema)", relationshipsAffected: [], risk: "LOW", ownerImpact: "'when did the price change?' is unknowable", futureActionImpact: "Sunny's own future actions will carry outcomes", status: "DATA_NOT_RECORDED", appRemediation: "SCHEMA_CHANGE", sunnyReadsVia: ["client_view:history"] }),
  G({ id: "CLI_MEETING_OUTCOME_NOT_RECORDED", domain: "MEETINGS", entityType: "meeting outcome", class: "DATA_NOT_RECORDED",
    description: "What was decided in a meeting; whether a past 'נקבעה' meeting happened", redbloodsKnows: "date, time, location, status, notes", sunnyKnows: "those + 'past meeting still נקבעה — held or not unknown'",
    why: "no outcome field; status is updated by hand", wouldClose: "an outcome field (schema) or the Owner updating status / notes", relationshipsAffected: ["meeting → next step"], risk: "LOW", ownerImpact: "2 production meetings are past and still 'נקבעה'", futureActionImpact: "UPDATE_MEETING", status: "DATA_NOT_RECORDED", appRemediation: "OWNER_INPUT", sunnyReadsVia: ["client_view:meetings"] }),
  G({ id: "CLI_PROPOSAL_STATUS_CONSUMERS_DISAGREE", domain: "PROPOSALS", entityType: "proposal status", class: "CONFLICTING_SOURCES",
    description: "Which proposals count as open / due differs by screen (allow-list vs block-list, ₪-only vs mixed-currency sums, UTC vs Israel dates)", redbloodsKnows: "each screen's own rule", sunnyKnows: "every consumer's rule (client_model status_consumers); Sunny uses the block-list + Israel dates and reports unknown statuses",
    why: "status is unvalidated free text and each screen computes its own view", wouldClose: "a validated status set + one shared rule (bug-fix mission)", relationshipsAffected: [], risk: "LOW", ownerImpact: "dashboard, Insights and the drawer can show different open totals", futureActionImpact: "CHANGE_PROPOSAL_STATUS must validate", status: "PARTIALLY_CLOSED", appRemediation: "BUG_FIX_MISSION", sunnyReadsVia: ["system_awareness:client_model"] }),
  G({ id: "CLI_RETURN_LATER_MEANING", domain: "PROPOSALS", entityType: "proposal status", class: "OWNER_DECISION_REQUIRED",
    description: "Whether 'לחזור בעתיד' belongs in the open pipeline / follow-up lists", redbloodsKnows: "every screen counts it as open", sunnyKnows: "the status and that its meaning is unset",
    why: "a label with no behavior", wouldClose: "an Owner decision", relationshipsAffected: [], risk: "LOW", ownerImpact: "open value may include parked opportunities", futureActionImpact: "none", status: "CONFLICT_REQUIRES_OWNER_DECISION", appRemediation: "OWNER_DECISION", sunnyReadsVia: ["system_awareness:client_model"] }),
  G({ id: "CLI_CONVERSION_NOT_ATOMIC", domain: "PROPOSALS", entityType: "conversion", class: "SYSTEM_BEHAVIOR_GAP",
    description: "Proposal → project conversion is not transactional; the only guard is read-then-write; the UI swallows errors", redbloodsKnows: "behavior", sunnyKnows: "the full flow + failure modes (client_model conversion)",
    why: "implementation", wouldClose: "a transactional / idempotent conversion (bug-fix mission)", relationshipsAffected: ["proposal → project → finance"], risk: "MEDIUM", ownerImpact: "a double click or a mid-way failure can create a second project", futureActionImpact: "CONVERT_PROPOSAL must be idempotent before Sunny may run it", status: "OPEN", appRemediation: "BUG_FIX_MISSION", sunnyReadsVia: ["system_awareness:client_model"] }),
  G({ id: "CLI_FOLLOWUP_TASK_BEHAVIOR", domain: "PROPOSALS", entityType: "follow-up task", class: "SYSTEM_BEHAVIOR_GAP",
    description: "The follow-up task is linked by a text marker, stays open when the proposal is lost, and an edit silently adds a follow-up date", redbloodsKnows: "behavior", sunnyKnows: "the task (DERIVED link) + these behaviors",
    why: "implementation", wouldClose: "a proposal id on tasks + closing the task on status change (bug-fix mission)", relationshipsAffected: ["proposal ↔ task"], risk: "LOW", ownerImpact: "stale follow-up tasks after a lost proposal", futureActionImpact: "SET_FOLLOW_UP", status: "OPEN", appRemediation: "BUG_FIX_MISSION", sunnyReadsVia: ["client_view:tasks"] }),
  G({ id: "CLI_FOLLOWUP_ALERT_DISABLED", domain: "PROPOSALS", entityType: "follow-up alert", class: "LEGACY_CONFLICT",
    description: "The legacy proposal follow-up alert is switched off (and would never push); the flag's comment says the opposite", redbloodsKnows: "the rule + flag", sunnyKnows: "that nothing reminds the Owner except dashboards / COO / the follow-up task",
    why: "legacy Mai agent disabled", wouldClose: "an Owner decision about reminders (Sunny may surface due follow-ups itself)", relationshipsAffected: [], risk: "LOW", ownerImpact: "no push for due follow-ups", futureActionImpact: "none", status: "OPEN", appRemediation: "OWNER_DECISION", sunnyReadsVia: ["client_portfolio:follow_ups"] }),
  G({ id: "CLI_DELETE_AND_RENAME_LEAVE_TRACES", domain: "CLIENTS", entityType: "client", class: "SYSTEM_BEHAVIOR_GAP",
    description: "Client delete leaves meetings / tasks / Red Films / Google Tasks pointing at it (no confirmation when no project names them); rename updates projects only", redbloodsKnows: "behavior", sunnyKnows: "behavior + the stale references it can see",
    why: "implementation", wouldClose: "bug-fix mission", relationshipsAffected: ["client ↔ meetings / tasks / Red Films / money text"], risk: "MEDIUM", ownerImpact: "history detaches after a delete / rename", futureActionImpact: "DELETE_CLIENT is DESTRUCTIVE", status: "OPEN", appRemediation: "BUG_FIX_MISSION", sunnyReadsVia: ["system_awareness:client_model"] }),
  G({ id: "CLI_STATUS_FIELD_MIXES_CONCEPTS", domain: "CLIENTS", entityType: "client status", class: "DATA_MODEL_GAP",
    description: "Client status mixes lifecycle, VIP tier and the label-artist role; חדש is also the auto-create default", redbloodsKnows: "one status value", sunnyKnows: "the value, never read as 'active customer' or 'lead'",
    why: "one field for three concepts", wouldClose: "separate lifecycle / tier / role (schema) — Owner decision", relationshipsAffected: [], risk: "LOW", ownerImpact: "'active clients' is not a stored fact — Sunny derives it from open work", futureActionImpact: "UPDATE_CLIENT", status: "OPEN", appRemediation: "OWNER_DECISION", sunnyReadsVia: ["client_view:identity"] }),
  G({ id: "CLI_PROJECTLESS_INCOME_BY_TEXT", domain: "FINANCE", entityType: "transaction", class: "AMBIGUOUS_IDENTITY",
    description: "Income with no project (mostly show income) links to a client only through the artist text", redbloodsKnows: "artist text on the row", sunnyKnows: "the rows attributed by exact name (TEXT_MATCH), labelled as such",
    why: "transactions have no client id", wouldClose: "an optional client id on transactions (schema, part of the client_id recommendation)", relationshipsAffected: ["transaction → client"], risk: "LOW", ownerImpact: "renames detach this money from the client", futureActionImpact: "RECORD_INCOME should carry the client", status: "PARTIALLY_CLOSED", appRemediation: "SCHEMA_CHANGE", sunnyReadsVia: ["client_view:money"] }),
  G({ id: "CLI_PERSON_WITH_TWO_RECORDS", domain: "CLIENTS", entityType: "person", class: "AMBIGUOUS_IDENTITY",
    description: "The same person can be a client record AND a label-artist record (linked only by the same name)", redbloodsKnows: "two records", sunnyKnows: "both, as roles of one person (TEXT_MATCH) + the Owner's label classification — never merged, label work never treated as client work",
    why: "no person entity", wouldClose: "a person / identity link (schema) or Owner-confirmed identity", relationshipsAffected: ["client ↔ label artist"], risk: "LOW", ownerImpact: "none while names stay identical", futureActionImpact: "none", status: "PARTIALLY_CLOSED", appRemediation: "OWNER_INPUT", sunnyReadsVia: ["client_view:roles"] }),
  G({ id: "CLI_PROPOSAL_AMOUNT_VS_PRICE", domain: "PROPOSALS", entityType: "price", class: "CONFLICTING_SOURCES",
    description: "The proposal amount and the project's agreed price can differ after conversion (1 of 3 in production)", redbloodsKnows: "both numbers", sunnyKnows: "both + the difference; the agreed price is the finance truth, the reason is unknown",
    why: "copied once, edited separately", wouldClose: "the proposed deal-terms model", relationshipsAffected: ["proposal → project price"], risk: "LOW", ownerImpact: "a discount may be invisible", futureActionImpact: "none", status: "PARTIALLY_CLOSED", appRemediation: "OWNER_INPUT", sunnyReadsVia: ["client_view:proposals"] }),
  G({ id: "CLI_NO_PROPOSAL_DOCUMENTS", domain: "PROPOSALS", entityType: "document", class: "DATA_NOT_RECORDED",
    description: "Proposal documents / contracts / attachments", redbloodsKnows: "nothing — no document model or storage for proposals", sunnyKnows: "that none exist in Redbloods",
    why: "not built", wouldClose: "a document model (only if wanted)", relationshipsAffected: [], risk: "LOW", ownerImpact: "the proposal text lives outside Redbloods", futureActionImpact: "none", status: "DATA_NOT_RECORDED", appRemediation: "OWNER_DECISION", sunnyReadsVia: [] }),
  G({ id: "CLI_ACTIONS_NOT_EXECUTABLE", domain: "CLIENTS", entityType: "client / proposal action", class: "FUTURE_PRIMITIVE_REQUIRED",
    description: "Every client / proposal mutation (create / edit / delete client, create / edit / status / follow-up / delete / convert proposal, meetings, client tasks)", redbloodsKnows: "the dashboard actions", sunnyKnows: "each action, its effects and approval class (client_model actions)",
    why: "no approved typed primitive", wouldClose: "typed primitives with preview + Owner approval (CONVERT_PROPOSAL only after it is idempotent)", relationshipsAffected: [], risk: "LOW", ownerImpact: "the Owner performs them in the dashboard", futureActionImpact: "roadmap", status: "OPEN", appRemediation: "NONE", sunnyReadsVia: ["system_awareness:client_model"] }),
  // ── Label Artists Deep Brain (2026-09-25) ──
  G({ id: "LBL_PORTAL_STORAGE_NOT_READ", domain: "ARTIST_PORTALS", entityType: "sketch / rating / next-work / press kit", class: "CAPABILITY_GAP",
    description: "Sketches (music library), ratings, next-work pick, next-release card data, press kit, performance files and profile images", redbloodsKnows: "all of it, in each artist's storage folder / manifest (not the database)", sunnyKnows: "that it exists and where; not its contents",
    why: "reading it needs the storage credential at read time; Sunny's read path is credential-free", wouldClose: "an Owner-approved read-only storage listing primitive (same as the project Dropbox gap)", relationshipsAffected: ["artist → sketches → projects"], risk: "MEDIUM", ownerImpact: "Sunny cannot see new sketches / versions / ratings", futureActionImpact: "none", status: "OPEN", appRemediation: "OAUTH_OR_INTEGRATION_APPROVAL", sunnyReadsVia: ["system_awareness:artist_model"] }),
  G({ id: "LBL_NO_CURRENCY_ON_ARTIST_MONEY", domain: "ARTIST_BALANCES", entityType: "ledger / cycle / media income / show", class: "DATA_MODEL_GAP",
    description: "The artist ledger, cycles, media income and shows store no currency (screens assume ₪)", redbloodsKnows: "amounts only", sunnyKnows: "amounts labelled currency NOT_STORED — never added to currency-bearing finance rows",
    why: "no currency column", wouldClose: "a currency column (schema)", relationshipsAffected: ["artist money ↔ finance"], risk: "LOW", ownerImpact: "a $ show or foreign media payment would be read as ₪ by the app", futureActionImpact: "any ledger primitive must state the currency", status: "OPEN", appRemediation: "SCHEMA_CHANGE", sunnyReadsVia: ["artist_view:money"] }),
  G({ id: "LBL_RECOUP_NOT_RECONCILED", domain: "MEDIA_INCOME", entityType: "recoup", class: "CONFLICTING_SOURCES",
    description: "Three artist money views: the ledger, the derived recoup view (clips vs shows + media) and each media record's stored recoup snapshot — never reconciled", redbloodsKnows: "all three", sunnyKnows: "all three, kept separate; never computes a fourth",
    why: "built separately", wouldClose: "an Owner decision on the artist accounting model", relationshipsAffected: ["ledger ↔ recoup ↔ media"], risk: "MEDIUM", ownerImpact: "'what does the label owe the artist' has no single answer", futureActionImpact: "payout primitives need one model", status: "CONFLICT_REQUIRES_OWNER_DECISION", appRemediation: "OWNER_DECISION", sunnyReadsVia: ["artist_view:money", "system_awareness:artist_model"] }),
  G({ id: "LBL_RELEASE_HISTORY_LOST", domain: "RELEASES", entityType: "release history", class: "SYSTEM_BEHAVIOR_GAP",
    description: "Only the current stage start is kept; leaving יצא clears the release date", redbloodsKnows: "current stage + start", sunnyKnows: "the same; cadence evidence is only the release dates still stored",
    why: "implementation", wouldClose: "a stage-history log + keeping the release date (bug-fix / schema)", relationshipsAffected: [], risk: "MEDIUM", ownerImpact: "release cadence cannot be reconstructed reliably", futureActionImpact: "UPDATE_RELEASE_STAGE", status: "OPEN", appRemediation: "BUG_FIX_MISSION", sunnyReadsVia: ["artist_view:releases"] }),
  G({ id: "LBL_NO_READINESS_MODEL", domain: "RELEASES", entityType: "release readiness", class: "OWNER_DECISION_REQUIRED",
    description: "What 'ready for release' means (mix / master / cover / distribution / content done)", redbloodsKnows: "the Owner-set stage מוכן ליציאה", sunnyKnows: "the stage + blocker + next action; never infers readiness",
    why: "no checklist", wouldClose: "an Owner definition (then optionally a checklist model)", relationshipsAffected: [], risk: "LOW", ownerImpact: "Sunny cannot say what is missing before a release beyond what is recorded", futureActionImpact: "none", status: "CONFLICT_REQUIRES_OWNER_DECISION", appRemediation: "OWNER_DECISION", sunnyReadsVia: ["artist_view:releases"] }),
  G({ id: "LBL_NO_CADENCE_POLICY", domain: "RELEASES", entityType: "release cadence", class: "OWNER_DECISION_REQUIRED",
    description: "A desired release cadence / inactivity threshold", redbloodsKnows: "nothing (the label page computes days since the last release but never shows it)", sunnyKnows: "release dates + targets as evidence only",
    why: "no policy", wouldClose: "an Owner decision", relationshipsAffected: [], risk: "LOW", ownerImpact: "Sunny reports, never judges", futureActionImpact: "none", status: "CONFLICT_REQUIRES_OWNER_DECISION", appRemediation: "OWNER_DECISION", sunnyReadsVia: ["artist_portfolio"] }),
  G({ id: "LBL_NAME_LINKS", domain: "LABEL_ARTISTS", entityType: "artist links", class: "AMBIGUOUS_IDENTITY",
    description: "Artist ↔ project (except releases), show (via client name), Red Films, social and session links are by name; the portal / beats by a fixed name → slug table", redbloodsKnows: "names", sunnyKnows: "each link with its quality; collaborations flagged",
    why: "no artist id on those records", wouldClose: "artist ids on projects / shows / productions / campaigns (schema)", relationshipsAffected: ["artist ↔ projects / shows / clips / social"], risk: "MEDIUM", ownerImpact: "a rename breaks the portal, show → ledger and matching", futureActionImpact: "rename must be a guarded primitive", status: "PARTIALLY_CLOSED", appRemediation: "SCHEMA_CHANGE", sunnyReadsVia: ["artist_view:projects"] }),
  G({ id: "LBL_SHOW_LEDGER_EDGE_CASES", domain: "ARTIST_BALANCES", entityType: "show → ledger", class: "SYSTEM_BEHAVIOR_GAP",
    description: "Setting בוצע by a normal edit writes no ledger row; unticking 'paid' deletes nothing; reopen / cancel after close keeps income / payment; collaboration shows are skipped", redbloodsKnows: "behavior", sunnyKnows: "behavior + each ledger row's show source",
    why: "implementation", wouldClose: "bug-fix mission", relationshipsAffected: ["show ↔ ledger"], risk: "MEDIUM", ownerImpact: "the ledger may miss or keep show money", futureActionImpact: "CLOSE_SHOW must be idempotent", status: "OPEN", appRemediation: "BUG_FIX_MISSION", sunnyReadsVia: ["artist_view:money"] }),
  G({ id: "LBL_NO_PAYOUT_WORKFLOW", domain: "ARTIST_BALANCES", entityType: "payout", class: "DATA_MODEL_GAP",
    description: "Payouts are manual ledger rows (no payout method / schedule / approval)", redbloodsKnows: "payment rows", sunnyKnows: "payment rows + cycle snapshots",
    why: "not modelled", wouldClose: "an Owner decision on payout policy", relationshipsAffected: [], risk: "LOW", ownerImpact: "none today", futureActionImpact: "RECORD_ARTIST_PAYMENT", status: "OPEN", appRemediation: "OWNER_DECISION", sunnyReadsVia: ["artist_view:money"] }),
  G({ id: "LBL_PRODUCTION_HANDOFF_NOT_RECORDED", domain: "LABEL_ARTISTS", entityType: "production handoff", class: "DATA_NOT_RECORDED",
    description: "Who produces an artist song when it is not with Victor (in-house production, the artist themself)", redbloodsKnows: "sessions and the release 'responsible' free text only", sunnyKnows: "those, and asks when nothing is recorded",
    why: "no production-handoff record outside Victor", wouldClose: "Owner input per project (P2 blocker / release responsible)", relationshipsAffected: ["project → producer"], risk: "LOW", ownerImpact: "Sunny may ask 'who is producing?'", futureActionImpact: "none", status: "DATA_NOT_RECORDED", appRemediation: "OWNER_INPUT", sunnyReadsVia: ["artist_view:next_steps"] }),
  G({ id: "LBL_ARTIST_ACTIONS_NOT_EXECUTABLE", domain: "LABEL_ARTISTS", entityType: "artist action", class: "FUTURE_PRIMITIVE_REQUIRED",
    description: "Every artist / release / beat / ledger / cycle / media / show / session / notify action", redbloodsKnows: "the dashboard + portal actions", sunnyKnows: "each action, effects and approval class (artist_model actions)",
    why: "no approved typed primitive", wouldClose: "typed primitives with preview + Owner approval", relationshipsAffected: [], risk: "LOW", ownerImpact: "the Owner performs them", futureActionImpact: "roadmap", status: "OPEN", appRemediation: "NONE", sunnyReadsVia: ["system_awareness:artist_model"] }),
  G({ id: "LBL_CYCLE_REMINDER_BUG", domain: "ARTIST_BALANCES", entityType: "push", class: "SYSTEM_BEHAVIOR_GAP",
    description: "The balance-cycle reminder push has no production guard and deep-links every artist to Shalev's balance tab", redbloodsKnows: "behavior", sunnyKnows: "behavior",
    why: "implementation", wouldClose: "bug-fix mission", relationshipsAffected: [], risk: "LOW", ownerImpact: "Avi / CLEANTONE would land on a page they cannot open", futureActionImpact: "NOTIFY_ARTIST", status: "OPEN", appRemediation: "BUG_FIX_MISSION", sunnyReadsVia: ["system_awareness:artist_model"] }),
  // ── Shows + DJ Deep Brain (2026-09-25) ──
  G({ id: "SHW_PERFORMANCE_FILES_NOT_READ", domain: "SHOWS", entityType: "performance file", class: "CAPABILITY_GAP",
    description: "Performance audio files (per artist, not per show) in the artist's storage folder", redbloodsKnows: "files in storage only (no database metadata)", sunnyKnows: "that they exist per artist; not the list",
    why: "credential-free read path", wouldClose: "an Owner-approved read-only storage listing primitive", relationshipsAffected: ["artist → performance files"], risk: "LOW", ownerImpact: "Sunny cannot say which performance files exist", futureActionImpact: "none", status: "OPEN", appRemediation: "OAUTH_OR_INTEGRATION_APPROVAL", sunnyReadsVia: ["show_view:portal"] }),
  G({ id: "SHW_NO_CURRENCY", domain: "SHOWS", entityType: "show money", class: "DATA_MODEL_GAP",
    description: "Shows store no currency; every show finance row is written as ₪", redbloodsKnows: "amounts only", sunnyKnows: "amounts labelled currency NOT_STORED; the finance rows' ₪",
    why: "no currency column", wouldClose: "a currency column (schema)", relationshipsAffected: ["show → finance"], risk: "LOW", ownerImpact: "a foreign-currency show would be booked as ₪", futureActionImpact: "CREATE_SHOW must carry the currency", status: "OPEN", appRemediation: "SCHEMA_CHANGE", sunnyReadsVia: ["show_view:money"] }),
  G({ id: "SHW_NO_READINESS_MODEL", domain: "SHOWS", entityType: "show preparation", class: "OWNER_DECISION_REQUIRED",
    description: "What 'ready for the show' means", redbloodsKnows: "DJ / confirmation / markers / rehearsals / calendar / payment / tasks", sunnyKnows: "all of that as evidence; never a readiness score",
    why: "no checklist", wouldClose: "an Owner definition", relationshipsAffected: [], risk: "LOW", ownerImpact: "Sunny lists evidence and asks", futureActionImpact: "none", status: "CONFLICT_REQUIRES_OWNER_DECISION", appRemediation: "OWNER_DECISION", sunnyReadsVia: ["show_view:signals"] }),
  G({ id: "SHW_HISTORY_NOT_RECORDED", domain: "SHOWS", entityType: "show history", class: "DATA_NOT_RECORDED",
    description: "Status / price / DJ / payment change history", redbloodsKnows: "created / updated times, DJ confirmation time, sent times, ledger dates", sunnyKnows: "a timeline of those only",
    why: "no audit trail", wouldClose: "a change log (schema)", relationshipsAffected: [], risk: "LOW", ownerImpact: "'when was it confirmed / reopened?' is unknowable", futureActionImpact: "none", status: "DATA_NOT_RECORDED", appRemediation: "SCHEMA_CHANGE", sunnyReadsVia: ["show_view:history"] }),
  G({ id: "SHW_LEDGER_FINANCE_EDGES", domain: "SHOWS", entityType: "show money", class: "SYSTEM_BEHAVIOR_GAP",
    description: "Back-to-pipeline hard-deletes received income; cancel / delete after close keeps realized ledger money; a plain edit to בוצע writes no ledger; price edits after close do not reach the ledger; the close preview ignores rehearsal costs; the DJ-fee row is created with no DJ; deleting a rehearsal leaves its expense and a stale split", redbloodsKnows: "behavior", sunnyKnows: "behavior + per-show signals (DONE_WITHOUT_LEDGER, LEDGER_KEPT_AFTER_CANCEL, DJ_FEE_WITHOUT_DJ)",
    why: "implementation", wouldClose: "bug-fix mission", relationshipsAffected: ["show ↔ finance ↔ ledger"], risk: "MEDIUM", ownerImpact: "show state and money can disagree", futureActionImpact: "show primitives must be idempotent", status: "OPEN", appRemediation: "BUG_FIX_MISSION", sunnyReadsVia: ["show_view:money", "show_view:ledger"] }),
  G({ id: "SHW_DJ_CONFIRMATION_EDGES", domain: "LABEL_DJ", entityType: "DJ confirmation", class: "SYSTEM_BEHAVIOR_GAP",
    description: "Confirmation not reset by date / place change or cancel; the DJ portal shows the client's payment and lists leads / past shows as upcoming", redbloodsKnows: "behavior", sunnyKnows: "behavior + DJ_CONFIRMED_BEFORE_CHANGE",
    why: "implementation", wouldClose: "bug-fix mission", relationshipsAffected: ["show ↔ DJ"], risk: "LOW", ownerImpact: "a confirmation may refer to old details", futureActionImpact: "ASSIGN_SHOW_DJ", status: "OPEN", appRemediation: "BUG_FIX_MISSION", sunnyReadsVia: ["show_view:dj"] }),
  G({ id: "SHW_ARTIST_BY_TEXT", domain: "SHOWS", entityType: "show artist", class: "AMBIGUOUS_IDENTITY",
    description: "The artist is a client id + display text; roster membership, ledger sync and the artist push use the TEXT (single exact name; collaborations skipped)", redbloodsKnows: "client id + text", sunnyKnows: "both, with quality; collaboration flagged",
    why: "no label-artist id on shows", wouldClose: "a label-artist id on shows (schema)", relationshipsAffected: ["show ↔ label artist"], risk: "MEDIUM", ownerImpact: "a renamed artist loses show → ledger sync", futureActionImpact: "CREATE_SHOW", status: "PARTIALLY_CLOSED", appRemediation: "SCHEMA_CHANGE", sunnyReadsVia: ["show_view:artist"] }),
  G({ id: "SHW_CONSUMERS_DISAGREE", domain: "SHOWS", entityType: "show counts", class: "CONFLICTING_SOURCES",
    description: "Which shows count as upcoming / expected differs by screen (leads included in label page, recoup and dashboard)", redbloodsKnows: "each screen's rule", sunnyKnows: "every consumer's rule (show_model status_consumers)",
    why: "separate implementations", wouldClose: "one shared rule (bug-fix)", relationshipsAffected: [], risk: "LOW", ownerImpact: "different expected totals per screen", futureActionImpact: "none", status: "PARTIALLY_CLOSED", appRemediation: "BUG_FIX_MISSION", sunnyReadsVia: ["system_awareness:show_model"] }),
  G({ id: "SHW_ADVANCE_NOT_A_ROW", domain: "SHOWS", entityType: "advance", class: "DATA_MODEL_GAP",
    description: "The client advance is an amount on the show (no date, no finance row); מקדמה counts as unpaid", redbloodsKnows: "amount + payment status", sunnyKnows: "both; remaining as the UI computes it",
    why: "not modelled", wouldClose: "an advance as a received income row (schema / finance decision)", relationshipsAffected: ["show → finance"], risk: "LOW", ownerImpact: "cash received as an advance is invisible to finance totals", futureActionImpact: "RECORD_SHOW_ADVANCE", status: "OPEN", appRemediation: "OWNER_DECISION", sunnyReadsVia: ["show_view:money"] }),
  G({ id: "SHW_ACTIONS_NOT_EXECUTABLE", domain: "SHOWS", entityType: "show action", class: "FUTURE_PRIMITIVE_REQUIRED",
    description: "Create / edit / assign DJ / close / cancel / delete / notify artist / notify DJ / rehearsal", redbloodsKnows: "the dashboard actions", sunnyKnows: "each action + effects + approval class (show_model actions)",
    why: "no approved typed primitive", wouldClose: "typed primitives with preview + Owner approval", relationshipsAffected: [], risk: "LOW", ownerImpact: "the Owner performs them", futureActionImpact: "roadmap", status: "OPEN", appRemediation: "NONE", sunnyReadsVia: ["system_awareness:show_model"] }),
  G({ id: "SHW_NO_REMINDERS", domain: "SHOWS", entityType: "show reminder", class: "DATA_MODEL_GAP",
    description: "No automatic show reminder / cron exists (only manual 'שלח')", redbloodsKnows: "nothing scheduled", sunnyKnows: "that nothing reminds anyone automatically",
    why: "not built", wouldClose: "an Owner decision (Sunny may surface upcoming shows itself)", relationshipsAffected: [], risk: "LOW", ownerImpact: "none today", futureActionImpact: "NOTIFY_ARTIST_DJ", status: "OPEN", appRemediation: "OWNER_DECISION", sunnyReadsVia: ["show_portfolio"] }),
  // ── Victor Deep Brain (2026-09-25) ──
  G({ id: "VIC_STORAGE_NOT_READ", domain: "VICTOR", entityType: "Victor file", class: "CAPABILITY_GAP",
    description: "The actual files in Victor's storage folders", redbloodsKnows: "stored file entries (name, version, upload time, path) — storage itself", sunnyKnows: "the stored entries only",
    why: "credential-free read path", wouldClose: "an Owner-approved read-only storage listing primitive", relationshipsAffected: ["work → files"], risk: "LOW", ownerImpact: "files added outside Redbloods are invisible", futureActionImpact: "none", status: "OPEN", appRemediation: "OAUTH_OR_INTEGRATION_APPROVAL", sunnyReadsVia: ["victor_view"] }),
  G({ id: "VIC_WORK_WITHOUT_PROJECT", domain: "VICTOR", entityType: "Victor work", class: "DATA_MODEL_GAP",
    description: "Most Victor works (24 of 31) have no project — no artist / client / label / deadline context", redbloodsKnows: "title only", sunnyKnows: "the title and that the context is missing",
    why: "standalone works are allowed", wouldClose: "linking works to projects (Owner input) or a required project (schema / UX)", relationshipsAffected: ["work → project"], risk: "MEDIUM", ownerImpact: "Sunny cannot say which artist / client most Victor work is for", futureActionImpact: "LINK_VICTOR_WORK", status: "OPEN", appRemediation: "OWNER_INPUT", sunnyReadsVia: ["victor_portfolio"] }),
  G({ id: "VIC_NO_VERSION_RECORDS", domain: "VICTOR", entityType: "version", class: "DATA_MODEL_GAP",
    description: "Versions are client-chosen labels on file entries (not records); 'latest' = append order; review status always 'waiting'", redbloodsKnows: "labels + upload times + notes", sunnyKnows: "the same, labelled as such",
    why: "not modelled", wouldClose: "version + review-decision records (schema)", relationshipsAffected: ["work → versions → notes"], risk: "LOW", ownerImpact: "no 'approved' state", futureActionImpact: "APPROVE_VICTOR_VERSION", status: "OPEN", appRemediation: "SCHEMA_CHANGE", sunnyReadsVia: ["victor_view"] }),
  G({ id: "VIC_NO_MIX_HANDOFF", domain: "VICTOR", entityType: "production → mix", class: "DATA_MODEL_GAP",
    description: "No record links a finished Victor work to the mix engineer / stems / final production", redbloodsKnows: "separate engineer work on the project", sunnyKnows: "engineer work on the same project as evidence only",
    why: "not modelled", wouldClose: "a production-handoff record (schema)", relationshipsAffected: ["Victor → mix"], risk: "MEDIUM", ownerImpact: "Sunny cannot prove production moved to mix", futureActionImpact: "HANDOFF_TO_MIX", status: "OPEN", appRemediation: "SCHEMA_CHANGE", sunnyReadsVia: ["victor_view"] }),
  G({ id: "VIC_SALARY_SOURCES_CONFLICT", domain: "VICTOR", entityType: "salary month", class: "CONFLICTING_SOURCES",
    description: "Salary status overrides (May–Aug paid) vs finance rows (only Aug) vs legacy keys (May / June expected)", redbloodsKnows: "all four sources", sunnyKnows: "all four per month with proof level; Finance is the canonical money",
    why: "overrides outrank finance in the salary view; the live UI cannot create finance rows", wouldClose: "an Owner decision + recording the missing finance rows through the approved action", relationshipsAffected: ["salary → finance"], risk: "MEDIUM", ownerImpact: "May–July 2026 are 'paid' only by statement", futureActionImpact: "RECORD_PAID_EXPENSE", status: "CONFLICT_REQUIRES_OWNER_DECISION", appRemediation: "OWNER_DECISION", sunnyReadsVia: ["victor_view"] }),
  G({ id: "VIC_GOAL_VS_PAY", domain: "VICTOR", entityType: "arrangement", class: "OWNER_DECISION_REQUIRED",
    description: "Whether '$550 for 12 projects' is the current arrangement", redbloodsKnows: "salary 550 $ and a monthly goal 12 (KPI) — not linked in code", sunnyKnows: "both, never as a pay rule",
    why: "no pay-per-project rule exists", wouldClose: "an Owner answer", relationshipsAffected: [], risk: "LOW", ownerImpact: "Sunny will not treat 12 as a quota", futureActionImpact: "none", status: "CONFLICT_REQUIRES_OWNER_DECISION", appRemediation: "OWNER_DECISION", sunnyReadsVia: ["victor_view"] }),
  G({ id: "VIC_BEHAVIOR_BUGS", domain: "VICTOR", entityType: "Victor behavior", class: "SYSTEM_BEHAVIOR_GAP",
    description: "Stuck cron never fires (status vs work-state values); stuck thresholds disagree; duplicate works possible; work_state / outcome / quality / entered-project never maintained; Owner uploads count as Victor uploads in the ball rule", redbloodsKnows: "behavior", sunnyKnows: "behavior + per-work caveats",
    why: "implementation", wouldClose: "bug-fix mission", relationshipsAffected: [], risk: "MEDIUM", ownerImpact: "no stuck reminder; the ball can point at the Owner after the Owner's own upload", futureActionImpact: "none", status: "OPEN", appRemediation: "BUG_FIX_MISSION", sunnyReadsVia: ["system_awareness:victor_model"] }),
  G({ id: "VIC_HISTORY_NOT_RECORDED", domain: "VICTOR", entityType: "Victor history", class: "DATA_NOT_RECORDED",
    description: "Status / deadline changes, sent-work pushes (no marker), review decisions", redbloodsKnows: "sent / returned dates, upload + notes times, completion marker", sunnyKnows: "a timeline of those",
    why: "no audit trail", wouldClose: "a change log (schema)", relationshipsAffected: [], risk: "LOW", ownerImpact: "'when was the deadline moved?' is unknowable", futureActionImpact: "none", status: "DATA_NOT_RECORDED", appRemediation: "SCHEMA_CHANGE", sunnyReadsVia: ["victor_view"] }),
  G({ id: "VIC_OUTSIDE_COMMUNICATION", domain: "VICTOR", entityType: "communication", class: "CAPABILITY_GAP",
    description: "WhatsApp / phone / in-person exchanges with Victor", redbloodsKnows: "nothing", sunnyKnows: "that they exist — stale in-app handoffs become questions",
    why: "no integration", wouldClose: "the Owner telling Sunny", relationshipsAffected: ["work → handoff"], risk: "MEDIUM", ownerImpact: "Sunny asks", futureActionImpact: "none", status: "OPEN", appRemediation: "OWNER_INPUT", sunnyReadsVia: ["victor_view"] }),
  G({ id: "VIC_ACTIONS_NOT_EXECUTABLE", domain: "VICTOR", entityType: "Victor action", class: "FUTURE_PRIMITIVE_REQUIRED",
    description: "Send / notify / deadline / status / notes / delete / remove / salary overrides (salary finance row = the approved Partner action)", redbloodsKnows: "the dashboard actions", sunnyKnows: "each action + effects (victor_model actions)",
    why: "no approved typed primitive", wouldClose: "typed primitives with preview + Owner approval", relationshipsAffected: [], risk: "LOW", ownerImpact: "the Owner performs them", futureActionImpact: "roadmap", status: "OPEN", appRemediation: "NONE", sunnyReadsVia: ["system_awareness:victor_model"] }),
  G({ id: "VIC_PORTAL_FILE_SECURITY", domain: "VICTOR", entityType: "file access", class: "SYSTEM_BEHAVIOR_GAP",
    description: "REMEDIATED 2026-09-25 (Victor portal security hardening). Victor could inject file paths / his work folder and then stream, delete or upload anywhere in the storage account; he could delete the Owner's uploads; upload responses leaked paths and public links; several storage routes relied on the proxy only. Now: no Victor PATCH, folder-scoped paths, uploader-checked delete, minimal responses, in-route Owner checks. Residue: chunked-upload sessions open without a work check (only the commit is scoped).", redbloodsKnows: "behavior", sunnyKnows: "the remediation and the residue (security gaps) — proven by the Victor portal security tests, never tested destructively",
    why: "unvalidated fields in Victor's PATCH allowlist (fixed)", wouldClose: "the residue: the client sends the work id on the first chunk (a client + server change)", relationshipsAffected: ["Victor → storage"], risk: "LOW", ownerImpact: "company files outside a work's folder are no longer reachable from Victor's account", futureActionImpact: "none", status: "PARTIALLY_CLOSED", appRemediation: "SECURITY_FIX", sunnyReadsVia: ["system_awareness:victor_model"] }),
  G({ id: "VIC_LEGACY_FILE_UPLOADER", domain: "VICTOR", entityType: "file", class: "DATA_NOT_RECORDED",
    description: "Who uploaded a version file is recorded only since 2026-09-25; the 101 older entries have no uploader (Owner or Victor unknown). Victor cannot delete them (fail closed); the Owner can.", redbloodsKnows: "no (older entries)", sunnyKnows: "that the uploader is unknown for older entries",
    why: "no uploader field before the hardening", wouldClose: "an Owner decision per file, or accepting that older files are Owner-deleted only", relationshipsAffected: ["file → uploader"], risk: "LOW", ownerImpact: "Victor may ask the Owner to remove an old upload of his", futureActionImpact: "DELETE_VICTOR_FILE stays DESTRUCTIVE", status: "DATA_NOT_RECORDED", appRemediation: "OWNER_INPUT", sunnyReadsVia: ["system_awareness:victor_model"] }),
  // ── Steven + Mix Pipeline Deep Brain (2026-09-25) ──
  G({ id: "MIX_NO_ENGINEER_IDENTITY", domain: "MIX_PIPELINE", entityType: "engineer", class: "AMBIGUOUS_IDENTITY",
    description: "An engineer is only a free-text name on a work; exactly 'Steven' is Steven. No engineer record, no id, no rate, no contact.", redbloodsKnows: "the name as typed", sunnyKnows: "the name + whether it is exactly Steven",
    why: "engineers were never modelled as records", wouldClose: "an engineer record (schema) or Owner-confirmed aliases", relationshipsAffected: ["work → engineer"], risk: "LOW", ownerImpact: "a typo is another engineer; other engineers get no portal", futureActionImpact: "engineer-targeted actions need an identity first", status: "OPEN", appRemediation: "SCHEMA_CHANGE", sunnyReadsVia: ["mix_view", "mix_portfolio"] }),
  G({ id: "MIX_NO_PRODUCTION_HANDOFF", domain: "MIX_PIPELINE", entityType: "production → mix", class: "DATA_MODEL_GAP",
    description: "No production → mix handoff record: only the project status, the engineer work, an unlinked send-log entry and markers. A Victor work is never linked to the engineer work.", redbloodsKnows: "fragments", sunnyKnows: "the fragments, labelled as evidence",
    why: "not modelled (the send log only links Victor works)", wouldClose: "a handoff record / a send-log link to engineer works (schema)", relationshipsAffected: ["Victor work → engineer work"], risk: "MEDIUM", ownerImpact: "did production move to mix? needs evidence, not a fact", futureActionImpact: "none", status: "OPEN", appRemediation: "SCHEMA_CHANGE", sunnyReadsVia: ["mix_view:work/handoff", "mix_view"] }),
  G({ id: "MIX_NO_APPROVAL_RECORD", domain: "MIX_PIPELINE", entityType: "mix approval", class: "DATA_NOT_RECORDED",
    description: "No Owner approval of a mix is recorded: the version status is never used (all בבדיקה) and אושר is the completed status. Approved cannot be proven.", redbloodsKnows: "no", sunnyKnows: "that it is not recorded",
    why: "no approval concept in use", wouldClose: "an Owner decision to use the version status / an approval action", relationshipsAffected: ["version → approval"], risk: "LOW", ownerImpact: "Sunny never says approved", futureActionImpact: "APPROVE_MIX_VERSION would need a defined meaning", status: "DATA_NOT_RECORDED", appRemediation: "OWNER_DECISION", sunnyReadsVia: ["mix_view:work/versions"] }),
  G({ id: "MIX_UPLOADER_NOT_PROVABLE", domain: "MIX_PIPELINE", entityType: "version / final file", class: "SYSTEM_BEHAVIOR_GAP",
    description: "Version files record the ENGINEER NAME as uploader even when the Owner uploads; final files show Steven on every row. Who uploaded cannot be proven, and an Owner upload looks like an engineer delivery in the ball evidence.", redbloodsKnows: "no", sunnyKnows: "the caveat",
    why: "the upload path writes the work's engineer name", wouldClose: "record the session role at upload (code change)", relationshipsAffected: ["version → uploader"], risk: "LOW", ownerImpact: "an Owner upload can read as waiting on Owner", futureActionImpact: "none", status: "OPEN", appRemediation: "BUG_FIX_MISSION", sunnyReadsVia: ["mix_view:work/handoff"] }),
  G({ id: "MIX_RESOLVE_NO_WHO_WHEN", domain: "MIX_PIPELINE", entityType: "comment", class: "DATA_NOT_RECORDED",
    description: "A comment resolve / reopen records no who and no when (the updated time also moves on edits); comment authors are never recorded.", redbloodsKnows: "open / resolved only", sunnyKnows: "open / resolved + the caveat",
    why: "no fields for it", wouldClose: "resolved-by / resolved-at (schema)", relationshipsAffected: ["comment → resolver"], risk: "LOW", ownerImpact: "did Steven handle it? is not provable", futureActionImpact: "none", status: "DATA_NOT_RECORDED", appRemediation: "SCHEMA_CHANGE", sunnyReadsVia: ["mix_view:work/comments"] }),
  G({ id: "MIX_NOTES_SENT_HISTORY", domain: "MIX_PIPELINE", entityType: "notes send", class: "DATA_NOT_RECORDED",
    description: "Send notes is kept only while a reminder cycle is active or reached a reminder; a send answered within 5 hours leaves no trace. There is no listened / reviewed record either.", redbloodsKnows: "partially", sunnyKnows: "the recorded instants",
    why: "the cycle row is deleted when it stops", wouldClose: "a notes-sent log (settings or schema)", relationshipsAffected: ["work → notes sent"], risk: "LOW", ownerImpact: "handoff evidence is sometimes thinner than reality", futureActionImpact: "SEND_MIX_NOTES", status: "DATA_NOT_RECORDED", appRemediation: "BUG_FIX_MISSION", sunnyReadsVia: ["mix_view:work/handoff"] }),
  G({ id: "MIX_TWO_FINANCE_WRITERS", domain: "MIX_PIPELINE", entityType: "engineer payment", class: "CONFLICTING_SOURCES",
    description: "Two writers use one expense link: the price sync (work currency, amount = agreed, status from amounts) and the Steven payment sync (₪ × 3.25, שולם, deleted when unpaid). The work's paid fields are manual, not from Finance.", redbloodsKnows: "both", sunnyKnows: "both + per-work conflicts",
    why: "two eras of payment recording", wouldClose: "one payment primitive (Owner decision + code)", relationshipsAffected: ["work → expense"], risk: "MEDIUM", ownerImpact: "Finance can disagree with the work's paid state", futureActionImpact: "RECORD_ENGINEER_PAYMENT must pick one writer", status: "OPEN", appRemediation: "OWNER_DECISION", sunnyReadsVia: ["mix_view:money"] }),
  G({ id: "MIX_EXPENSE_SCOPE_GENERAL", domain: "MIX_PIPELINE", entityType: "engineer expense", class: "SYSTEM_BEHAVIOR_GAP",
    description: "The Steven payment sync writes expense scope כללי (all 9 production payment expenses); the intended engineer expense scope is מיקס / מאסטר. The price sync writes none.", redbloodsKnows: "yes", sunnyKnows: "yes (per expense)",
    why: "a hard-coded value in the payment sync", wouldClose: "a code fix + an approved historical correction (not done here)", relationshipsAffected: ["expense → scope"], risk: "LOW", ownerImpact: "mix spend is filed as general spend", futureActionImpact: "none", status: "OPEN", appRemediation: "BUG_FIX_MISSION", sunnyReadsVia: ["mix_view:money"] }),
  G({ id: "MIX_FIXED_RATIO_NOT_POLICY", domain: "MIX_PIPELINE", entityType: "engineer rate", class: "OWNER_DECISION_REQUIRED",
    description: "Steven's payment is recorded in ₪ at a hard-coded $→₪ 3.25 with a ×1.05 PayPal note, and the project send pre-fills $200. None of it is stored policy; no default rate, fee rule or payment terms exist. The route applies the ratio to any engineer.", redbloodsKnows: "code values only", sunnyKnows: "the values, labelled IMPLEMENTATION_BEHAVIOR",
    why: "working values in code", wouldClose: "an Owner decision on the rate / fee / conversion", relationshipsAffected: ["work → expense amount"], risk: "MEDIUM", ownerImpact: "recorded ₪ may not match what was actually paid", futureActionImpact: "RECORD_ENGINEER_PAYMENT", status: "CONFLICT_REQUIRES_OWNER_DECISION", appRemediation: "OWNER_DECISION", sunnyReadsVia: ["mix_view:money", "system_awareness:mix_model"] }),
  G({ id: "MIX_ORPHAN_EXPENSES", domain: "MIX_PIPELINE", entityType: "engineer expense", class: "LEGACY_CONFLICT",
    description: "6 mix / master expenses are linked to no engineer work: 5 unpaid $ rows (5 / 50 / 3 / 30 / 300, 2026-06-29 — leftovers of the old price sync) and 1 paid ₪590.", redbloodsKnows: "the rows", sunnyKnows: "the rows (never fuzzy-linked)",
    why: "an old sync created rows while a price was being typed", wouldClose: "an Owner decision per row (not done here)", relationshipsAffected: ["expense → work"], risk: "LOW", ownerImpact: "unpaid mix expenses that are not real debts", futureActionImpact: "none", status: "CONFLICT_REQUIRES_OWNER_DECISION", appRemediation: "OWNER_DECISION", sunnyReadsVia: ["mix_view:money"] }),
  G({ id: "MIX_FINAL_FILE_TYPE", domain: "MIX_PIPELINE", entityType: "final file", class: "DATA_MODEL_GAP",
    description: "Final files carry no type (mix / master / stems / instrumental / acapella / performance / radio edit) and are not linked to the client delivery or the release.", redbloodsKnows: "file names only", sunnyKnows: "names, counts, times",
    why: "not modelled", wouldClose: "a final-file type + a delivery link (schema)", relationshipsAffected: ["final file → delivery", "final file → release"], risk: "LOW", ownerImpact: "is there a master? is answered from file names only", futureActionImpact: "none", status: "OPEN", appRemediation: "SCHEMA_CHANGE", sunnyReadsVia: ["mix_view:work/final_files"] }),
  G({ id: "MIX_STATUS_HISTORY", domain: "MIX_PIPELINE", entityType: "engineer work", class: "DATA_NOT_RECORDED",
    description: "No history of status, engineer, price, deadline or payment changes (updated time only); completion time is not recorded.", redbloodsKnows: "no", sunnyKnows: "the timeline from upload / comment / final-file / payment dates only",
    why: "no audit table", wouldClose: "a change log (schema)", relationshipsAffected: ["work → history"], risk: "LOW", ownerImpact: "when was it completed? is unknown", futureActionImpact: "none", status: "DATA_NOT_RECORDED", appRemediation: "SCHEMA_CHANGE", sunnyReadsVia: ["mix_view:work/timeline"] }),
  G({ id: "MIX_STEVEN_ASSUMPTIONS_GENERIC", domain: "MIX_PIPELINE", entityType: "push / payment", class: "SYSTEM_BEHAVIOR_GAP",
    description: "Steven-specific behavior is not restricted to Steven's works: the Payment sent push (any engineer), the ₪ payment sync and the Send notes / Send to Steven pushes have no engineer check. No other engineer exists in production today.", redbloodsKnows: "behavior", sunnyKnows: "the finding (never exercised)",
    why: "built when Steven was the only engineer", wouldClose: "engineer checks (a separate approved fix)", relationshipsAffected: ["engineer → push"], risk: "LOW", ownerImpact: "a future Bill payment would push Steven", futureActionImpact: "none", status: "OPEN", appRemediation: "BUG_FIX_MISSION", sunnyReadsVia: ["system_awareness:mix_model"] }),
  G({ id: "MIX_STORAGE_NOT_LISTED", domain: "MIX_PIPELINE", entityType: "file", class: "CAPABILITY_GAP",
    description: "Sunny reads version / final-file / attachment records, never the storage itself: a missing record is not a missing file.", redbloodsKnows: "records", sunnyKnows: "records",
    why: "no approved read-only storage listing", wouldClose: "an Owner-approved read-only listing primitive", relationshipsAffected: ["work → storage"], risk: "LOW", ownerImpact: "files placed straight in storage are invisible", futureActionImpact: "none", status: "OPEN", appRemediation: "OAUTH_OR_INTEGRATION_APPROVAL", sunnyReadsVia: ["mix_view"] }),
  G({ id: "MIX_ALBUM_TRACK_STATUS_UNLINKED", domain: "MIX_PIPELINE", entityType: "album track", class: "DATA_MODEL_GAP",
    description: "Album tracks carry their own manual mix / master status, not linked to engineer works.", redbloodsKnows: "both, separately", sunnyKnows: "both, separately",
    why: "two concepts", wouldClose: "a track → work link (schema)", relationshipsAffected: ["album track → engineer work"], risk: "LOW", ownerImpact: "two mix statuses for one album song can disagree", futureActionImpact: "none", status: "OPEN", appRemediation: "SCHEMA_CHANGE", sunnyReadsVia: ["albums", "mix_view"] }),
  // ── secrets (the ONLY intentional exclusion) ──
  G({ id: "SECRET_INTEGRATION_TOKENS", domain: "PLATFORM_ACCESS", entityType: "credential", class: "INTENTIONALLY_SECRET",
    description: "Google / Dropbox OAuth tokens, service keys, cron / webhook secrets, passwords, cookies", redbloodsKnows: "the credentials", sunnyKnows: "that each integration exists, whether it is connected, what it does and what depends on it — never the secret",
    why: "credentials are not knowledge", wouldClose: "never (by design)", relationshipsAffected: [], risk: "HIGH", ownerImpact: "none", futureActionImpact: "none", status: "CLOSED_NOW", appRemediation: "NONE", sunnyReadsVia: ["integrations"] }),
  G({ id: "SECRET_SHARE_LINKS", domain: "FILES_DROPBOX", entityType: "public share link / share token", class: "INTENTIONALLY_SECRET",
    description: "Dropbox public share links and share tokens stored with files / folders", redbloodsKnows: "the bearer URLs", sunnyKnows: "that a file / folder HAS a share link (hasShareLink) — never the URL",
    why: "anyone holding the link can open the file (bearer access material)", wouldClose: "never (by design)", relationshipsAffected: [], risk: "HIGH", ownerImpact: "none", futureActionImpact: "sharing stays an EXTERNAL_EFFECT action", status: "CLOSED_NOW", appRemediation: "NONE", sunnyReadsVia: ["project_view:files"] }),
];

/** Complete-knowledge status per system domain (Part N: the next deep-brain missions). */
export type DomainDepth = "DEEP_BRAIN_COMPLETE_STANDARD" | "DEEP_BRAIN_V1" | "SYSTEM_AWARENESS_ONLY" | "PENDING_DEEP_MISSION";
export const DOMAIN_KNOWLEDGE_DEPTH: Readonly<Record<string, DomainDepth>> = {
  PROJECTS: "DEEP_BRAIN_COMPLETE_STANDARD", PROJECT_ACTIONS: "DEEP_BRAIN_COMPLETE_STANDARD",
  PLATFORM_ACCESS: "DEEP_BRAIN_V1", ARTIST_PORTALS: "DEEP_BRAIN_V1", PUSH_NOTIFICATIONS: "DEEP_BRAIN_V1", FINANCE: "DEEP_BRAIN_V1",
  CLIENTS: "DEEP_BRAIN_V1", PROPOSALS: "DEEP_BRAIN_V1", SESSIONS: "PENDING_DEEP_MISSION", GOOGLE_CALENDAR: "DEEP_BRAIN_V1", TASKS: "PENDING_DEEP_MISSION",
  MEETINGS: "PENDING_DEEP_MISSION", ALBUMS: "PENDING_DEEP_MISSION", DELIVERY: "PENDING_DEEP_MISSION", LABEL_ARTISTS: "DEEP_BRAIN_V1", SHOWS: "DEEP_BRAIN_V1",
  LABEL_DJ: "DEEP_BRAIN_V1", ARTIST_BALANCES: "PENDING_DEEP_MISSION", MEDIA_INCOME: "PENDING_DEEP_MISSION", RELEASES: "PENDING_DEEP_MISSION", BEATS: "PENDING_DEEP_MISSION",
  VICTOR: "DEEP_BRAIN_V1", STEVEN: "DEEP_BRAIN_V1", MIX_PIPELINE: "DEEP_BRAIN_V1", RED_FILMS: "PENDING_DEEP_MISSION", CLIPS: "PENDING_DEEP_MISSION",
  SOCIAL: "PENDING_DEEP_MISSION", FILES_DROPBOX: "PENDING_DEEP_MISSION", REPORTS: "PENDING_DEEP_MISSION", AGENT_ALERTS: "SYSTEM_AWARENESS_ONLY", COMPANY_OVERVIEW: "SYSTEM_AWARENESS_ONLY",
  SUNNY_CORE: "PENDING_DEEP_MISSION", SUNNY_CONNECTOR: "PENDING_DEEP_MISSION",
};

export function validateKnowledgeGaps(o: { domainIds: readonly string[]; capabilityIds: readonly string[] }): string[] {
  const errs: string[] = [];
  const ids = new Set<string>();
  for (const g of KNOWLEDGE_GAPS) {
    if (!/^[A-Z][A-Z0-9_]{2,50}$/.test(g.id)) errs.push(`bad gap id ${g.id}`);
    if (ids.has(g.id)) errs.push(`duplicate gap ${g.id}`);
    ids.add(g.id);
    if (!o.domainIds.includes(g.domain)) errs.push(`${g.id}: unknown domain ${g.domain}`);
    for (const via of g.sunnyReadsVia) if (!o.capabilityIds.includes(via.split(":")[0])) errs.push(`${g.id}: unknown capability ${via}`);
    if (g.class === "INTENTIONALLY_SECRET" && !g.id.startsWith("SECRET_")) errs.push(`${g.id}: INTENTIONALLY_SECRET is reserved for credentials / bearer access (SECRET_*)`);
    if (g.status === "CLOSED_NOW" && g.sunnyReadsVia.length === 0) errs.push(`${g.id}: CLOSED_NOW needs a read path`);
    for (const k of ["description", "redbloodsKnows", "sunnyKnows", "why", "wouldClose"] as const) if (!g[k].trim()) errs.push(`${g.id}: empty ${k}`);
  }
  for (const d of o.domainIds) if (!(d in DOMAIN_KNOWLEDGE_DEPTH)) errs.push(`domain ${d} has no knowledge-depth status`);
  return errs;
}
