/**
 * Sunny System Awareness — the PROJECT ACTION INVENTORY: every mutation Redbloods OS can make today that touches a
 * project or project-linked data, from the smallest field edit to a destructive cascade (discovered from the route
 * handlers, 2026-09-25). READ-ONLY knowledge + the roadmap for "Sunny can eventually do everything with Owner
 * approval". NOTHING here is executable by Sunny: the only live Sunny primitive is UPDATE_PROJECT_DEADLINE
 * (approved + executed in the dashboard).
 *
 * The permanent ACTION CONTRACT every future Sunny primitive must satisfy is ACTION_CONTRACT_FIELDS; the confirmation
 * strength is the approval class. No generic writer, no generic SQL, ever.
 *
 * `internal.routes` exists only for the coverage test (every mutating project route must be inventoried) and is
 * never served.
 */

export type ApprovalClass =
  /** single field / reversible / no external effect — Owner approves the exact change */
  | "STANDARD"
  /** changes money state — Owner approves the exact amounts + currency */
  | "FINANCIAL"
  /** reaches outside Redbloods (calendar invite, push, public link, Dropbox) — Owner approves the external effect too */
  | "EXTERNAL_EFFECT"
  /** deletes / cannot be undone — typed confirmation of the target name + what is lost */
  | "DESTRUCTIVE"
  /** many records at once — per-record preview + count confirmation */
  | "BULK"
  /** who can see / do what — out of Sunny's delegation until the Owner decides otherwise */
  | "ACCESS";

export const APPROVAL_CLASSES: Readonly<Record<ApprovalClass, string>> = {
  STANDARD: "Owner approves the exact previewed change; reversible.",
  FINANCIAL: "Owner approves the exact amount, currency and status; the preview shows the finance verdict before and after.",
  EXTERNAL_EFFECT: "Owner approves the change AND each external effect (calendar invite, push, public link, Dropbox write) listed in the preview.",
  DESTRUCTIVE: "Strong confirmation: the Owner re-types / confirms the target and sees everything that will be lost or left behind; never batched with other actions.",
  BULK: "Per-record preview + total count; the Owner confirms the count; executed as one bounded batch with per-record outcomes.",
  ACCESS: "Access / role / permission changes stay with the Owner in the dashboard.",
};

/** The permanent contract of a Sunny mutation (proposal → preview → approval → execute → fresh read → outcome). */
export const ACTION_CONTRACT_FIELDS = [
  "ACTION_ID / TYPE", "TARGET", "CURRENT_STATE", "PROPOSED_STATE", "WHY", "RELATED_ENTITIES", "RELATED_DOMAINS", "SIDE_EFFECTS",
  "EXTERNAL_EFFECTS", "FINANCIAL_EFFECTS", "NOTIFICATION_EFFECTS", "RISK", "APPROVAL_REQUIREMENT", "EXECUTION_RESULT", "FRESH_STATE", "OUTCOME",
] as const;

export const ACTION_FLOW = ["UNDERSTAND", "PROPOSE", "PREVIEW EXACT CHANGE", "OWNER APPROVAL", "EXECUTE", "FRESH READ", "OUTCOME", "HISTORY"] as const;

export type Who = "OWNER" | "OWNER_OR_VICTOR" | "OWNER_OR_STEVEN" | "VICTOR" | "STEVEN" | "SYSTEM" | "CRON" | "NOBODY";
export type Enforcement = "ROUTE_CHECKS_OWNER" | "PROXY_ONLY" | "ROLE_SCOPED" | "CRON_ONLY" | "AUTOMATIC" | "NO_ROUTE";

export interface ProjectActionEntry {
  id: string;
  group: "FIELDS" | "LIFECYCLE" | "FINANCE" | "SESSIONS" | "PROPOSALS" | "TASKS_MEETINGS_LOG" | "VICTOR" | "ENGINEERS" | "FILES_DELIVERY" | "ALBUM" | "RED_FILMS" | "SOCIAL" | "SUNNY";
  action: string;
  who: Who;
  enforcement: Enforcement;
  input: string;
  sideEffects: string;
  push: string | null;
  calendar: string | null;
  finance: string | null;
  files: string | null;
  reversible: "YES" | "PARTIAL" | "NO";
  risk: "LOW" | "MEDIUM" | "HIGH";
  /** The future typed Sunny primitive (null = not a delegation candidate yet / automatic behavior). */
  futurePrimitive: string | null;
  approvalClass: ApprovalClass | null;
  /** What Sunny can do with it TODAY. */
  sunnyToday: "EXECUTE_AFTER_DASHBOARD_APPROVAL" | "KNOWLEDGE_ONLY";
  internal: { routes: readonly string[] };
}

type E = Omit<ProjectActionEntry, "sunnyToday" | "internal"> & { routes: readonly string[]; sunnyToday?: ProjectActionEntry["sunnyToday"] };
const X = (e: E): ProjectActionEntry => { const { routes, sunnyToday, ...rest } = e; return { ...rest, sunnyToday: sunnyToday ?? "KNOWLEDGE_ONLY", internal: { routes } }; };
const P = "app/api/projects/[id]/route.ts";

export const PROJECT_ACTIONS: readonly ProjectActionEntry[] = [
  // ── fields ──
  X({ id: "EDIT_NOTES", group: "FIELDS", action: "Edit project notes", who: "OWNER", enforcement: "PROXY_ONLY", input: "notes text", sideEffects: "updated time bumped", push: null, calendar: null, finance: null, files: null, reversible: "YES", risk: "LOW", futurePrimitive: "UPDATE_PROJECT_NOTES", approvalClass: "STANDARD", routes: [P] }),
  X({ id: "EDIT_START_DATE", group: "FIELDS", action: "Edit start date", who: "OWNER", enforcement: "PROXY_ONLY", input: "date or empty", sideEffects: "—", push: null, calendar: null, finance: null, files: null, reversible: "YES", risk: "LOW", futurePrimitive: "UPDATE_PROJECT_DATES", approvalClass: "STANDARD", routes: [P] }),
  X({ id: "EDIT_PLANNED", group: "FIELDS", action: "Edit planned hours / days (lessons)", who: "OWNER", enforcement: "PROXY_ONLY", input: "non-negative numbers (days whole)", sideEffects: "—", push: null, calendar: null, finance: null, files: null, reversible: "YES", risk: "LOW", futurePrimitive: "UPDATE_PROJECT_PLAN", approvalClass: "STANDARD", routes: [P] }),
  X({ id: "EDIT_PARENT", group: "FIELDS", action: "Set parent project (free-text name)", who: "OWNER", enforcement: "PROXY_ONLY", input: "parent name or ללא שיוך", sideEffects: "name link only, never checked", push: null, calendar: null, finance: null, files: null, reversible: "YES", risk: "LOW", futurePrimitive: "SET_PARENT_PROJECT", approvalClass: "STANDARD", routes: [P] }),
  X({ id: "EDIT_TYPE", group: "FIELDS", action: "Change project type", who: "OWNER", enforcement: "PROXY_ONLY", input: "type text (not validated)", sideEffects: "switches album center / riddim mode / whether Steven accepts it", push: null, calendar: null, finance: null, files: null, reversible: "YES", risk: "LOW", futurePrimitive: "UPDATE_PROJECT_TYPE", approvalClass: "STANDARD", routes: [P] }),
  X({ id: "EDIT_DEADLINE", group: "FIELDS", action: "Change deadline (UI)", who: "OWNER", enforcement: "PROXY_ONLY", input: "date or empty", sideEffects: "feeds overdue / due-soon cron pushes", push: "indirect (cron)", calendar: null, finance: null, files: null, reversible: "YES", risk: "LOW", futurePrimitive: "UPDATE_PROJECT_DEADLINE", approvalClass: "STANDARD", routes: [P] }),
  X({ id: "RENAME", group: "FIELDS", action: "Rename project", who: "OWNER", enforcement: "PROXY_ONLY", input: "name", sideEffects: "first rename freezes the Dropbox folder; calendar titles keep the old name; Victor folder uses the new name; children linked by parent name are orphaned; Red Films / social name snapshots go stale", push: null, calendar: "old event titles kept", finance: null, files: "folder freeze (no move)", reversible: "PARTIAL", risk: "MEDIUM", futurePrimitive: "RENAME_PROJECT", approvalClass: "STANDARD", routes: [P] }),
  X({ id: "CHANGE_ARTIST", group: "FIELDS", action: "Change project artist text", who: "OWNER", enforcement: "PROXY_ONLY", input: "artist text", sideEffects: "adds missing clients (never removes); changes client / label / portal matching and who gets Shalev pushes", push: "changes future recipients", calendar: null, finance: null, files: "unfrozen project: future uploads go to a new folder", reversible: "PARTIAL", risk: "MEDIUM", futurePrimitive: "CHANGE_PROJECT_ARTIST", approvalClass: "STANDARD", routes: [P] }),
  X({ id: "CLIENT_RENAME_REWRITES", group: "FIELDS", action: "Client rename rewrites every matching project's artist", who: "OWNER", enforcement: "PROXY_ONLY", input: "new client name", sideEffects: "one update per project, case-insensitive, not atomic", push: null, calendar: null, finance: null, files: "unfrozen folders move later", reversible: "PARTIAL", risk: "MEDIUM", futurePrimitive: "RENAME_CLIENT", approvalClass: "BULK", routes: ["app/api/clients/[id]/route.ts"] }),
  X({ id: "HIDE", group: "FIELDS", action: "Hide / unhide project (legacy drawer only)", who: "OWNER", enforcement: "PROXY_ONLY", input: "hidden flag", sideEffects: "drops out of most screens (not the Finance Brain)", push: null, calendar: null, finance: null, files: null, reversible: "YES", risk: "LOW", futurePrimitive: "SET_PROJECT_HIDDEN", approvalClass: "STANDARD", routes: [P] }),
  X({ id: "SET_COVER", group: "FIELDS", action: "Set / reset project cover", who: "OWNER", enforcement: "ROUTE_CHECKS_OWNER", input: "theme or image", sideEffects: "cover setting", push: null, calendar: null, finance: null, files: "image upload / delete", reversible: "YES", risk: "LOW", futurePrimitive: null, approvalClass: "STANDARD", routes: ["app/api/projects/[id]/cover/route.ts"] }),
  // ── lifecycle ──
  X({ id: "CREATE_PROJECT", group: "LIFECYCLE", action: "Create project", who: "OWNER", enforcement: "ROUTE_CHECKS_OWNER", input: "name, artist, status, deadline, type, parent", sideEffects: "start date = today; business type לקוח; missing clients added", push: null, calendar: null, finance: null, files: "no folder created", reversible: "YES", risk: "LOW", futurePrimitive: "CREATE_PROJECT", approvalClass: "STANDARD", routes: ["app/api/projects/route.ts"] }),
  X({ id: "CHANGE_STATUS", group: "LIFECYCLE", action: "Change status (server)", who: "OWNER", enforcement: "PROXY_ONLY", input: "any text (not validated)", sideEffects: "הושלם stamps end date; any other status clears it", push: null, calendar: null, finance: null, files: null, reversible: "PARTIAL", risk: "MEDIUM", futurePrimitive: "UPDATE_PROJECT_STATUS", approvalClass: "STANDARD", routes: [P] }),
  X({ id: "STATUS_COMPLETE_CLIENT_FLOW", group: "LIFECYCLE", action: "Status → הושלם (status menu)", who: "OWNER", enforcement: "PROXY_ONLY", input: "—", sideEffects: "opens delivery prompt; closes an active Victor work", push: "Victor + Owner 'completed'", calendar: null, finance: null, files: null, reversible: "PARTIAL", risk: "MEDIUM", futurePrimitive: "COMPLETE_PROJECT", approvalClass: "EXTERNAL_EFFECT", routes: ["app/api/vendor/victor/work/[id]/route.ts"] }),
  X({ id: "STATUS_CANCEL_BALANCE", group: "LIFECYCLE", action: "Status → בוטל + cancel open income", who: "OWNER", enforcement: "PROXY_ONLY", input: "cancel or keep", sideEffects: "open expected income → בוטל (the prompt adds currencies together)", push: null, calendar: null, finance: "income rows cancelled", files: null, reversible: "PARTIAL", risk: "MEDIUM", futurePrimitive: "CANCEL_PROJECT", approvalClass: "FINANCIAL", routes: ["app/api/transactions/[id]/route.ts"] }),
  X({ id: "STEVEN_COMPLETION", group: "LIFECYCLE", action: "Last Steven work approved → project הושלם", who: "SYSTEM", enforcement: "AUTOMATIC", input: "engineer work → אושר", sideEffects: "status הושלם + end date (race-guarded); final-files request marker; does NOT close Victor or open delivery", push: "Steven + Owner", calendar: null, finance: null, files: null, reversible: "PARTIAL", risk: "MEDIUM", futurePrimitive: null, approvalClass: null, routes: ["app/api/sound-engineer/[id]/route.ts"] }),
  X({ id: "SET_BUSINESS_TYPE", group: "LIFECYCLE", action: "Switch לקוח / לייבל (no UI caller)", who: "OWNER", enforcement: "ROUTE_CHECKS_OWNER", input: "business type", sideEffects: "release row stays dormant", push: null, calendar: null, finance: null, files: null, reversible: "YES", risk: "LOW", futurePrimitive: "SET_PROJECT_BUSINESS_TYPE", approvalClass: "STANDARD", routes: ["app/api/label/projects/[id]/business-type/route.ts"] }),
  X({ id: "CONVERT_TO_RELEASE", group: "LIFECYCLE", action: "Convert project to a label release", who: "OWNER", enforcement: "ROUTE_CHECKS_OWNER", input: "project, label artist, stage", sideEffects: "sets לייבל; may rewrite artist text; release row (manual undo)", push: null, calendar: null, finance: null, files: "portal visibility / cover", reversible: "PARTIAL", risk: "MEDIUM", futurePrimitive: "CONVERT_TO_LABEL_RELEASE", approvalClass: "STANDARD", routes: ["app/api/label/releases/route.ts"] }),
  X({ id: "CREATE_LABEL_SONG", group: "LIFECYCLE", action: "Create label song release (atomic)", who: "OWNER", enforcement: "ROUTE_CHECKS_OWNER", input: "artist, name, deadline, stage", sideEffects: "project + release together", push: null, calendar: null, finance: null, files: null, reversible: "YES", risk: "MEDIUM", futurePrimitive: "CREATE_LABEL_SONG", approvalClass: "STANDARD", routes: ["app/api/label/projects/route.ts"] }),
  X({ id: "UPDATE_RELEASE", group: "LIFECYCLE", action: "Release stage / target / next action / blocker", who: "OWNER", enforcement: "ROUTE_CHECKS_OWNER", input: "fields + optimistic version", sideEffects: "—", push: null, calendar: null, finance: null, files: null, reversible: "YES", risk: "LOW", futurePrimitive: "UPDATE_RELEASE", approvalClass: "STANDARD", routes: ["app/api/label/releases/[projectId]/route.ts"] }),
  X({ id: "BACKFILL_START_DATES", group: "LIFECYCLE", action: "Backfill start dates from sessions (no UI caller)", who: "OWNER", enforcement: "PROXY_ONLY", input: "—", sideEffects: "fills empty start dates", push: null, calendar: null, finance: null, files: null, reversible: "NO", risk: "MEDIUM", futurePrimitive: null, approvalClass: "BULK", routes: ["app/api/projects/backfill-start-dates/route.ts"] }),
  X({ id: "DELETE_PROJECT", group: "LIFECYCLE", action: "Delete project (not transactional)", who: "OWNER", enforcement: "PROXY_ONLY", input: "project", sideEffects: "app deletes sessions (+events), send log, clip rows, Victor work, finance / delivery / cover settings, proposal follow-ups; unlinks transactions; proposals back to לא נסגר; DB cascades release, album tracks, engineer work, alerts; leaves tasks, meetings, Red Films, social, notifications, album settings, Dropbox folders", push: null, calendar: "deletes session events", finance: "transactions unlinked, price setting deleted", files: "cover deleted; folders stay", reversible: "NO", risk: "HIGH", futurePrimitive: "DELETE_PROJECT", approvalClass: "DESTRUCTIVE", routes: [P] }),
  // ── finance ──
  X({ id: "SET_PRICE", group: "FINANCE", action: "Agreed price / currency / financial notes", who: "OWNER", enforcement: "ROUTE_CHECKS_OWNER", input: "fields merged into the finance setting", sideEffects: "—", push: null, calendar: null, finance: "price setting (no history)", files: null, reversible: "YES", risk: "MEDIUM", futurePrimitive: "SET_PROJECT_AGREED_PRICE", approvalClass: "FINANCIAL", routes: ["app/api/transactions/route.ts"] }),
  X({ id: "SET_FINANCE_EXCEPTION", group: "FINANCE", action: "Finance exception on / off", who: "OWNER", enforcement: "ROUTE_CHECKS_OWNER", input: "flag, reason, date", sideEffects: "project no longer shows as owing", push: null, calendar: null, finance: "no receivable", files: null, reversible: "YES", risk: "MEDIUM", futurePrimitive: "SET_FINANCE_EXCEPTION", approvalClass: "FINANCIAL", routes: ["app/api/transactions/route.ts"] }),
  X({ id: "SET_CLIP_PRICE", group: "FINANCE", action: "Clip price", who: "OWNER", enforcement: "ROUTE_CHECKS_OWNER", input: "clip price ≥0", sideEffects: "pushes the price into the managed Red Films budget", push: null, calendar: null, finance: "setting + production budget", files: null, reversible: "YES", risk: "MEDIUM", futurePrimitive: "SET_CLIP_PRICE", approvalClass: "FINANCIAL", routes: ["app/api/projects/[id]/clip/route.ts"] }),
  X({ id: "OPEN_CLIP_DEAL", group: "FINANCE", action: "Open clip deal (seed advance + balance)", who: "OWNER", enforcement: "ROUTE_CHECKS_OWNER", input: "price", sideEffects: "2 expected clip income rows; שיר → שיר + קליפ", push: null, calendar: null, finance: "+2 transactions", files: null, reversible: "PARTIAL", risk: "MEDIUM", futurePrimitive: "OPEN_CLIP_DEAL", approvalClass: "FINANCIAL", routes: ["app/api/projects/[id]/clip/payments/route.ts"] }),
  X({ id: "ADD_TRANSACTION", group: "FINANCE", action: "Add transaction to a project", who: "OWNER", enforcement: "ROUTE_CHECKS_OWNER", input: "type, amount, currency, status, date (no enum checks)", sideEffects: "project updated time bumped", push: null, calendar: null, finance: "insert", files: null, reversible: "YES", risk: "MEDIUM", futurePrimitive: "RECORD_PROJECT_TRANSACTION", approvalClass: "FINANCIAL", routes: ["app/api/transactions/route.ts"] }),
  X({ id: "EDIT_TRANSACTION", group: "FINANCE", action: "Edit transaction (can move it to another project)", who: "OWNER", enforcement: "PROXY_ONLY", input: "any field", sideEffects: "paid → linked clip rows שולם", push: null, calendar: null, finance: "update", files: null, reversible: "YES", risk: "MEDIUM", futurePrimitive: "RECORD_RECEIVED_INCOME", approvalClass: "FINANCIAL", routes: ["app/api/transactions/[id]/route.ts"] }),
  X({ id: "DELETE_TRANSACTION", group: "FINANCE", action: "Delete transaction", who: "OWNER", enforcement: "PROXY_ONLY", input: "id", sideEffects: "hard delete", push: null, calendar: null, finance: "delete", files: null, reversible: "NO", risk: "HIGH", futurePrimitive: "DELETE_TRANSACTION", approvalClass: "DESTRUCTIVE", routes: ["app/api/transactions/[id]/route.ts"] }),
  X({ id: "SPLIT_INCOME", group: "FINANCE", action: "Split expected income (atomic)", who: "OWNER", enforcement: "ROUTE_CHECKS_OWNER", input: "paid amount, date, method", sideEffects: "1 row → received + remainder", push: null, calendar: null, finance: "split", files: null, reversible: "PARTIAL", risk: "LOW", futurePrimitive: "RECORD_RECEIVED_INCOME", approvalClass: "FINANCIAL", routes: ["app/api/transactions/[id]/split/route.ts"] }),
  X({ id: "CLIP_ITEMS", group: "FINANCE", action: "Clip planning rows add / edit / delete", who: "OWNER", enforcement: "PROXY_ONLY", input: "category, amount, currency", sideEffects: "planning only", push: null, calendar: null, finance: "planning", files: null, reversible: "PARTIAL", risk: "LOW", futurePrimitive: "PLAN_CLIP_ITEM", approvalClass: "STANDARD", routes: ["app/api/clip-items/route.ts", "app/api/clip-items/[id]/route.ts"] }),
  X({ id: "PROMOTE_CLIP_ITEM", group: "FINANCE", action: "Promote clip row to an expense (not atomic)", who: "OWNER", enforcement: "PROXY_ONLY", input: "date", sideEffects: "unpaid clip expense created, row deleted", push: null, calendar: null, finance: "+expense", files: null, reversible: "NO", risk: "MEDIUM", futurePrimitive: "PROMOTE_CLIP_ITEM", approvalClass: "FINANCIAL", routes: ["app/api/clip-items/[id]/promote/route.ts"] }),
  X({ id: "ALBUM_SETTINGS", group: "FINANCE", action: "Album finance / previous-system info settings", who: "OWNER", enforcement: "PROXY_ONLY", input: "setting values", sideEffects: "isolated settings (album finance has no UI caller)", push: null, calendar: null, finance: "isolated", files: null, reversible: "YES", risk: "LOW", futurePrimitive: null, approvalClass: "STANDARD", routes: ["app/api/album-finance/route.ts", "app/api/album-prev-info/route.ts"] }),
  // ── sessions / calendar ──
  X({ id: "SESSION_LIMIT", group: "SESSIONS", action: "Session limit", who: "OWNER", enforcement: "PROXY_ONLY", input: "limit", sideEffects: "setting", push: null, calendar: null, finance: null, files: null, reversible: "YES", risk: "LOW", futurePrimitive: "SET_SESSION_LIMIT", approvalClass: "STANDARD", routes: ["app/api/sessions/route.ts"] }),
  X({ id: "ADD_SESSION", group: "SESSIONS", action: "Add session", who: "OWNER", enforcement: "ROUTE_CHECKS_OWNER", input: "project, date, times, status, type, add-to-calendar", sideEffects: "project touched; start date filled if empty; rehearsal finance synced", push: "Shalev + Owner for Shalev projects", calendar: "creates an event", finance: "rehearsal expense only", files: null, reversible: "YES", risk: "MEDIUM", futurePrimitive: "SCHEDULE_SESSION", approvalClass: "EXTERNAL_EFFECT", routes: ["app/api/sessions/route.ts"] }),
  X({ id: "CALENDAR_INVITE", group: "SESSIONS", action: "Create calendar event with artist invite", who: "OWNER", enforcement: "PROXY_ONLY", input: "summary, start, end, artist email", sideEffects: "then a session with the event id", push: null, calendar: "sends a Google invite", finance: null, files: null, reversible: "PARTIAL", risk: "MEDIUM", futurePrimitive: "SCHEDULE_SESSION", approvalClass: "EXTERNAL_EFFECT", routes: ["app/api/calendar/create-event/route.ts"] }),
  X({ id: "EDIT_SESSION", group: "SESSIONS", action: "Edit session / inline status", who: "OWNER", enforcement: "ROUTE_CHECKS_OWNER", input: "fields", sideEffects: "project touched; rehearsal finance synced", push: null, calendar: "updates the event", finance: "rehearsal only", files: null, reversible: "YES", risk: "LOW", futurePrimitive: "UPDATE_SESSION", approvalClass: "EXTERNAL_EFFECT", routes: ["app/api/sessions/[id]/route.ts"] }),
  X({ id: "DELETE_SESSION", group: "SESSIONS", action: "Delete session", who: "OWNER", enforcement: "ROUTE_CHECKS_OWNER", input: "id", sideEffects: "row then event deleted; rehearsal expense not removed", push: null, calendar: "deletes the event", finance: null, files: null, reversible: "NO", risk: "MEDIUM", futurePrimitive: "CANCEL_SESSION", approvalClass: "DESTRUCTIVE", routes: ["app/api/sessions/[id]/route.ts"] }),
  X({ id: "AUTO_MARK_HELD", group: "SESSIONS", action: "Auto-mark passed sessions held (every page load, device clock)", who: "SYSTEM", enforcement: "PROXY_ONLY", input: "client clock", sideEffects: "planned → התקיים", push: null, calendar: null, finance: null, files: null, reversible: "PARTIAL", risk: "MEDIUM", futurePrimitive: null, approvalClass: null, routes: ["app/api/sessions/auto-mark/route.ts"] }),
  X({ id: "CALENDAR_PULL", group: "SESSIONS", action: "Calendar pull (cron): copy moved event times; held → planned when the event is in the future", who: "CRON", enforcement: "CRON_ONLY", input: "—", sideEffects: "session date / time / status", push: null, calendar: "reads Google", finance: null, files: null, reversible: "PARTIAL", risk: "MEDIUM", futurePrimitive: null, approvalClass: null, routes: ["app/api/sessions/calendar-pull/route.ts"] }),
  // ── proposals ──
  X({ id: "CONVERT_PROPOSAL", group: "PROPOSALS", action: "Convert proposal to project (not transactional)", who: "OWNER", enforcement: "PROXY_ONLY", input: "optional name", sideEffects: "project created; client added; finance setting overwritten whole; proposal נסגר + linked; follow-up done", push: null, calendar: "Google Task done", finance: "agreed price set", files: null, reversible: "PARTIAL", risk: "MEDIUM", futurePrimitive: "CONVERT_PROPOSAL", approvalClass: "FINANCIAL", routes: ["app/api/proposals/[id]/convert/route.ts"] }),
  X({ id: "LINK_PROPOSAL", group: "PROPOSALS", action: "Link / relink proposal to a project (id not checked)", who: "OWNER", enforcement: "PROXY_ONLY", input: "project id", sideEffects: "follow-up task create / update / delete", push: null, calendar: "Google Tasks", finance: null, files: null, reversible: "YES", risk: "LOW", futurePrimitive: "LINK_PROPOSAL", approvalClass: "STANDARD", routes: ["app/api/proposals/[id]/route.ts"] }),
  // ── tasks / meetings / send log ──
  X({ id: "ADD_TASK", group: "TASKS_MEETINGS_LOG", action: "Add task on a project", who: "OWNER", enforcement: "PROXY_ONLY", input: "title, due", sideEffects: "UI then creates a Google Task", push: null, calendar: "Google Task", finance: null, files: null, reversible: "YES", risk: "LOW", futurePrimitive: "CREATE_TASK", approvalClass: "EXTERNAL_EFFECT", routes: ["app/api/tasks/route.ts"] }),
  X({ id: "EDIT_TASK", group: "TASKS_MEETINGS_LOG", action: "Complete / edit / delete task", who: "OWNER", enforcement: "PROXY_ONLY", input: "status / fields", sideEffects: "mirrored to Google Tasks", push: null, calendar: "Google Tasks", finance: null, files: null, reversible: "PARTIAL", risk: "LOW", futurePrimitive: "COMPLETE_TASK", approvalClass: "EXTERNAL_EFFECT", routes: ["app/api/tasks/[id]/route.ts"] }),
  X({ id: "ADD_MEETING", group: "TASKS_MEETINGS_LOG", action: "Add meeting", who: "OWNER", enforcement: "PROXY_ONLY", input: "client, project, date", sideEffects: "optional Google event", push: null, calendar: "event", finance: null, files: null, reversible: "YES", risk: "LOW", futurePrimitive: "SCHEDULE_MEETING", approvalClass: "EXTERNAL_EFFECT", routes: ["app/api/meetings/route.ts"] }),
  X({ id: "EDIT_MEETING", group: "TASKS_MEETINGS_LOG", action: "Edit / delete meeting (event left orphaned)", who: "OWNER", enforcement: "PROXY_ONLY", input: "fields", sideEffects: "Google event not updated / deleted", push: null, calendar: "orphan event", finance: null, files: null, reversible: "PARTIAL", risk: "LOW", futurePrimitive: "UPDATE_MEETING", approvalClass: "STANDARD", routes: ["app/api/meetings/[id]/route.ts"] }),
  X({ id: "SEND_LOG_ADD", group: "TASKS_MEETINGS_LOG", action: "Add / update send-log entry (who waits for whom)", who: "OWNER", enforcement: "PROXY_ONLY", input: "type, recipient, status, follow-up", sideEffects: "—", push: null, calendar: null, finance: null, files: null, reversible: "YES", risk: "LOW", futurePrimitive: "LOG_PROJECT_SEND", approvalClass: "STANDARD", routes: ["app/api/project-actions/route.ts", "app/api/project-actions/[id]/route.ts"] }),
  X({ id: "SEND_LOG_DELETE", group: "TASKS_MEETINGS_LOG", action: "Delete send-log entry (browser cascades into engineer / Victor work)", who: "OWNER", enforcement: "PROXY_ONLY", input: "id", sideEffects: "engineer send → deletes the engineer work (expense kept); Victor send → deletes Victor task + work", push: null, calendar: "Google Task deleted", finance: "orphan expense possible", files: null, reversible: "NO", risk: "HIGH", futurePrimitive: null, approvalClass: "DESTRUCTIVE", routes: ["app/api/project-actions/[id]/route.ts"] }),
  // ── Victor ──
  X({ id: "SEND_TO_VICTOR", group: "VICTOR", action: "Send to Victor (work + follow-up task + send log)", who: "OWNER", enforcement: "ROUTE_CHECKS_OWNER", input: "title, deadline", sideEffects: "creates / reuses the Victor work; deadline → task", push: null, calendar: "Google Task", finance: null, files: null, reversible: "PARTIAL", risk: "LOW", futurePrimitive: "SEND_TO_VICTOR", approvalClass: "EXTERNAL_EFFECT", routes: ["app/api/vendor/victor/work/route.ts"] }),
  X({ id: "NOTIFY_VICTOR", group: "VICTOR", action: "Push new work / version notes to Victor", who: "OWNER", enforcement: "ROUTE_CHECKS_OWNER", input: "work / version", sideEffects: "saves sent notes", push: "Victor + Owner", calendar: null, finance: null, files: null, reversible: "NO", risk: "LOW", futurePrimitive: "NOTIFY_VICTOR", approvalClass: "EXTERNAL_EFFECT", routes: ["app/api/vendor/victor/notify-work/route.ts", "app/api/vendor/victor/notify-version-notes/route.ts"] }),
  X({ id: "EDIT_VICTOR_WORK", group: "VICTOR", action: "Edit Victor work (Owner all; Victor file fields only)", who: "OWNER_OR_VICTOR", enforcement: "ROLE_SCOPED", input: "fields / reviews / outcome", sideEffects: "הושלם → push; deadline → task", push: "Victor + Owner on הושלם", calendar: "Google Task", finance: null, files: "Victor can set any Dropbox path (security gap)", reversible: "YES", risk: "MEDIUM", futurePrimitive: "UPDATE_VICTOR_WORK", approvalClass: "STANDARD", routes: ["app/api/vendor/victor/work/[id]/route.ts"] }),
  X({ id: "VICTOR_FILES", group: "VICTOR", action: "Victor uploads / folder create / file delete / brief", who: "OWNER_OR_VICTOR", enforcement: "ROLE_SCOPED", input: "file / names", sideEffects: "files list on the work", push: "Owner when Victor uploads (batched)", calendar: null, finance: null, files: "Dropbox upload / delete; public links", reversible: "PARTIAL", risk: "MEDIUM", futurePrimitive: null, approvalClass: "EXTERNAL_EFFECT", routes: ["app/api/dropbox/vendor-upload/route.ts", "app/api/dropbox/vendor-upload/chunk/route.ts", "app/api/dropbox/vendor-folder/route.ts", "app/api/vendor/victor/work/[id]/file/route.ts", "app/api/vendor/victor/work/[id]/brief/route.ts", "app/api/vendor/victor/production-link/route.ts"] }),
  X({ id: "DELETE_VICTOR_WORK", group: "VICTOR", action: "Delete Victor work (task + folder stay)", who: "OWNER", enforcement: "ROUTE_CHECKS_OWNER", input: "id", sideEffects: "row only", push: null, calendar: null, finance: null, files: null, reversible: "NO", risk: "MEDIUM", futurePrimitive: null, approvalClass: "DESTRUCTIVE", routes: ["app/api/vendor/victor/work/[id]/route.ts"] }),
  // ── engineers ──
  X({ id: "SEND_TO_ENGINEER", group: "ENGINEERS", action: "Send to Steven / Bill / other engineer", who: "OWNER", enforcement: "ROUTE_CHECKS_OWNER", input: "engineer, title", sideEffects: "Steven accepts only some types; $200 + 3-day deadline default; no expense; send log; status → במיקס (Steven)", push: null, calendar: null, finance: "none at send", files: null, reversible: "PARTIAL", risk: "MEDIUM", futurePrimitive: "SEND_TO_ENGINEER", approvalClass: "STANDARD", routes: ["app/api/sound-engineer/route.ts"] }),
  X({ id: "EDIT_ENGINEER_WORK", group: "ENGINEERS", action: "Edit engineer work (status / price / paid)", who: "OWNER", enforcement: "PROXY_ONLY", input: "fields", sideEffects: "price re-syncs expense; אושר → completion flow", push: "payment-sent push (fires for any engineer — known gap)", calendar: null, finance: "expense insert / update", files: null, reversible: "PARTIAL", risk: "HIGH", futurePrimitive: "UPDATE_ENGINEER_WORK", approvalClass: "FINANCIAL", routes: ["app/api/sound-engineer/[id]/route.ts", "app/api/sound-engineer/[id]/payment-expense/route.ts"] }),
  X({ id: "DELETE_ENGINEER_WORK", group: "ENGINEERS", action: "Delete engineer work (expense left behind)", who: "OWNER", enforcement: "PROXY_ONLY", input: "id", sideEffects: "orphan expense", push: null, calendar: null, finance: "orphan expense", files: null, reversible: "NO", risk: "MEDIUM", futurePrimitive: null, approvalClass: "DESTRUCTIVE", routes: ["app/api/sound-engineer/[id]/route.ts"] }),
  X({ id: "ENGINEER_NOTIFY", group: "ENGINEERS", action: "Mix-ready / mix-notes push", who: "OWNER", enforcement: "ROUTE_CHECKS_OWNER", input: "work", sideEffects: "—", push: "Owner + Steven", calendar: null, finance: null, files: null, reversible: "NO", risk: "LOW", futurePrimitive: "NOTIFY_ENGINEER", approvalClass: "EXTERNAL_EFFECT", routes: ["app/api/sound-engineer/[id]/notify-mix-ready/route.ts", "app/api/sound-engineer/[id]/notify-notes/route.ts"] }),
  X({ id: "MIX_VERSION_UPLOAD", group: "ENGINEERS", action: "Upload mix version (full mix copied into the project player)", who: "OWNER_OR_STEVEN", enforcement: "ROLE_SCOPED", input: "file, label", sideEffects: "version row; first Steven upload → בתהליך", push: "Owner (batched, Steven)", calendar: null, finance: null, files: "Dropbox upload + copy + public link", reversible: "PARTIAL", risk: "MEDIUM", futurePrimitive: null, approvalClass: "EXTERNAL_EFFECT", routes: ["app/api/sound-engineer/[id]/versions/route.ts", "app/api/sound-engineer/[id]/versions/chunk/route.ts", "app/api/supplier/steven/work/[id]/versions/route.ts", "app/api/supplier/steven/work/[id]/versions/chunk/route.ts"] }),
  X({ id: "MIX_VERSION_EDIT", group: "ENGINEERS", action: "Edit / delete mix version (project copy stays)", who: "OWNER", enforcement: "ROUTE_CHECKS_OWNER", input: "status / label", sideEffects: "—", push: null, calendar: null, finance: null, files: "Dropbox delete", reversible: "NO", risk: "MEDIUM", futurePrimitive: null, approvalClass: "DESTRUCTIVE", routes: ["app/api/sound-engineer/versions/[versionId]/route.ts"] }),
  X({ id: "MIX_COMMENTS", group: "ENGINEERS", action: "Add / resolve / delete mix comment (+ attachments)", who: "OWNER_OR_STEVEN", enforcement: "ROLE_SCOPED", input: "text, timecode / status", sideEffects: "Steven may only resolve", push: null, calendar: null, finance: null, files: "attachment upload / delete", reversible: "PARTIAL", risk: "LOW", futurePrimitive: "ADD_MIX_NOTE", approvalClass: "STANDARD", routes: ["app/api/sound-engineer/versions/[versionId]/comments/route.ts", "app/api/sound-engineer/comments/[commentId]/route.ts", "app/api/supplier/steven/comments/[commentId]/route.ts", "app/api/sound-engineer/comments/[commentId]/attachments/route.ts"] }),
  X({ id: "RIDDIM_TARGETS", group: "ENGINEERS", action: "Riddim mix lines + their notes", who: "OWNER", enforcement: "ROUTE_CHECKS_OWNER", input: "lines / notes", sideEffects: "soft removal", push: null, calendar: null, finance: null, files: null, reversible: "YES", risk: "LOW", futurePrimitive: null, approvalClass: "STANDARD", routes: ["app/api/sound-engineer/[id]/targets/route.ts", "app/api/sound-engineer/[id]/targets/[targetId]/route.ts"] }),
  X({ id: "WORK_MATERIALS", group: "ENGINEERS", action: "Work materials (files + BPM / key / instructions)", who: "OWNER", enforcement: "ROUTE_CHECKS_OWNER", input: "file / fields", sideEffects: "project files (חומרי עבודה) + work materials merged", push: null, calendar: null, finance: null, files: "Dropbox upload / delete", reversible: "PARTIAL", risk: "MEDIUM", futurePrimitive: "UPDATE_WORK_MATERIALS", approvalClass: "STANDARD", routes: ["app/api/sound-engineer/[id]/work-materials/route.ts", "app/api/sound-engineer/[id]/work-materials/chunk/route.ts"] }),
  X({ id: "FINAL_FILES", group: "ENGINEERS", action: "Final files upload (no delete route)", who: "OWNER_OR_STEVEN", enforcement: "ROLE_SCOPED", input: "file, batch", sideEffects: "final file rows", push: "Owner per batch", calendar: null, finance: null, files: "Dropbox", reversible: "NO", risk: "MEDIUM", futurePrimitive: null, approvalClass: "EXTERNAL_EFFECT", routes: ["app/api/sound-engineer/[id]/final-files/route.ts", "app/api/sound-engineer/[id]/final-files/chunk/route.ts", "app/api/supplier/steven/work/[id]/final-files/route.ts", "app/api/supplier/steven/work/[id]/final-files/chunk/route.ts"] }),
  X({ id: "REORDER_ENGINEER_WORKS", group: "ENGINEERS", action: "Reorder engineer works", who: "OWNER", enforcement: "ROUTE_CHECKS_OWNER", input: "ids", sideEffects: "—", push: null, calendar: null, finance: null, files: null, reversible: "YES", risk: "LOW", futurePrimitive: null, approvalClass: "STANDARD", routes: ["app/api/sound-engineer/reorder/route.ts"] }),
  // ── files / delivery ──
  X({ id: "UPLOAD_PROJECT_FILE", group: "FILES_DELIVERY", action: "Upload project file (no lock)", who: "OWNER", enforcement: "PROXY_ONLY", input: "file, name, subfolder, track, version", sideEffects: "appended to the project's files list", push: null, calendar: null, finance: null, files: "Dropbox upload + public link", reversible: "YES", risk: "MEDIUM", futurePrimitive: null, approvalClass: "EXTERNAL_EFFECT", routes: ["app/api/dropbox/upload/route.ts"] }),
  X({ id: "LINK_TO_PORTAL", group: "FILES_DELIVERY", action: "Push a project file to an artist portal", who: "OWNER", enforcement: "ROUTE_CHECKS_OWNER", input: "project, path, sketch", sideEffects: "reference in the artist's music", push: "artist + Owner", calendar: null, finance: null, files: "reference only", reversible: "PARTIAL", risk: "MEDIUM", futurePrimitive: "SHARE_TO_ARTIST_PORTAL", approvalClass: "EXTERNAL_EFFECT", routes: ["app/api/label/artists/[id]/sketches/project-link/route.ts", "app/api/label/artists/[id]/sketches/[sketchId]/notify/route.ts"] }),
  X({ id: "DELETE_PROJECT_FILE", group: "FILES_DELIVERY", action: "Delete project file / folder (path never checked against the project)", who: "OWNER", enforcement: "PROXY_ONLY", input: "path, project", sideEffects: "portal reference removed; path and everything under it removed from the files list", push: null, calendar: null, finance: null, files: "Dropbox delete (any path)", reversible: "NO", risk: "HIGH", futurePrimitive: null, approvalClass: "DESTRUCTIVE", routes: ["app/api/dropbox/delete/route.ts"] }),
  X({ id: "INTAKE", group: "FILES_DELIVERY", action: "Intake: move files into Delivery / delete empty source", who: "OWNER", enforcement: "PROXY_ONLY", input: "project + items", sideEffects: "Delivery folders created; files added", push: null, calendar: null, finance: null, files: "move + delete", reversible: "PARTIAL", risk: "HIGH", futurePrimitive: null, approvalClass: "DESTRUCTIVE", routes: ["app/api/dropbox/intake/route.ts"] }),
  X({ id: "DELIVERY", group: "FILES_DELIVERY", action: "Delivery folder / status / upload (legacy drawer)", who: "OWNER", enforcement: "PROXY_ONLY", input: "project / status keys", sideEffects: "delivery setting", push: null, calendar: null, finance: null, files: "folder + public link", reversible: "YES", risk: "LOW", futurePrimitive: "MARK_DELIVERED", approvalClass: "EXTERNAL_EFFECT", routes: ["app/api/delivery/route.ts", "app/api/delivery/upload/route.ts"] }),
  X({ id: "DELETE_DELIVERY", group: "FILES_DELIVERY", action: "Delete the whole Delivery folder (file list keeps dead links)", who: "OWNER", enforcement: "PROXY_ONLY", input: "project", sideEffects: "setting reset", push: null, calendar: null, finance: null, files: "folder delete", reversible: "NO", risk: "HIGH", futurePrimitive: null, approvalClass: "DESTRUCTIVE", routes: ["app/api/delivery/route.ts"] }),
  X({ id: "REFRESH_LINK", group: "FILES_DELIVERY", action: "Refresh share link / track length", who: "OWNER", enforcement: "PROXY_ONLY", input: "path", sideEffects: "—", push: null, calendar: null, finance: null, files: "public link", reversible: "YES", risk: "LOW", futurePrimitive: null, approvalClass: "EXTERNAL_EFFECT", routes: ["app/api/dropbox/share-link/route.ts", "app/api/red-artists/track-duration/route.ts"] }),
  X({ id: "FILE_RENAME_MOVE", group: "FILES_DELIVERY", action: "Rename / reorder project files, move folder", who: "NOBODY", enforcement: "NO_ROUTE", input: "—", sideEffects: "does not exist in Redbloods", push: null, calendar: null, finance: null, files: null, reversible: "YES", risk: "LOW", futurePrimitive: null, approvalClass: null, routes: [] }),
  // ── album / Red Films / social ──
  X({ id: "ALBUM_TRACKS", group: "ALBUM", action: "Album tracks add / edit / delete / reorder", who: "OWNER", enforcement: "PROXY_ONLY", input: "title, number, statuses", sideEffects: "reorder not atomic", push: null, calendar: null, finance: null, files: null, reversible: "PARTIAL", risk: "LOW", futurePrimitive: "UPDATE_ALBUM_TRACK", approvalClass: "STANDARD", routes: ["app/api/album-tracks/route.ts", "app/api/album-tracks/[id]/route.ts", "app/api/album-tracks/reorder/route.ts"] }),
  X({ id: "CLIP_TO_RED_FILMS", group: "RED_FILMS", action: "Send clip to Red Films (managed production)", who: "OWNER", enforcement: "ROUTE_CHECKS_OWNER", input: "—", sideEffects: "production (רעיון, budget = clip price, client by exact name)", push: null, calendar: null, finance: "budget", files: null, reversible: "PARTIAL", risk: "MEDIUM", futurePrimitive: "START_CLIP_PRODUCTION", approvalClass: "FINANCIAL", routes: ["app/api/projects/[id]/clip/send/route.ts"] }),
  X({ id: "RED_FILMS_PRODUCTION", group: "RED_FILMS", action: "Create / edit production (link, budget, crew names, status)", who: "OWNER", enforcement: "PROXY_ONLY", input: "fields", sideEffects: "בוטל cancels future tasks", push: null, calendar: "Google Tasks", finance: "budget", files: null, reversible: "PARTIAL", risk: "MEDIUM", futurePrimitive: "UPDATE_PRODUCTION", approvalClass: "STANDARD", routes: ["app/api/red-films/productions/route.ts", "app/api/red-films/productions/[id]/route.ts"] }),
  X({ id: "RED_FILMS_DELETE", group: "RED_FILMS", action: "Permanently delete cancelled productions", who: "OWNER", enforcement: "PROXY_ONLY", input: "ids", sideEffects: "references, budget items, tasks, production", push: null, calendar: "Google Tasks deleted", finance: null, files: "Dropbox delete", reversible: "NO", risk: "HIGH", futurePrimitive: null, approvalClass: "BULK", routes: ["app/api/red-films/productions/bulk-permanent-delete/route.ts"] }),
  X({ id: "SOCIAL", group: "SOCIAL", action: "Social campaign / content / uploads", who: "OWNER", enforcement: "PROXY_ONLY", input: "fields / files", sideEffects: "uploads live outside the project folder", push: null, calendar: null, finance: null, files: "Dropbox upload / delete", reversible: "PARTIAL", risk: "LOW", futurePrimitive: "UPDATE_SOCIAL_CAMPAIGN", approvalClass: "STANDARD", routes: ["app/api/social/campaigns/route.ts", "app/api/social/campaigns/[id]/route.ts", "app/api/social/content/route.ts", "app/api/social/content/[id]/route.ts", "app/api/social/upload/route.ts"] }),
  // ── Sunny ──
  X({ id: "SUNNY_DEADLINE", group: "SUNNY", action: "Sunny deadline action: decide + execute (atomic, staleness-checked, audited)", who: "OWNER", enforcement: "ROUTE_CHECKS_OWNER", input: "approval event", sideEffects: "changes the deadline + decision / outcome events", push: null, calendar: null, finance: null, files: null, reversible: "YES", risk: "MEDIUM", futurePrimitive: "UPDATE_PROJECT_DEADLINE", approvalClass: "STANDARD", sunnyToday: "EXECUTE_AFTER_DASHBOARD_APPROVAL", routes: ["app/api/partner/actions/decide/route.ts", "app/api/partner/actions/execute/route.ts", "app/api/partner/actions/change-deadline/route.ts"] }),
];

/** Mutating routes that touch project-linked data but are covered elsewhere or are not project actions (with the reason). */
export const PROJECT_ACTION_EXCLUSIONS: Readonly<Record<string, string>> = {
  "app/api/push/check/route.ts": "legacy push check — reads projects to decide a push, never changes project data (covered by the Push contracts)",
  "app/api/vendor/victor/salary/route.ts": "Victor salary months (finance domain) — not a project mutation",
};
