/**
 * SUNNY UNIVERSAL ACTION LAYER — which registered primitives carry out each census operation.
 *
 * full: true  → the operation's whole business outcome is executable through these primitives (→ EXECUTABLE).
 * full: false → part of it is executable; `remaining` names what is still being built.
 * Every primitive id must exist (G7). This map + the registry are the mechanical 100% proof.
 */
export interface CoverageEntry { by: readonly string[]; full: boolean; remaining?: string }

export const COVERAGE_MAP: Readonly<Record<string, CoverageEntry>> = {
  // ── Wave 1 ──
  "PROJECT.EDIT_NOTES": { by: ["UPDATE_PROJECT_NOTES"], full: true },
  "PROJECT.EDIT_START_DATE": { by: ["UPDATE_PROJECT_PLANNING"], full: true },
  "PROJECT.EDIT_PLANNED": { by: ["UPDATE_PROJECT_PLANNING"], full: true },
  "PROJECT.EDIT_TYPE": { by: ["UPDATE_PROJECT_TYPE_OR_PARENT"], full: true },
  "PROJECT.EDIT_PARENT": { by: ["UPDATE_PROJECT_TYPE_OR_PARENT"], full: true },
  "PROJECT.UPDATE_RELEASE": { by: ["UPDATE_RELEASE_DETAILS", "CHANGE_RELEASE_STAGE"], full: true },
  "LABEL.UPDATE_RELEASE": { by: ["UPDATE_RELEASE_DETAILS", "CHANGE_RELEASE_STAGE"], full: true },
  "MIX.RESOLVE_COMMENT": { by: ["RESOLVE_MIX_COMMENT", "REOPEN_MIX_COMMENT"], full: true },
  "PROJECT.SUNNY_DEADLINE": { by: ["UPDATE_PROJECT_DEADLINE"], full: true },
  "LABEL.UPDATE_LABEL_ARTIST": { by: ["UPDATE_LABEL_ARTIST_NOTES_STATUS"], full: false, remaining: "name / image" },
  "VICTOR.CHANGE_STATUS": { by: ["UPDATE_VICTOR_WORK_STATE", "UPDATE_VICTOR_OUTCOME"], full: false, remaining: "status → הושלם with its completion push" },
  "MIX.EDIT_OR_DELETE_VERSION": { by: ["UPDATE_MIX_VERSION_STATUS_OR_LABEL"], full: false, remaining: "file delete" },
  "PROJECT.EDIT_DEADLINE": { by: ["UPDATE_PROJECT_DEADLINE"], full: false, remaining: "the UI path's communication side" },
  "VICTOR.EDIT_BRIEF": { by: ["UPDATE_VICTOR_NOTES"], full: false, remaining: "title / brief text / brief files / references" },
  // ── Projects family ──
  "PROJECT.CHANGE_STATUS": { by: ["UPDATE_PROJECT_STATUS"], full: true },
  "PROJECT.HIDE": { by: ["SET_PROJECT_HIDDEN"], full: true },
  "PROJECT.RENAME": { by: ["RENAME_PROJECT"], full: true },
  "PROJECT.CHANGE_ARTIST": { by: ["CHANGE_PROJECT_ARTIST"], full: true },
  "PROJECT.SET_BUSINESS_TYPE": { by: ["SET_PROJECT_BUSINESS_TYPE"], full: true },
  "LABEL.SET_PROJECT_BUSINESS_TYPE": { by: ["SET_PROJECT_BUSINESS_TYPE"], full: true },
  "PROJECT.SET_COVER": { by: ["SET_PROJECT_COVER_THEME", "RESET_PROJECT_COVER"], full: false, remaining: "a custom cover IMAGE needs file bytes (see the file-bytes decision)" },
  "PROJECT.SESSION_LIMIT": { by: ["SET_SESSION_LIMIT"], full: true },
  "PROJECT.CREATE_PROJECT": { by: ["CREATE_PROJECT"], full: true },
  "CLIENT.NEW_PROJECT_FROM_CLIENT": { by: ["CREATE_PROJECT"], full: true },
  "PROJECT.CREATE_LABEL_SONG": { by: ["CREATE_LABEL_SONG"], full: true },
  "LABEL.CREATE_LABEL_SONG": { by: ["CREATE_LABEL_SONG"], full: true },
  "PROJECT.CONVERT_TO_RELEASE": { by: ["CONVERT_TO_LABEL_RELEASE"], full: true },
  "LABEL.CONVERT_TO_LABEL_RELEASE": { by: ["CONVERT_TO_LABEL_RELEASE"], full: true },
  // ── Clients / proposals / meetings / tasks / calendar family ──
  "CLIENT.CREATE_CLIENT": { by: ["CREATE_CLIENT"], full: true },
  "CLIENT.UPDATE_CLIENT": { by: ["UPDATE_CLIENT_CONTACT", "RENAME_CLIENT"], full: true },
  "PROJECT.CLIENT_RENAME_REWRITES": { by: ["RENAME_CLIENT"], full: true },
  "CLIENT.DELETE_CLIENT": { by: ["DELETE_CLIENT"], full: true },
  "CLIENT.CREATE_PROPOSAL": { by: ["CREATE_PROPOSAL"], full: true },
  "CLIENT.UPDATE_PROPOSAL": { by: ["UPDATE_PROPOSAL_INFO", "UPDATE_PROPOSAL_AMOUNT", "CHANGE_PROPOSAL_STATUS", "SET_PROPOSAL_FOLLOWUP"], full: true },
  "CLIENT.MARK_PROPOSAL_LOST": { by: ["CHANGE_PROPOSAL_STATUS"], full: true },
  "CLIENT.DELETE_PROPOSAL": { by: ["DELETE_PROPOSAL"], full: true },
  "CLIENT.CONVERT_PROPOSAL": { by: ["CONVERT_PROPOSAL"], full: true },
  "PROJECT.CONVERT_PROPOSAL": { by: ["CONVERT_PROPOSAL"], full: true },
  "PROJECT.LINK_PROPOSAL": { by: ["LINK_PROPOSAL_TO_PROJECT"], full: true },
  "CLIENT.CREATE_MEETING": { by: ["CREATE_MEETING"], full: true },
  "PROJECT.ADD_MEETING": { by: ["CREATE_MEETING"], full: true },
  "CLIENT.MEETING_HELD_OR_CANCELLED": { by: ["UPDATE_MEETING", "DELETE_MEETING"], full: true },
  "PROJECT.EDIT_MEETING": { by: ["UPDATE_MEETING", "DELETE_MEETING"], full: true },
  "CLIENT.CLIENT_TASK": { by: ["CREATE_TASK", "UPDATE_TASK", "SET_TASK_STATUS", "DELETE_TASK"], full: true },
  "PROJECT.ADD_TASK": { by: ["CREATE_TASK"], full: true },
  "PROJECT.EDIT_TASK": { by: ["UPDATE_TASK", "SET_TASK_STATUS", "DELETE_TASK"], full: true },
  "CALENDAR.CREATE_EVENT": { by: ["CREATE_CALENDAR_EVENT", "CREATE_CALENDAR_INVITE"], full: true },
  "CALENDAR.UPDATE_OR_DELETE_EVENT": { by: ["UPDATE_CALENDAR_EVENT", "DELETE_CALENDAR_EVENT"], full: true },
  "CALENDAR.CREATE_GOOGLE_TASK": { by: ["CREATE_GOOGLE_TASK"], full: true },
  "CALENDAR.DELETE_GOOGLE_TASK": { by: ["DELETE_GOOGLE_TASK", "DELETE_TASK"], full: true },
  "CALENDAR.SYNC_COMPLETED_TASKS": { by: ["SYNC_GOOGLE_TASKS_NOW"], full: true },
  "CALENDAR.DISCONNECT": { by: ["DISCONNECT_GOOGLE_CALENDAR"], full: true },
  // ── Sessions family ──
  "PROJECT.ADD_SESSION": { by: ["SCHEDULE_SESSION", "SCHEDULE_SESSION_WITH_INVITE"], full: false, remaining: "the optional expected-payment row staged with the booking (Finance family)" },
  "PROJECT.CALENDAR_INVITE": { by: ["SCHEDULE_SESSION_WITH_INVITE"], full: true },
  "PROJECT.EDIT_SESSION": { by: ["UPDATE_SESSION"], full: false, remaining: "show-rehearsal cost / payment edits (Shows family, D6 vocabulary unchanged)" },
  "PROJECT.DELETE_SESSION": { by: ["DELETE_SESSION"], full: false, remaining: "deleting a show rehearsal (Shows family: split re-sync)" },
  "CLIENT.SESSION_FROM_CLIENT": { by: ["SCHEDULE_SESSION"], full: false, remaining: "the optional payment row with artist = client name (Finance family)" },
  "LABEL.ARTIST_SESSION": { by: ["SCHEDULE_SESSION"], full: false, remaining: "booking a show rehearsal (Shows family)" },
};

/** Which Sunny system domain (lib/partner/system DOMAIN_CONTRACTS id) each registered primitive belongs to. Every
 *  primitive must be listed (G10) — the domain's execute support is then PARTIAL, never a hand-kept claim. */
export const PRIMITIVE_SYSTEM_DOMAIN: Readonly<Record<string, string>> = {
  UPDATE_PROJECT_NOTES: "PROJECTS",
  UPDATE_PROJECT_PLANNING: "PROJECTS",
  UPDATE_PROJECT_TYPE_OR_PARENT: "PROJECTS",
  UPDATE_PROJECT_DEADLINE: "PROJECTS",
  UPDATE_PROJECT_STATUS: "PROJECTS",
  SET_PROJECT_HIDDEN: "PROJECTS",
  RENAME_PROJECT: "PROJECTS",
  CHANGE_PROJECT_ARTIST: "PROJECTS",
  SET_PROJECT_BUSINESS_TYPE: "PROJECTS",
  SET_PROJECT_COVER_THEME: "PROJECTS",
  RESET_PROJECT_COVER: "PROJECTS",
  SET_SESSION_LIMIT: "PROJECTS",
  CREATE_PROJECT: "PROJECTS",
  UPDATE_RELEASE_DETAILS: "RELEASES",
  CHANGE_RELEASE_STAGE: "RELEASES",
  CREATE_LABEL_SONG: "RELEASES",
  CONVERT_TO_LABEL_RELEASE: "RELEASES",
  RESOLVE_MIX_COMMENT: "MIX_PIPELINE",
  REOPEN_MIX_COMMENT: "MIX_PIPELINE",
  UPDATE_MIX_VERSION_STATUS_OR_LABEL: "MIX_PIPELINE",
  UPDATE_LABEL_ARTIST_NOTES_STATUS: "LABEL_ARTISTS",
  UPDATE_VICTOR_WORK_STATE: "VICTOR",
  UPDATE_VICTOR_OUTCOME: "VICTOR",
  UPDATE_VICTOR_NOTES: "VICTOR",
  CREATE_CLIENT: "CLIENTS",
  UPDATE_CLIENT_CONTACT: "CLIENTS",
  RENAME_CLIENT: "CLIENTS",
  DELETE_CLIENT: "CLIENTS",
  CREATE_PROPOSAL: "PROPOSALS",
  UPDATE_PROPOSAL_INFO: "PROPOSALS",
  UPDATE_PROPOSAL_AMOUNT: "PROPOSALS",
  CHANGE_PROPOSAL_STATUS: "PROPOSALS",
  SET_PROPOSAL_FOLLOWUP: "PROPOSALS",
  LINK_PROPOSAL_TO_PROJECT: "PROPOSALS",
  CONVERT_PROPOSAL: "PROPOSALS",
  DELETE_PROPOSAL: "PROPOSALS",
  CREATE_MEETING: "MEETINGS",
  UPDATE_MEETING: "MEETINGS",
  DELETE_MEETING: "MEETINGS",
  CREATE_TASK: "TASKS",
  UPDATE_TASK: "TASKS",
  SET_TASK_STATUS: "TASKS",
  DELETE_TASK: "TASKS",
  SYNC_GOOGLE_TASKS_NOW: "TASKS",
  CREATE_CALENDAR_EVENT: "GOOGLE_CALENDAR",
  CREATE_CALENDAR_INVITE: "GOOGLE_CALENDAR",
  UPDATE_CALENDAR_EVENT: "GOOGLE_CALENDAR",
  DELETE_CALENDAR_EVENT: "GOOGLE_CALENDAR",
  CREATE_GOOGLE_TASK: "GOOGLE_CALENDAR",
  DELETE_GOOGLE_TASK: "GOOGLE_CALENDAR",
  DISCONNECT_GOOGLE_CALENDAR: "GOOGLE_CALENDAR",
  SCHEDULE_SESSION: "SESSIONS",
  SCHEDULE_SESSION_WITH_INVITE: "SESSIONS",
  UPDATE_SESSION: "SESSIONS",
  DELETE_SESSION: "SESSIONS",
};

/** The business-action taxonomy (lib/partner/system BUSINESS_ACTIONS) → the primitives that execute it through
 *  Claude. sunnyCanExecuteToday must equal "has an entry here" (G10). */
export const BUSINESS_ACTION_PRIMITIVES: Readonly<Record<string, readonly string[]>> = {
  UPDATE_PROJECT_DEADLINE: ["UPDATE_PROJECT_DEADLINE"],
  CREATE_PROJECT: ["CREATE_PROJECT", "CREATE_LABEL_SONG"],
  UPDATE_PROJECT_STATUS: ["UPDATE_PROJECT_STATUS"],
  CONVERT_PROPOSAL: ["CONVERT_PROPOSAL"],
  CREATE_PROPOSAL: ["CREATE_PROPOSAL"],
  CREATE_SESSION: ["SCHEDULE_SESSION"],
  CALENDAR_WRITE: ["CREATE_CALENDAR_EVENT", "UPDATE_CALENDAR_EVENT", "DELETE_CALENDAR_EVENT"],
  CREATE_CALENDAR_EVENT: ["CREATE_CALENDAR_EVENT", "CREATE_CALENDAR_INVITE"],
  UPDATE_CALENDAR_EVENT: ["UPDATE_CALENDAR_EVENT"],
  DELETE_CALENDAR_EVENT: ["DELETE_CALENDAR_EVENT"],
  SCHEDULE_SESSION: ["SCHEDULE_SESSION", "SCHEDULE_SESSION_WITH_INVITE"],
  SCHEDULE_MEETING: ["CREATE_MEETING"],
  RESCHEDULE_EVENT: ["UPDATE_SESSION", "UPDATE_MEETING", "UPDATE_CALENDAR_EVENT"],
  CREATE_TASK: ["CREATE_TASK"],
  RELEASE_STAGE: ["CHANGE_RELEASE_STAGE"],
};
