/**
 * GENERATED by scripts/gen-act-handler-map.mjs — do not edit by hand. Every API route file with a write handler (or a
 * GET that writes), its LF-normalized SHA-256 and the side effects found by the transitive scan. Internal (never served).
 */
export interface HandlerEntry { methods: readonly string[]; getWrites: boolean; sha256: string; effects: readonly string[]; fields: readonly string[] }
export const HANDLER_MAP: Readonly<Record<string, HandlerEntry>> = {
 "app/api/agent/alerts/[id]/route.ts": {
  "methods": [
   "PATCH"
  ],
  "getWrites": false,
  "sha256": "d2422fbd7f207e1905211c59e012f7d195b135d4157ac9389e1065a003a0bd11",
  "effects": [
   "DELETION",
   "EMAIL",
   "SETTINGS"
  ],
  "fields": [
   "status"
  ]
 },
 "app/api/agent/alerts/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "94f745a3fa31ee1cb1b95177ec50013be69e23841e1a00a5bf4ac868726a2394",
  "effects": [],
  "fields": [
   "message",
   "metadata",
   "relatedClientId",
   "relatedProjectId",
   "severity",
   "suggestedActions",
   "title",
   "type"
  ]
 },
 "app/api/agent/check/route.ts": {
  "methods": [],
  "getWrites": true,
  "sha256": "4062865deed954c0a8823e6267e9f1c970ec51b2761b58e801c1c13ec02b0974",
  "effects": [
   "DELETION",
   "PUSH",
   "SETTINGS"
  ],
  "fields": [
   "updated_at"
  ]
 },
 "app/api/agent/goals/route.ts": {
  "methods": [
   "PATCH"
  ],
  "getWrites": false,
  "sha256": "fab16b6c74dea558fa7ad405ce893408d70aef92922d4198d5ef25952cd9cd59",
  "effects": [
   "DELETION",
   "EMAIL",
   "SETTINGS"
  ],
  "fields": []
 },
 "app/api/album-finance/route.ts": {
  "methods": [
   "PATCH"
  ],
  "getWrites": false,
  "sha256": "2362808216e7409e6ce12a8710ff14f08aafeddfb67edcbb3e19b1fc84d60496",
  "effects": [
   "DELETION",
   "EXTERNAL_LINK",
   "FILES",
   "FINANCE",
   "GOOGLE_TASKS",
   "PUSH",
   "SETTINGS"
  ],
  "fields": []
 },
 "app/api/album-prev-info/route.ts": {
  "methods": [
   "PATCH"
  ],
  "getWrites": false,
  "sha256": "790afd7199afceac14f7beaf08f841586193b24d6dba0e708ce48dfdddeb9d4a",
  "effects": [
   "DELETION",
   "EXTERNAL_LINK",
   "FILES",
   "FINANCE",
   "GOOGLE_TASKS",
   "PUSH",
   "SETTINGS"
  ],
  "fields": [
   "actionDate",
   "actionType",
   "action_date",
   "action_type",
   "agreed",
   "contentType",
   "content_type",
   "currency",
   "dropboxUrl",
   "dropbox_url",
   "followupDate",
   "followup_date",
   "linkedTaskId",
   "linkedWorkId",
   "linked_task_id",
   "linked_work_id",
   "master_status",
   "mix_status",
   "note",
   "notes",
   "projectId",
   "project_id",
   "recipientClientId",
   "recipientName",
   "recipientPhone",
   "recipientRole",
   "recipient_name",
   "recipient_phone",
   "recipient_role",
   "rows",
   "status",
   "title",
   "track_number",
   "versionLabel",
   "version_label"
  ]
 },
 "app/api/album-tracks/[id]/route.ts": {
  "methods": [
   "DELETE",
   "PATCH"
  ],
  "getWrites": false,
  "sha256": "c2a4025b34f06afbf84679fd59903a957dc86ca3e413b456011c27dd6b2d5664",
  "effects": [
   "DELETION",
   "EXTERNAL_LINK",
   "FILES",
   "FINANCE",
   "GOOGLE_TASKS",
   "PUSH",
   "SETTINGS"
  ],
  "fields": [
   "actionDate",
   "actionType",
   "action_date",
   "action_type",
   "agreed",
   "contentType",
   "content_type",
   "currency",
   "dropboxUrl",
   "dropbox_url",
   "followupDate",
   "followup_date",
   "linkedTaskId",
   "linkedWorkId",
   "linked_task_id",
   "linked_work_id",
   "master_status",
   "mix_status",
   "note",
   "notes",
   "projectId",
   "project_id",
   "recipientClientId",
   "recipientName",
   "recipientPhone",
   "recipientRole",
   "recipient_name",
   "recipient_phone",
   "recipient_role",
   "rows",
   "status",
   "title",
   "track_number",
   "versionLabel",
   "version_label"
  ]
 },
 "app/api/album-tracks/reorder/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "1dda54d2f591b8d6097dcea95fb28dca6587945107f97a0de4cd402e281b0727",
  "effects": [
   "DELETION",
   "EXTERNAL_LINK",
   "FILES",
   "FINANCE",
   "GOOGLE_TASKS",
   "PUSH",
   "SETTINGS"
  ],
  "fields": [
   "actionDate",
   "actionType",
   "action_date",
   "action_type",
   "agreed",
   "contentType",
   "content_type",
   "currency",
   "dropboxUrl",
   "dropbox_url",
   "followupDate",
   "followup_date",
   "linkedTaskId",
   "linkedWorkId",
   "linked_task_id",
   "linked_work_id",
   "master_status",
   "mix_status",
   "note",
   "notes",
   "projectId",
   "project_id",
   "recipientClientId",
   "recipientName",
   "recipientPhone",
   "recipientRole",
   "recipient_name",
   "recipient_phone",
   "recipient_role",
   "rows",
   "status",
   "title",
   "track_number",
   "tracks",
   "versionLabel",
   "version_label"
  ]
 },
 "app/api/album-tracks/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "52133168460d025c0b64856ccc4ffd0578b0978477ba88c6286124496725f653",
  "effects": [
   "DELETION",
   "EXTERNAL_LINK",
   "FILES",
   "FINANCE",
   "GOOGLE_TASKS",
   "PUSH",
   "SETTINGS"
  ],
  "fields": [
   "actionDate",
   "actionType",
   "action_date",
   "action_type",
   "agreed",
   "contentType",
   "content_type",
   "currency",
   "dropboxUrl",
   "dropbox_url",
   "followupDate",
   "followup_date",
   "linkedTaskId",
   "linkedWorkId",
   "linked_task_id",
   "linked_work_id",
   "master_status",
   "mix_status",
   "note",
   "notes",
   "projectId",
   "project_id",
   "recipientClientId",
   "recipientName",
   "recipientPhone",
   "recipientRole",
   "recipient_name",
   "recipient_phone",
   "recipient_role",
   "rows",
   "status",
   "title",
   "track_number",
   "versionLabel",
   "version_label"
  ]
 },
 "app/api/beats/[id]/assignments/route.ts": {
  "methods": [
   "DELETE",
   "POST"
  ],
  "getWrites": false,
  "sha256": "4f87a5afb8cd87cebec56848c2dd954b395be0600d20016ad117bd72329e18a8",
  "effects": [
   "DELETION",
   "LEDGER",
   "PUSH",
   "SETTINGS"
  ],
  "fields": [
   "artistSlug"
  ]
 },
 "app/api/beats/[id]/route.ts": {
  "methods": [
   "DELETE",
   "PATCH"
  ],
  "getWrites": false,
  "sha256": "56dfeae0db843c45624120e0e0bdf2f124ed0f417e4137ae48f1d3a7991dcd26",
  "effects": [
   "DELETION",
   "EXTERNAL_LINK",
   "FILES",
   "PUSH",
   "SETTINGS"
  ],
  "fields": []
 },
 "app/api/beats/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "8cdcaf293b49488d365dce3646e476b0397342376acc8813cc306625ff0fc699",
  "effects": [
   "DELETION",
   "EXTERNAL_LINK",
   "FILES",
   "PUSH",
   "SETTINGS"
  ],
  "fields": [
   "createdAt",
   "durationSeconds",
   "genre",
   "id",
   "musicalKey",
   "name"
  ]
 },
 "app/api/calendar/callback/route.ts": {
  "methods": [],
  "getWrites": true,
  "sha256": "a22f2dec31e241fd9272a740754839aad92c429bcc3125fccd990361d568dc94",
  "effects": [
   "CALENDAR"
  ],
  "fields": []
 },
 "app/api/calendar/check-slot/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "22363187dd27936ca27e8fc2c608b43434a79b2e4d4b4aaa733f730a3b1a1b5e",
  "effects": [],
  "fields": []
 },
 "app/api/calendar/create-event/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "3161bb993cc1644601d85e70c4d6e36a3c10f5d7dea4a463681d0d1c21606f71",
  "effects": [
   "CALENDAR"
  ],
  "fields": []
 },
 "app/api/calendar/create-task/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "0659066bef28f56262a9300a7ff431ed34f7281771d34b85b934e6eb9e73358f",
  "effects": [
   "GOOGLE_TASKS"
  ],
  "fields": []
 },
 "app/api/calendar/events/[id]/route.ts": {
  "methods": [
   "DELETE",
   "PATCH"
  ],
  "getWrites": false,
  "sha256": "c1d1b427cab29b8e1498b7524f8d730f2746e36ded009c60f753d03fe583362b",
  "effects": [
   "CALENDAR"
  ],
  "fields": []
 },
 "app/api/calendar/status/route.ts": {
  "methods": [
   "DELETE"
  ],
  "getWrites": false,
  "sha256": "337af2da6ff4f5f7c401539c842332cd1f5d4208e054fcea114eaf19a62987bc",
  "effects": [
   "CALENDAR"
  ],
  "fields": []
 },
 "app/api/calendar/tasks/[id]/route.ts": {
  "methods": [
   "DELETE"
  ],
  "getWrites": false,
  "sha256": "ef389f24953b63a439b1df4c2e7842e8d9a756e6b511118461d35dcf047a8752",
  "effects": [
   "GOOGLE_TASKS"
  ],
  "fields": []
 },
 "app/api/calendar/tasks/sync/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "327a252b91863aac0daf95d97cdcbe00b22f07967f20a3932fb2ba33d97a71f9",
  "effects": [
   "DELETION",
   "GOOGLE_TASKS"
  ],
  "fields": [
   "due_date",
   "notes",
   "status",
   "title"
  ]
 },
 "app/api/clients/[id]/route.ts": {
  "methods": [
   "DELETE",
   "PATCH"
  ],
  "getWrites": false,
  "sha256": "f6930caba4e09a8eb60fed3e512da0818942f08a812e4346c135ea6c8922aa2e",
  "effects": [
   "DELETION",
   "GOOGLE_TASKS",
   "SETTINGS"
  ],
  "fields": [
   "email",
   "name",
   "notes",
   "phone",
   "status",
   "type"
  ]
 },
 "app/api/clients/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "51ed5a95bbd0d54c84cc3a47bfd1a89d716628e99c6b6fad81cb599bd7fc4e5d",
  "effects": [
   "DELETION",
   "GOOGLE_TASKS",
   "SETTINGS"
  ],
  "fields": [
   "email",
   "name",
   "notes",
   "phone",
   "status",
   "type"
  ]
 },
 "app/api/clip-items/[id]/promote/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "d2a6dbdcee397491afb7d1b82244a94c8754a3b7243703a75c08ddab64e89218",
  "effects": [
   "DELETION",
   "EXTERNAL_LINK",
   "FILES",
   "FINANCE",
   "GOOGLE_TASKS",
   "LEDGER",
   "SETTINGS"
  ],
  "fields": [
   "acquired_date",
   "actual_amount",
   "added_by",
   "amount",
   "artist_name",
   "category",
   "client_id",
   "client_name",
   "client_source",
   "currency",
   "date",
   "description",
   "name",
   "notes",
   "photographer_name",
   "planned_amount",
   "production_type",
   "projectId",
   "project_id",
   "provider",
   "purchase_price",
   "purchased_from",
   "quantity",
   "removed_at",
   "serial_number",
   "status",
   "thumbnail_url",
   "title",
   "updated_at",
   "url",
   "vendor_name",
   "video_id"
  ]
 },
 "app/api/clip-items/[id]/route.ts": {
  "methods": [
   "DELETE",
   "PATCH"
  ],
  "getWrites": false,
  "sha256": "d31ca649d1ced7a5a346963da1330e29cdc953560bcba7825b7b271aa0c54f17",
  "effects": [
   "DELETION",
   "EXTERNAL_LINK",
   "FILES",
   "FINANCE",
   "GOOGLE_TASKS",
   "LEDGER",
   "SETTINGS"
  ],
  "fields": [
   "acquired_date",
   "actual_amount",
   "added_by",
   "amount",
   "artist_name",
   "category",
   "client_id",
   "client_name",
   "client_source",
   "currency",
   "description",
   "name",
   "notes",
   "photographer_name",
   "planned_amount",
   "production_type",
   "projectId",
   "project_id",
   "provider",
   "purchase_price",
   "purchased_from",
   "quantity",
   "removed_at",
   "serial_number",
   "status",
   "thumbnail_url",
   "title",
   "updated_at",
   "url",
   "vendor_name",
   "video_id"
  ]
 },
 "app/api/clip-items/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "c40439dae22f8b175b85c3a35ecbdf3188633a05c225ded96b428c0f0cae6f89",
  "effects": [
   "DELETION",
   "EXTERNAL_LINK",
   "FILES",
   "FINANCE",
   "GOOGLE_TASKS",
   "LEDGER",
   "SETTINGS"
  ],
  "fields": [
   "acquired_date",
   "actual_amount",
   "added_by",
   "amount",
   "artist_name",
   "category",
   "client_id",
   "client_name",
   "client_source",
   "currency",
   "description",
   "name",
   "notes",
   "photographer_name",
   "planned_amount",
   "production_type",
   "projectId",
   "project_id",
   "provider",
   "purchase_price",
   "purchased_from",
   "quantity",
   "removed_at",
   "serial_number",
   "status",
   "thumbnail_url",
   "title",
   "updated_at",
   "url",
   "vendor_name",
   "video_id"
  ]
 },
 "app/api/delivery/route.ts": {
  "methods": [
   "DELETE",
   "PATCH",
   "POST"
  ],
  "getWrites": false,
  "sha256": "60989529fcb46fbe7ea7f6f94a9b4b1948c51fe8594aa29c112df1aab9b2616e",
  "effects": [
   "DELETION",
   "EXTERNAL_LINK",
   "FILES",
   "SETTINGS"
  ],
  "fields": [
   "deliveredAt",
   "deliveryStatus",
   "projectId",
   "updates"
  ]
 },
 "app/api/delivery/upload/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "948b061dec8d9c35212580ddd504f9e38b9cd946d7a068b3a01abd978e7c9750",
  "effects": [
   "DELETION",
   "EXTERNAL_LINK",
   "FILES",
   "FINANCE",
   "LEDGER",
   "PUSH",
   "SETTINGS"
  ],
  "fields": []
 },
 "app/api/dropbox/delete/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "64472e53bc277b0fb5898a74504d2b3efc9ced879cc91eca1466f5bd6cf6f029",
  "effects": [
   "DELETION",
   "FILES",
   "SETTINGS"
  ],
  "fields": []
 },
 "app/api/dropbox/folder-link/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "e87b6fbf50caaed8bd1e774427fcf2694c5a0889d08d33d1b4cb931d4fd544ae",
  "effects": [
   "EXTERNAL_LINK"
  ],
  "fields": [
   "error",
   "error_summary"
  ]
 },
 "app/api/dropbox/intake/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "919e0b6870962251d2d39e2c5a0c15d9f35bb520f3d3dcb82c9cd984d216b0d6",
  "effects": [
   "DELETION"
  ],
  "fields": [
   "action",
   "items",
   "projectId",
   "projectName",
   "sourcePath",
   "url"
  ]
 },
 "app/api/dropbox/share-link/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "ccc5da8a7abe2ce6432918d634a383a314450bc8cd203ea31da0c10f73c1062d",
  "effects": [
   "DELETION",
   "EXTERNAL_LINK"
  ],
  "fields": []
 },
 "app/api/dropbox/status/route.ts": {
  "methods": [
   "DELETE"
  ],
  "getWrites": false,
  "sha256": "ba316bb15b22f65bfc0e8b279764fa55edd6291e538ccd23e1d6e4b7023f2c6f",
  "effects": [
   "DELETION",
   "EMAIL",
   "SETTINGS"
  ],
  "fields": []
 },
 "app/api/dropbox/upload/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "c594a553c9288d3d22a28a9839f20101a6c9777cad43a71cdbad6ae3ff60dad2",
  "effects": [
   "DELETION",
   "EXTERNAL_LINK",
   "FILES",
   "FINANCE",
   "LEDGER",
   "PUSH",
   "SETTINGS"
  ],
  "fields": []
 },
 "app/api/dropbox/vendor-delete/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "a16477a56bb354de45ba6d72a4d1a197ecaa4a03095049533519133b75a0e947",
  "effects": [
   "DELETION",
   "FILES"
  ],
  "fields": []
 },
 "app/api/dropbox/vendor-folder/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "0220bc4b0b0171c5f13594b6bd3be812636a2deff0e275bcbe74461d8b101973",
  "effects": [
   "DELETION",
   "EXTERNAL_LINK",
   "FILES",
   "FINANCE",
   "GOOGLE_TASKS",
   "PUSH",
   "SETTINGS"
  ],
  "fields": [
   "artistName",
   "projectName",
   "useProjectsLayout",
   "vendorName"
  ]
 },
 "app/api/dropbox/vendor-upload/chunk/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "1b47767b820f9fc32a763d9151e124e04c23a71ec46fe2bce03c8159ac76f474",
  "effects": [
   "DELETION",
   "FILES",
   "PUSH",
   "SETTINGS"
  ],
  "fields": []
 },
 "app/api/dropbox/vendor-upload/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "9e7b1f7b39b9e22f46b62c8d5ddb1fc8032c2ebdda48a0730f0c3c00aa239226",
  "effects": [
   "DELETION",
   "EXTERNAL_LINK",
   "FILES",
   "FINANCE",
   "LEDGER",
   "PUSH",
   "SETTINGS"
  ],
  "fields": []
 },
 "app/api/label/artists/[id]/availability/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "bb28e6e488224d5b96e85028d882cb7507bce6f09db8106285e8efb513608dd0",
  "effects": [
   "PUSH",
   "SETTINGS"
  ],
  "fields": []
 },
 "app/api/label/artists/[id]/balance/[entryId]/route.ts": {
  "methods": [
   "DELETE",
   "PATCH"
  ],
  "getWrites": false,
  "sha256": "7094c71630094adaa0b530ddf0e18a5d390fa0f70524af6404f1117de3717a9f",
  "effects": [
   "DELETION",
   "FINANCE",
   "LEDGER"
  ],
  "fields": [
   "amount",
   "created_at",
   "description",
   "entryDate",
   "entryType",
   "id",
   "note"
  ]
 },
 "app/api/label/artists/[id]/balance/cycles/close/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "3cea3350edb7b8717c7fb3b97466f4550789ccd847f15d4579e6b49cbce8942e",
  "effects": [
   "DELETION",
   "LEDGER",
   "SETTINGS"
  ],
  "fields": [
   "force"
  ]
 },
 "app/api/label/artists/[id]/balance/cycles/remind/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "69ada29555c0c1f0419ce08671f0757cb34093bc28c72c110b9e1abe3c06e004",
  "effects": [
   "DELETION",
   "LEDGER",
   "PUSH",
   "SETTINGS"
  ],
  "fields": [
   "toArtist",
   "toOwner"
  ]
 },
 "app/api/label/artists/[id]/balance/cycles/route.ts": {
  "methods": [
   "PATCH",
   "POST"
  ],
  "getWrites": false,
  "sha256": "515703422d9f6cbe387ed2f9139b56a3c40c41f440dc498c46664aac33559d4e",
  "effects": [
   "DELETION",
   "LEDGER",
   "SETTINGS"
  ],
  "fields": [
   "anchorDate"
  ]
 },
 "app/api/label/artists/[id]/balance/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "3de9832bbb075e11620026f3a9fdd44b9118d7aa390306c66577a7cff151d5be",
  "effects": [
   "DELETION",
   "FINANCE",
   "LEDGER"
  ],
  "fields": [
   "allowDuplicate",
   "amount",
   "created_at",
   "description",
   "entryDate",
   "entryType",
   "id",
   "idempotencyKey",
   "method",
   "note"
  ]
 },
 "app/api/label/artists/[id]/media/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "dc81d630aaee31207c019b8dd36cc0e2ee8b5437ff565c9e0b71c3e9afbf754d",
  "effects": [
   "DELETION"
  ],
  "fields": [
   "creditedArtistIds",
   "financeTransactionId",
   "grossAmount",
   "incomeKind",
   "notes",
   "receivedDate",
   "reportPeriod",
   "requestKey",
   "source",
   "status"
  ]
 },
 "app/api/label/artists/[id]/next-work/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "3bf50e0bd952b1a2574d4c90abbfffd6f26b65de43c2d74287bb0b3bd40903c6",
  "effects": [
   "FILES"
  ],
  "fields": [
   "deadline",
   "sketchId"
  ]
 },
 "app/api/label/artists/[id]/ping/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "70a0aac7217b171e669ba0e065d3f0b35617284287f597677c9da4ba60fa48f0",
  "effects": [
   "PUSH",
   "SETTINGS"
  ],
  "fields": []
 },
 "app/api/label/artists/[id]/press-kit-link/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "1681361f3a7ca6975948616f9bdddf6e22ae70325cf7a92d049a26b14dc23932",
  "effects": [
   "EXTERNAL_LINK",
   "FILES"
  ],
  "fields": []
 },
 "app/api/label/artists/[id]/profile-image/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "a964c06745347dfd679d2c1678109b2e666b8604a46bc876b6b83b025fd8f9f0",
  "effects": [
   "EXTERNAL_LINK",
   "FILES"
  ],
  "fields": []
 },
 "app/api/label/artists/[id]/push-subscribe/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "511c900af7806f925b5ab9c2dbbc9dda14d1a6670783d508a29c0813773b13a1",
  "effects": [],
  "fields": []
 },
 "app/api/label/artists/[id]/route.ts": {
  "methods": [
   "PATCH"
  ],
  "getWrites": false,
  "sha256": "b9e92a82d736f493c1d5a2dae8fd122b64c00f58b70e2e35247d326c3db96156",
  "effects": [
   "DELETION",
   "FILES",
   "SETTINGS"
  ],
  "fields": [
   "imageUrl",
   "name",
   "notes",
   "status"
  ]
 },
 "app/api/label/artists/[id]/sketches/[sketchId]/beat/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "dfb7c97e2111472efb36c5d6a2861e48c54f3b19aaf962de87b0bcf6e995b5f9",
  "effects": [
   "FILES"
  ],
  "fields": []
 },
 "app/api/label/artists/[id]/sketches/[sketchId]/duration/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "d4d02964d5a166750c089f5b1bb7c00336bb18474fcdc7a8eff368e7f3690749",
  "effects": [
   "FILES"
  ],
  "fields": [
   "durationSeconds",
   "versionNumber"
  ]
 },
 "app/api/label/artists/[id]/sketches/[sketchId]/notify/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "03b0a6b09c93ffc2663ecbb12ac7f6229e23bb072d85704a509b54256083ded8",
  "effects": [
   "DELETION",
   "FILES",
   "LEDGER",
   "PUSH",
   "SETTINGS"
  ],
  "fields": []
 },
 "app/api/label/artists/[id]/sketches/[sketchId]/rating/route.ts": {
  "methods": [
   "PATCH"
  ],
  "getWrites": false,
  "sha256": "398348035b07b39e7320e0df45c2f8782ddaa92e1b9c9e2d5feec1b1444d3841",
  "effects": [
   "FILES"
  ],
  "fields": []
 },
 "app/api/label/artists/[id]/sketches/[sketchId]/route.ts": {
  "methods": [
   "DELETE",
   "PATCH"
  ],
  "getWrites": false,
  "sha256": "e4be7e2d4e7650c2b750aeb9412f2774d1fb8065215839c547d0af8410d0d189",
  "effects": [
   "FILES"
  ],
  "fields": [
   "description",
   "notes",
   "title"
  ]
 },
 "app/api/label/artists/[id]/sketches/[sketchId]/version/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "002db096d869a7eba8f9f6884950667d56573d54278a37afe43ac30099e9cd35",
  "effects": [
   "FILES"
  ],
  "fields": []
 },
 "app/api/label/artists/[id]/sketches/project-link/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "c8a556e4e99388e49c80ef881817b2648b3622963a8b1e0db63c5056a1a0e5f4",
  "effects": [
   "DELETION",
   "FILES",
   "SETTINGS"
  ],
  "fields": [
   "dropboxPath",
   "newTitle",
   "projectId",
   "sketchId"
  ]
 },
 "app/api/label/artists/[id]/sketches/reorder/route.ts": {
  "methods": [
   "PATCH"
  ],
  "getWrites": false,
  "sha256": "3da8da12bfa2c732c092d7db3db417e3ebe551ccf5e821943c849048188f47b9",
  "effects": [
   "FILES"
  ],
  "fields": []
 },
 "app/api/label/artists/[id]/sketches/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "c3e0018de9b30045e688fd46fdf1f77ed3d5bb6146ed7965f26175b0fa657317",
  "effects": [
   "FILES"
  ],
  "fields": []
 },
 "app/api/label/artists/[id]/upload/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "28a9a81f2279f3faa7d9e9b49abd52dc089e26248b65a3b06b4cefdbafdc469d",
  "effects": [
   "EXTERNAL_LINK",
   "FILES"
  ],
  "fields": []
 },
 "app/api/label/artists/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "db4c0a3b1168b9d20150f2db25c2f6c5b417b214dac8fbea37afd6c93ef35b8d",
  "effects": [],
  "fields": [
   "imageUrl",
   "name",
   "notes",
   "status"
  ]
 },
 "app/api/label/media/[recordId]/cancel/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "f75ca10f2832e3ca21f1a5cfc9b69a9e3901c56e8dfa82e108224ea1593c3a26",
  "effects": [
   "DELETION"
  ],
  "fields": [
   "artistId",
   "expectedUpdatedAt"
  ]
 },
 "app/api/label/media/[recordId]/route.ts": {
  "methods": [
   "PATCH"
  ],
  "getWrites": false,
  "sha256": "d39b3fbc4a5a4d22a4891c02f863ffac20e0b38463b4652edad3230485187ff2",
  "effects": [
   "DELETION"
  ],
  "fields": [
   "artistId",
   "clearReceivedDate",
   "creditedArtistIds",
   "expectedUpdatedAt",
   "grossAmount",
   "incomeKind",
   "notes",
   "receivedDate",
   "reportPeriod",
   "source",
   "status"
  ]
 },
 "app/api/label/projects/[id]/business-type/route.ts": {
  "methods": [
   "PATCH"
  ],
  "getWrites": false,
  "sha256": "2d1c3d376165584bc830da36b9d539470be67da6540a770e33a2be039c1bb3a5",
  "effects": [
   "DELETION",
   "FILES",
   "SETTINGS"
  ],
  "fields": [
   "businessType"
  ]
 },
 "app/api/label/projects/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "1bc925861438a8ba9d6fb68904351be6c79f97463de699d286bdeaaf225f0d55",
  "effects": [
   "DELETION",
   "FILES",
   "SETTINGS"
  ],
  "fields": [
   "blocker",
   "deadline",
   "labelArtistId",
   "name",
   "nextAction",
   "notes",
   "parentProject",
   "releaseStage",
   "releaseTargetDate",
   "responsible"
  ]
 },
 "app/api/label/releases/[projectId]/route.ts": {
  "methods": [
   "PATCH"
  ],
  "getWrites": false,
  "sha256": "f08874537b37c30f2697b445a33b46c33781c277b8ac5a41b740a34ce0b8b934",
  "effects": [
   "DELETION",
   "FILES",
   "SETTINGS"
  ],
  "fields": [
   "blocker",
   "expectedUpdatedAt",
   "nextAction",
   "releaseStage",
   "releaseTargetDate",
   "responsible"
  ]
 },
 "app/api/label/releases/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "c52fddd96bbd01d0de2fefb5eab5e0f84d0f7a4e65ad6cfc4f1dd1250fcc1b9f",
  "effects": [
   "DELETION",
   "FILES",
   "SETTINGS"
  ],
  "fields": [
   "blocker",
   "labelArtistId",
   "nextAction",
   "projectId",
   "releaseStage",
   "releaseTargetDate",
   "responsible"
  ]
 },
 "app/api/maintenance/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "65d15ee1f874f4cd3bf1f2ec8bbe867722346d53608d90d6a82b71632a1a2a76",
  "effects": [
   "DELETION",
   "EMAIL",
   "SETTINGS"
  ],
  "fields": []
 },
 "app/api/mcp-oauth/authorize/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "ede8ce74f39c74efcec6dc379447ba7737082826ba77a73d66bb392e0b9f4181",
  "effects": [
   "DELETION",
   "FILES",
   "PUSH",
   "SETTINGS"
  ],
  "fields": []
 },
 "app/api/mcp-oauth/register/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "5f66e9df26772b5cd925708287a2e15becb265c87057877b9dd88d35987e0989",
  "effects": [
   "DELETION",
   "FILES",
   "PUSH",
   "SETTINGS"
  ],
  "fields": []
 },
 "app/api/mcp-oauth/revoke/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "2e289e7d0c47e5bc4ae3a801bea64e1d32c7df6330d596dc6d9e39c8fe0d8563",
  "effects": [
   "DELETION",
   "FILES",
   "PUSH",
   "SETTINGS"
  ],
  "fields": []
 },
 "app/api/mcp-oauth/token/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "1b7c7d9c9df14b4d4318df16be999d3ff54b006087cd727cc820dfb55925734c",
  "effects": [
   "DELETION",
   "FILES",
   "PUSH",
   "SETTINGS"
  ],
  "fields": []
 },
 "app/api/mcp/route.ts": {
  "methods": [
   "DELETE",
   "PATCH",
   "POST",
   "PUT"
  ],
  "getWrites": false,
  "sha256": "14dbc19ba88e6832f04547899a3c5b8887ec5dac13b54ddd762dfb048e8a4b07",
  "effects": [
   "DELETION",
   "FILES",
   "PUSH",
   "SETTINGS"
  ],
  "fields": []
 },
 "app/api/meetings/[id]/route.ts": {
  "methods": [
   "DELETE",
   "PATCH"
  ],
  "getWrites": false,
  "sha256": "1d7f11ae5a0e15c10ea809eec0957a663d9afe49e3d5c83da55c76b664251b03",
  "effects": [
   "CALENDAR",
   "DELETION"
  ],
  "fields": [
   "addToCalendar",
   "clientId",
   "clientName",
   "date",
   "duration",
   "location",
   "notes",
   "projectId",
   "time"
  ]
 },
 "app/api/meetings/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "36f8855c8e0418f4516624a4841e23db27f19194099d65a89a9dc5eb51a3b5dd",
  "effects": [
   "CALENDAR",
   "DELETION"
  ],
  "fields": [
   "addToCalendar",
   "clientId",
   "clientName",
   "date",
   "duration",
   "location",
   "notes",
   "projectId",
   "time"
  ]
 },
 "app/api/notifications/[id]/route.ts": {
  "methods": [
   "PATCH"
  ],
  "getWrites": false,
  "sha256": "c3561811cc53714f11fc670b57fbb339e3d8fa14a0adce95a000260759aff79f",
  "effects": [],
  "fields": []
 },
 "app/api/notifications/read-all/route.ts": {
  "methods": [
   "PATCH"
  ],
  "getWrites": false,
  "sha256": "12ce956b0b624f4371e71273ec449865af551e1b767f05ad02ad0761e8941d79",
  "effects": [],
  "fields": []
 },
 "app/api/partner/actions/change-deadline/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "24c31101dc373433cd9d429d27de7a74e61f8f74fb424b0cc9ac42b823ff60ca",
  "effects": [
   "DELETION",
   "FILES",
   "PUSH",
   "SETTINGS"
  ],
  "fields": []
 },
 "app/api/partner/actions/decide/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "ac7b00c172d2447a726a9aebb459a84ef84dd87a149574338883311355159d61",
  "effects": [
   "DELETION",
   "FILES",
   "PUSH",
   "SETTINGS"
  ],
  "fields": [
   "actionId",
   "decision",
   "deferChoice",
   "deferDateYmd",
   "deferUntil",
   "expectedHeadEventId",
   "requestId",
   "seenSnapshotHash"
  ]
 },
 "app/api/partner/actions/execute/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "46e3476ed3e426dd11fdef097ee21129ff3e0cbde8549cc87fcdd616be3a34b3",
  "effects": [
   "DELETION",
   "FILES",
   "PUSH",
   "SETTINGS"
  ],
  "fields": [
   "approvalEventId",
   "requestId"
  ]
 },
 "app/api/partner/finance/answer/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "d9ff4b34a9efdbdeaa8a336b3418371234376f66e0d62ed127af711d623c69f5",
  "effects": [
   "DELETION",
   "SETTINGS"
  ],
  "fields": []
 },
 "app/api/partner/integrity/answer/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "e6afa4001d68e378d7c3ab15c010875d6f819cdea46ed330f28d1e499c51bef7",
  "effects": [
   "DELETION",
   "FILES",
   "PUSH",
   "SETTINGS"
  ],
  "fields": []
 },
 "app/api/partner/internal/act/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "70cade06e5de12c4f03343af5a1b7a5eebcf0157c9a1d09262a83a74a960b069",
  "effects": [
   "CALENDAR",
   "DELETION",
   "EMAIL",
   "EXTERNAL_LINK",
   "FILES",
   "FINANCE",
   "GOOGLE_TASKS",
   "LEDGER",
   "PUSH",
   "SETTINGS"
  ],
  "fields": []
 },
 "app/api/project-actions/[id]/route.ts": {
  "methods": [
   "DELETE",
   "PATCH"
  ],
  "getWrites": false,
  "sha256": "d30c233c1876b87abe0e66d6c812b6fe2c0020d1d663330ce7a4bb4121af37b1",
  "effects": [
   "DELETION",
   "EXTERNAL_LINK",
   "FILES",
   "FINANCE",
   "GOOGLE_TASKS",
   "PUSH",
   "SETTINGS"
  ],
  "fields": [
   "actionDate",
   "actionType",
   "action_date",
   "action_type",
   "agreed",
   "contentType",
   "content_type",
   "currency",
   "dropboxUrl",
   "dropbox_url",
   "followupDate",
   "followup_date",
   "linkedTaskId",
   "linkedWorkId",
   "linked_task_id",
   "linked_work_id",
   "master_status",
   "mix_status",
   "note",
   "notes",
   "projectId",
   "project_id",
   "recipientClientId",
   "recipientName",
   "recipientPhone",
   "recipientRole",
   "recipient_name",
   "recipient_phone",
   "recipient_role",
   "rows",
   "status",
   "title",
   "track_number",
   "versionLabel",
   "version_label"
  ]
 },
 "app/api/project-actions/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "7e76b388c5d0a059e76de6edb536a4dcf3f197b7037f782c25721cdb40466895",
  "effects": [
   "DELETION",
   "EXTERNAL_LINK",
   "FILES",
   "FINANCE",
   "GOOGLE_TASKS",
   "PUSH",
   "SETTINGS"
  ],
  "fields": [
   "actionDate",
   "actionType",
   "action_date",
   "action_type",
   "agreed",
   "contentType",
   "content_type",
   "currency",
   "dropboxUrl",
   "dropbox_url",
   "followupDate",
   "followup_date",
   "linkedTaskId",
   "linkedWorkId",
   "linked_task_id",
   "linked_work_id",
   "master_status",
   "mix_status",
   "note",
   "notes",
   "projectId",
   "project_id",
   "recipientClientId",
   "recipientName",
   "recipientPhone",
   "recipientRole",
   "recipient_name",
   "recipient_phone",
   "recipient_role",
   "rows",
   "status",
   "title",
   "track_number",
   "versionLabel",
   "version_label"
  ]
 },
 "app/api/projects/[id]/clip/payments/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "702daa9ca700179488d3427137dbe4ffc3daaf2e015b8dacc0acff965aaae3d5",
  "effects": [
   "DELETION",
   "FINANCE",
   "LEDGER",
   "SETTINGS"
  ],
  "fields": [
   "amount",
   "category",
   "clipAgreedPrice",
   "date",
   "description",
   "notes",
   "paymentStatus",
   "seed"
  ]
 },
 "app/api/projects/[id]/clip/route.ts": {
  "methods": [
   "PATCH"
  ],
  "getWrites": false,
  "sha256": "b97d7b15f72005dd63bde526336aa8dc536f3d5155d4d446a1b79060f28d5f15",
  "effects": [
   "DELETION",
   "FINANCE",
   "LEDGER",
   "SETTINGS"
  ],
  "fields": [
   "amount",
   "category",
   "clipAgreedPrice",
   "date",
   "description",
   "notes",
   "paymentStatus",
   "seed"
  ]
 },
 "app/api/projects/[id]/clip/send/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "356bcbde091e657738998046edc4e7cf41f6972dec0f783063e980152ebd1fba",
  "effects": [
   "DELETION",
   "FINANCE",
   "LEDGER",
   "SETTINGS"
  ],
  "fields": [
   "amount",
   "category",
   "clipAgreedPrice",
   "date",
   "description",
   "notes",
   "paymentStatus",
   "seed"
  ]
 },
 "app/api/projects/[id]/cover/route.ts": {
  "methods": [
   "DELETE",
   "PUT"
  ],
  "getWrites": false,
  "sha256": "417fd86f2b0b626f8e578bfeb470ed87271120f16a97af4c2758acfee3eca652",
  "effects": [
   "DELETION",
   "FILES",
   "SETTINGS"
  ],
  "fields": [
   "theme"
  ]
 },
 "app/api/projects/[id]/route.ts": {
  "methods": [
   "DELETE",
   "PATCH"
  ],
  "getWrites": false,
  "sha256": "515506e0e771a3d5bdb7e40df1bfd0e6efbe080d7aca5028964aaba1d3a7ddaa",
  "effects": [
   "CALENDAR",
   "DELETION",
   "EXTERNAL_LINK",
   "FILES",
   "FINANCE",
   "GOOGLE_TASKS",
   "LEDGER",
   "PUSH",
   "SETTINGS"
  ],
  "fields": [
   "artist",
   "completeIfAllowed",
   "deadline",
   "end_date",
   "field",
   "isHidden",
   "name",
   "notes",
   "parentProject",
   "plannedDays",
   "plannedHours",
   "projectType",
   "startDate",
   "status",
   "value"
  ]
 },
 "app/api/projects/backfill-start-dates/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "9e6b109d33a85f721bdcf9a727efd7dc3a8cd296d2cf5aa65fc8c2133487c8b3",
  "effects": [],
  "fields": []
 },
 "app/api/projects/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "486ceb2e7b45ed5419e86a97f5f59dfff0a3fd9925e2eca10af1e5b650dbbca5",
  "effects": [
   "DELETION",
   "FILES",
   "LEDGER",
   "SETTINGS"
  ],
  "fields": [
   "artist",
   "deadline",
   "name",
   "notes",
   "parentProject",
   "projectType",
   "status"
  ]
 },
 "app/api/projects/sync-artists/route.ts": {
  "methods": [],
  "getWrites": true,
  "sha256": "f4169fdd348334e643e85a54c47a8885a3ec815c4ba6d5aa97fb30117ab09c11",
  "effects": [],
  "fields": []
 },
 "app/api/proposals/[id]/convert/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "c96caa3413bb3424da68a44bdc9e38fac9e10eb11741acbc1cb931be97c5a1b0",
  "effects": [
   "DELETION",
   "GOOGLE_TASKS",
   "SETTINGS"
  ],
  "fields": [
   "amount",
   "clientId",
   "currency",
   "followupDate",
   "followup_date",
   "linkedProjectId",
   "linked_project_id",
   "notes",
   "projectName",
   "sentDate",
   "sent_date",
   "status",
   "title",
   "updated_at"
  ]
 },
 "app/api/proposals/[id]/route.ts": {
  "methods": [
   "DELETE",
   "PATCH"
  ],
  "getWrites": false,
  "sha256": "0e0b7ec900523c49dd0c41677dd9e96cab3e97af67e01a006bf939151e3a0251",
  "effects": [
   "DELETION",
   "GOOGLE_TASKS",
   "SETTINGS"
  ],
  "fields": [
   "amount",
   "clientId",
   "currency",
   "followupDate",
   "followup_date",
   "linkedProjectId",
   "linked_project_id",
   "notes",
   "sentDate",
   "sent_date",
   "status",
   "title",
   "updated_at"
  ]
 },
 "app/api/proposals/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "4f24dcc1d314847455cc551c10107c1e1f48af2207dbd256a84392f0c7be1efb",
  "effects": [
   "DELETION",
   "GOOGLE_TASKS",
   "SETTINGS"
  ],
  "fields": [
   "amount",
   "clientId",
   "currency",
   "followupDate",
   "followup_date",
   "linkedProjectId",
   "linked_project_id",
   "notes",
   "sentDate",
   "sent_date",
   "status",
   "title",
   "updated_at"
  ]
 },
 "app/api/push/check/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "1486f9f11c261da55c875fba3c7c08aecf2865816b774546aa7d0520865d939f",
  "effects": [
   "PUSH",
   "SETTINGS"
  ],
  "fields": []
 },
 "app/api/push/subscribe/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "658b4d7e43478b534bdf2b37114d5611d74dc4508ff57f347aa0a89594270979",
  "effects": [],
  "fields": []
 },
 "app/api/red-artists/availability/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "977162db7ee2e1a99adbf76c3527d28400cef413f99b49f877016a0463d88f74",
  "effects": [
   "PUSH",
   "SETTINGS"
  ],
  "fields": []
 },
 "app/api/red-artists/cleantone/ping/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "32c26d01f3e6eafbd00ff842eb7a36aae8879c77135e1e0247c3d888ffcb4a0a",
  "effects": [
   "PUSH",
   "SETTINGS"
  ],
  "fields": []
 },
 "app/api/red-artists/cleantone/profile-image/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "12c4c7f61f26c69b8f0b375f1e0e6b0abae69b65171c6dc70087af51e63dafd0",
  "effects": [
   "EXTERNAL_LINK",
   "FILES"
  ],
  "fields": []
 },
 "app/api/red-artists/cleantone/push-subscribe/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "87606a93c7553b688378afbad0270b1d901931e59a54afbe40657f644b1f301f",
  "effects": [],
  "fields": []
 },
 "app/api/red-artists/cleantone/shows/[id]/confirm/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "a59882e0bed76736a88906fd0036f3e0a7e689181d94191dc250f64deaa8b41c",
  "effects": [
   "DELETION",
   "PUSH"
  ],
  "fields": []
 },
 "app/api/red-artists/cleantone/shows/[id]/unconfirm/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "3e589502a7df798a2317558ea2df8f5d0277919823780273cd7edfaf0d5c3671",
  "effects": [
   "DELETION"
  ],
  "fields": []
 },
 "app/api/red-artists/next-work/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "a4a1d0066d3b45c69d9e9af8d609231fefbc47b142ef310459d6ff09dc60bf13",
  "effects": [
   "FILES"
  ],
  "fields": [
   "deadline",
   "sketchId"
  ]
 },
 "app/api/red-artists/ping/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "4b8ba573fa14af490b70bce16c6839f82f7ca85d0546450e242d3fed3fc1645f",
  "effects": [
   "PUSH",
   "SETTINGS"
  ],
  "fields": []
 },
 "app/api/red-artists/press-kit-link/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "8de1c177f46f36b0e2e14d4578be21c2428da1c359aee47c25f1a93e358585b8",
  "effects": [
   "EXTERNAL_LINK",
   "FILES"
  ],
  "fields": []
 },
 "app/api/red-artists/profile-image/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "fcc3f5d6c1285bf12c01365a5029b139910315f99612262ca330c811372548ba",
  "effects": [
   "EXTERNAL_LINK",
   "FILES"
  ],
  "fields": []
 },
 "app/api/red-artists/push-subscribe/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "372fa71b2474616feb6cae880c61226e03fa3ebb87b105ad39fcc6ac08239604",
  "effects": [],
  "fields": []
 },
 "app/api/red-artists/sketches/[id]/duration/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "41c92981b9bd71dac41cced239c84c321f5d4931e06ab1c55e8ca7dcbcfa8dff",
  "effects": [
   "FILES"
  ],
  "fields": [
   "durationSeconds",
   "versionNumber"
  ]
 },
 "app/api/red-artists/sketches/[id]/route.ts": {
  "methods": [
   "DELETE",
   "PATCH"
  ],
  "getWrites": false,
  "sha256": "ffe50dace150a92f4fa554e38d73917d7c0291fc17e66eed7d126e454522323c",
  "effects": [
   "FILES"
  ],
  "fields": [
   "description",
   "notes",
   "title"
  ]
 },
 "app/api/red-artists/sketches/[id]/version/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "dca1fcc06161020c25ade3b0e0de80508a4e040a813507893fa5277108b0ede3",
  "effects": [
   "FILES",
   "PUSH"
  ],
  "fields": []
 },
 "app/api/red-artists/sketches/reorder/route.ts": {
  "methods": [
   "PATCH"
  ],
  "getWrites": false,
  "sha256": "312f8832a89eb963d160177dd89429849134bbd4f2b8dd14439d22ca451a1c5f",
  "effects": [
   "FILES"
  ],
  "fields": []
 },
 "app/api/red-artists/sketches/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "bcc39f554ec52b24a2c583bff3fd6ee10bf5964ced39823d7f5ea6e83220ffbd",
  "effects": [
   "FILES",
   "PUSH"
  ],
  "fields": []
 },
 "app/api/red-artists/track-duration/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "06e20b44e585d4df44f0caeceb73fe9e8e7b6bee93b2696ec2918f4e806eacf5",
  "effects": [
   "DELETION"
  ],
  "fields": [
   "dropboxPath",
   "durationSeconds",
   "projectId"
  ]
 },
 "app/api/red-artists/upload/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "4b53c4e2b507582d0e61027c9037f53c6c06c1a5e06e9bb8f9ba5933d2eae241",
  "effects": [
   "EXTERNAL_LINK",
   "FILES"
  ],
  "fields": []
 },
 "app/api/red-films/budget-items/[itemId]/payments/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "f2230177508724d887c162d6e32c78130fb2ef323479af93f8e66285bae01349",
  "effects": [
   "DELETION",
   "EXTERNAL_LINK",
   "FILES",
   "FINANCE",
   "GOOGLE_TASKS",
   "LEDGER",
   "PUSH",
   "SETTINGS"
  ],
  "fields": [
   "acquired_date",
   "actual_amount",
   "added_by",
   "amount",
   "artist_name",
   "category",
   "client_id",
   "client_name",
   "client_source",
   "currency",
   "description",
   "name",
   "notes",
   "photographer_name",
   "planned_amount",
   "production_type",
   "projectId",
   "project_id",
   "provider",
   "purchase_price",
   "purchased_from",
   "quantity",
   "removed_at",
   "serial_number",
   "status",
   "thumbnail_url",
   "title",
   "updated_at",
   "url",
   "vendor_name",
   "video_id"
  ]
 },
 "app/api/red-films/budget-items/[itemId]/route.ts": {
  "methods": [
   "DELETE",
   "PATCH"
  ],
  "getWrites": false,
  "sha256": "89de289fd2ed03acdb2449684d46836dab3b5fdf336e4884d666737e1eb37738",
  "effects": [
   "DELETION",
   "EXTERNAL_LINK",
   "FILES",
   "FINANCE",
   "GOOGLE_TASKS",
   "LEDGER",
   "SETTINGS"
  ],
  "fields": [
   "acquired_date",
   "actual_amount",
   "added_by",
   "amount",
   "artist_name",
   "category",
   "client_id",
   "client_name",
   "client_source",
   "currency",
   "description",
   "name",
   "notes",
   "photographer_name",
   "planned_amount",
   "production_type",
   "projectId",
   "project_id",
   "provider",
   "purchase_price",
   "purchased_from",
   "quantity",
   "removed_at",
   "serial_number",
   "status",
   "thumbnail_url",
   "title",
   "updated_at",
   "url",
   "vendor_name",
   "video_id"
  ]
 },
 "app/api/red-films/budget-payments/[paymentId]/receipt/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "d27147ed1192a9bf37eb795ae73dad37ea6b21464c2730b29104382d363297bb",
  "effects": [
   "DELETION",
   "EXTERNAL_LINK",
   "FILES",
   "FINANCE",
   "LEDGER",
   "PUSH",
   "SETTINGS"
  ],
  "fields": []
 },
 "app/api/red-films/budget-payments/[paymentId]/route.ts": {
  "methods": [
   "DELETE",
   "PATCH"
  ],
  "getWrites": false,
  "sha256": "d0986855ef6d1d2e5eaffa7858101c3233d0bb7ad2abcc6c443185fdde5c657b",
  "effects": [
   "DELETION",
   "EXTERNAL_LINK",
   "FILES",
   "FINANCE",
   "GOOGLE_TASKS",
   "LEDGER",
   "SETTINGS"
  ],
  "fields": [
   "acquired_date",
   "actual_amount",
   "added_by",
   "amount",
   "artist_name",
   "category",
   "client_id",
   "client_name",
   "client_source",
   "currency",
   "description",
   "name",
   "notes",
   "photographer_name",
   "planned_amount",
   "production_type",
   "projectId",
   "project_id",
   "provider",
   "purchase_price",
   "purchased_from",
   "quantity",
   "removed_at",
   "serial_number",
   "status",
   "thumbnail_url",
   "title",
   "updated_at",
   "url",
   "vendor_name",
   "video_id"
  ]
 },
 "app/api/red-films/documents/[docId]/route.ts": {
  "methods": [
   "DELETE"
  ],
  "getWrites": false,
  "sha256": "1ead82d412831b6430b3f5070d69e4b4e1db88023b93898d5c3618cccf805e5a",
  "effects": [
   "DELETION",
   "EXTERNAL_LINK",
   "FILES",
   "FINANCE",
   "GOOGLE_TASKS",
   "LEDGER",
   "SETTINGS"
  ],
  "fields": [
   "acquired_date",
   "actual_amount",
   "added_by",
   "amount",
   "artist_name",
   "category",
   "client_id",
   "client_name",
   "client_source",
   "currency",
   "description",
   "name",
   "notes",
   "photographer_name",
   "planned_amount",
   "production_type",
   "projectId",
   "project_id",
   "provider",
   "purchase_price",
   "purchased_from",
   "quantity",
   "removed_at",
   "serial_number",
   "status",
   "thumbnail_url",
   "title",
   "updated_at",
   "url",
   "vendor_name",
   "video_id"
  ]
 },
 "app/api/red-films/equipment/[id]/route.ts": {
  "methods": [
   "PATCH"
  ],
  "getWrites": false,
  "sha256": "5ae958bbe4ef9f45436d455b3610404344f0a6a4711fa1216d190c564dc233e8",
  "effects": [
   "DELETION",
   "EXTERNAL_LINK",
   "FILES",
   "FINANCE",
   "GOOGLE_TASKS",
   "LEDGER",
   "SETTINGS"
  ],
  "fields": [
   "acquired_date",
   "actual_amount",
   "added_by",
   "amount",
   "artist_name",
   "category",
   "client_id",
   "client_name",
   "client_source",
   "currency",
   "description",
   "name",
   "notes",
   "photographer_name",
   "planned_amount",
   "production_type",
   "projectId",
   "project_id",
   "provider",
   "purchase_price",
   "purchased_from",
   "quantity",
   "removed_at",
   "serial_number",
   "status",
   "thumbnail_url",
   "title",
   "updated_at",
   "url",
   "vendor_name",
   "video_id"
  ]
 },
 "app/api/red-films/equipment/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "7cda72252ef7b6f138d6734079c3329b97d2dfd7df0a801d103358edec91d0d9",
  "effects": [
   "DELETION",
   "EXTERNAL_LINK",
   "FILES",
   "FINANCE",
   "GOOGLE_TASKS",
   "LEDGER",
   "SETTINGS"
  ],
  "fields": [
   "acquired_date",
   "actual_amount",
   "added_by",
   "amount",
   "artist_name",
   "category",
   "client_id",
   "client_name",
   "client_source",
   "currency",
   "description",
   "name",
   "notes",
   "photographer_name",
   "planned_amount",
   "production_type",
   "projectId",
   "project_id",
   "provider",
   "purchase_price",
   "purchased_from",
   "quantity",
   "removed_at",
   "serial_number",
   "status",
   "thumbnail_url",
   "title",
   "updated_at",
   "url",
   "vendor_name",
   "video_id"
  ]
 },
 "app/api/red-films/productions/[id]/budget-items/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "53ad9f656d497b338ce62a30c566c3ae92bf0ce9491a6467bbd762f2f0abc8b8",
  "effects": [
   "DELETION",
   "EXTERNAL_LINK",
   "FILES",
   "FINANCE",
   "GOOGLE_TASKS",
   "LEDGER",
   "SETTINGS"
  ],
  "fields": [
   "acquired_date",
   "actual_amount",
   "added_by",
   "amount",
   "artist_name",
   "category",
   "client_id",
   "client_name",
   "client_source",
   "currency",
   "description",
   "name",
   "notes",
   "photographer_name",
   "planned_amount",
   "production_type",
   "projectId",
   "project_id",
   "provider",
   "purchase_price",
   "purchased_from",
   "quantity",
   "removed_at",
   "serial_number",
   "status",
   "thumbnail_url",
   "title",
   "updated_at",
   "url",
   "vendor_name",
   "video_id"
  ]
 },
 "app/api/red-films/productions/[id]/documents/upload/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "82561ad85f4861a6189539aeeef435da737df14851266f95138920ae7068800b",
  "effects": [
   "DELETION",
   "EXTERNAL_LINK",
   "FILES",
   "FINANCE",
   "LEDGER",
   "PUSH",
   "SETTINGS"
  ],
  "fields": []
 },
 "app/api/red-films/productions/[id]/dropbox-folder/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "bc33b9a89294c59d81aebe4ddd6f881689b1e2e1bd65adba0a657ee9a5cf0e86",
  "effects": [
   "DELETION",
   "EXTERNAL_LINK",
   "FILES",
   "FINANCE",
   "GOOGLE_TASKS",
   "LEDGER",
   "SETTINGS"
  ],
  "fields": []
 },
 "app/api/red-films/productions/[id]/reference-links/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "be21f154429aed21ab3e28f2f4140483631c854c662470a9d9c8771ef94817bb",
  "effects": [
   "DELETION",
   "EXTERNAL_LINK",
   "FILES",
   "FINANCE",
   "GOOGLE_TASKS",
   "LEDGER",
   "SETTINGS"
  ],
  "fields": [
   "acquired_date",
   "actual_amount",
   "added_by",
   "amount",
   "artist_name",
   "category",
   "client_id",
   "client_name",
   "client_source",
   "currency",
   "description",
   "name",
   "notes",
   "photographer_name",
   "planned_amount",
   "production_type",
   "projectId",
   "project_id",
   "provider",
   "purchase_price",
   "purchased_from",
   "quantity",
   "removed_at",
   "serial_number",
   "status",
   "thumbnail_url",
   "title",
   "updated_at",
   "url",
   "vendor_name",
   "video_id"
  ]
 },
 "app/api/red-films/productions/[id]/references/upload/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "0bfb748b1fdc1fa279fc172ab270b0bacf78ea096a77a9da862a8e0d92468f81",
  "effects": [
   "DELETION",
   "EXTERNAL_LINK",
   "FILES",
   "FINANCE",
   "LEDGER",
   "PUSH",
   "SETTINGS"
  ],
  "fields": []
 },
 "app/api/red-films/productions/[id]/route.ts": {
  "methods": [
   "PATCH"
  ],
  "getWrites": false,
  "sha256": "3fb198a3244277eadef0b231ba76357b3f9385078a585f5f55bf85c5331e0b0d",
  "effects": [
   "DELETION",
   "EXTERNAL_LINK",
   "FILES",
   "FINANCE",
   "GOOGLE_TASKS",
   "LEDGER",
   "SETTINGS"
  ],
  "fields": [
   "acquired_date",
   "actual_amount",
   "added_by",
   "amount",
   "artist_name",
   "category",
   "client_id",
   "client_name",
   "client_source",
   "currency",
   "description",
   "name",
   "notes",
   "photographer_name",
   "planned_amount",
   "production_type",
   "projectId",
   "project_id",
   "provider",
   "purchase_price",
   "purchased_from",
   "quantity",
   "removed_at",
   "serial_number",
   "status",
   "thumbnail_url",
   "title",
   "updated_at",
   "url",
   "vendor_name",
   "video_id"
  ]
 },
 "app/api/red-films/productions/bulk-permanent-delete/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "c176d9d02f12393c56c7faf612762b6a1a89f4b993f2befc709b0647d4201e1b",
  "effects": [
   "DELETION",
   "EXTERNAL_LINK",
   "FILES",
   "FINANCE",
   "GOOGLE_TASKS",
   "LEDGER",
   "SETTINGS"
  ],
  "fields": [
   "acquired_date",
   "actual_amount",
   "added_by",
   "amount",
   "artist_name",
   "category",
   "client_id",
   "client_name",
   "client_source",
   "currency",
   "description",
   "ids",
   "name",
   "notes",
   "photographer_name",
   "planned_amount",
   "production_type",
   "projectId",
   "project_id",
   "provider",
   "purchase_price",
   "purchased_from",
   "quantity",
   "removed_at",
   "serial_number",
   "status",
   "thumbnail_url",
   "title",
   "updated_at",
   "url",
   "vendor_name",
   "video_id"
  ]
 },
 "app/api/red-films/productions/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "dd055fbfcdd19fa33cb5d241c7024696a8326b9054e639a420bb5648e2be184a",
  "effects": [
   "DELETION",
   "EXTERNAL_LINK",
   "FILES",
   "FINANCE",
   "GOOGLE_TASKS",
   "LEDGER",
   "SETTINGS"
  ],
  "fields": [
   "acquired_date",
   "actual_amount",
   "added_by",
   "amount",
   "artist_name",
   "category",
   "client_id",
   "client_name",
   "client_source",
   "currency",
   "description",
   "name",
   "notes",
   "photographer_name",
   "planned_amount",
   "production_type",
   "projectId",
   "project_id",
   "provider",
   "purchase_price",
   "purchased_from",
   "quantity",
   "removed_at",
   "serial_number",
   "status",
   "thumbnail_url",
   "title",
   "updated_at",
   "url",
   "vendor_name",
   "video_id"
  ]
 },
 "app/api/red-films/reference-links/[linkId]/route.ts": {
  "methods": [
   "DELETE",
   "PATCH"
  ],
  "getWrites": false,
  "sha256": "0cb8c35deed6e7daf1a22f5c23ac4b668ea2d7d6345da23f58f3e1cbdc121c10",
  "effects": [
   "DELETION",
   "EXTERNAL_LINK",
   "FILES",
   "FINANCE",
   "GOOGLE_TASKS",
   "LEDGER",
   "SETTINGS"
  ],
  "fields": [
   "acquired_date",
   "actual_amount",
   "added_by",
   "amount",
   "artist_name",
   "category",
   "client_id",
   "client_name",
   "client_source",
   "currency",
   "description",
   "name",
   "notes",
   "photographer_name",
   "planned_amount",
   "production_type",
   "projectId",
   "project_id",
   "provider",
   "purchase_price",
   "purchased_from",
   "quantity",
   "removed_at",
   "serial_number",
   "status",
   "thumbnail_url",
   "title",
   "updated_at",
   "url",
   "vendor_name",
   "video_id"
  ]
 },
 "app/api/red-films/references/[refId]/route.ts": {
  "methods": [
   "DELETE",
   "PATCH"
  ],
  "getWrites": false,
  "sha256": "b1ba636f8038e73a4078423b9ef9e2689ff9010e628f76d84e712ac2b590a244",
  "effects": [
   "DELETION",
   "EXTERNAL_LINK",
   "FILES",
   "FINANCE",
   "GOOGLE_TASKS",
   "LEDGER",
   "SETTINGS"
  ],
  "fields": [
   "acquired_date",
   "actual_amount",
   "added_by",
   "amount",
   "artist_name",
   "category",
   "client_id",
   "client_name",
   "client_source",
   "currency",
   "description",
   "name",
   "notes",
   "photographer_name",
   "planned_amount",
   "production_type",
   "projectId",
   "project_id",
   "provider",
   "purchase_price",
   "purchased_from",
   "quantity",
   "removed_at",
   "serial_number",
   "status",
   "tag",
   "thumbnail_url",
   "title",
   "updated_at",
   "url",
   "vendor_name",
   "video_id"
  ]
 },
 "app/api/reports/config/route.ts": {
  "methods": [
   "POST",
   "PUT"
  ],
  "getWrites": false,
  "sha256": "335adcbee081b405d3bf3a17f1e7091346eb4f0d1b371d5122ffded1faf5e65f",
  "effects": [
   "DELETION",
   "EMAIL",
   "SETTINGS"
  ],
  "fields": [
   "eveningTime",
   "morningTime"
  ]
 },
 "app/api/reports/evening/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "47979ec59bff62c61a02525f9cacf042329ca5d405eea20a2e4f31282a9d029f",
  "effects": [
   "DELETION",
   "EMAIL",
   "SETTINGS"
  ],
  "fields": []
 },
 "app/api/reports/morning/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "aea37269685bf50ba74f479e7628c760473523c39aecf842de4c5a862f6a52fb",
  "effects": [
   "DELETION",
   "EMAIL",
   "SETTINGS"
  ],
  "fields": []
 },
 "app/api/reports/weekly/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "6e99575f60863dbf2bfc59355bb3a0a4ed210ef82d620df1d698a238eb9cf752",
  "effects": [
   "DELETION",
   "EMAIL",
   "SETTINGS"
  ],
  "fields": []
 },
 "app/api/sessions/[id]/route.ts": {
  "methods": [
   "DELETE",
   "PATCH"
  ],
  "getWrites": false,
  "sha256": "98dfee401a019eebb647cd19c6d979b2dba8dbd2f3df9cf3f501e239b4266a86",
  "effects": [
   "CALENDAR",
   "DELETION",
   "FINANCE",
   "LEDGER",
   "PUSH"
  ],
  "fields": [
   "addToCalendar",
   "calendarEventId",
   "cost",
   "date",
   "endIso",
   "endTime",
   "end_time",
   "invite",
   "location",
   "notes",
   "paymentStatus",
   "photographer",
   "projectId",
   "sessionType",
   "session_type",
   "showId",
   "startIso",
   "startTime",
   "start_time",
   "status",
   "summary",
   "title"
  ]
 },
 "app/api/sessions/calendar-pull/route.ts": {
  "methods": [],
  "getWrites": true,
  "sha256": "c946ccb0777605b2bde4e3298af25372f1520f22f42e34a0f9efdc2ce491a71e",
  "effects": [
   "CALENDAR",
   "DELETION",
   "FINANCE",
   "LEDGER",
   "PUSH"
  ],
  "fields": [
   "addToCalendar",
   "calendarEventId",
   "cost",
   "date",
   "endIso",
   "endTime",
   "end_time",
   "invite",
   "location",
   "notes",
   "paymentStatus",
   "photographer",
   "projectId",
   "sessionType",
   "session_type",
   "showId",
   "startIso",
   "startTime",
   "start_time",
   "status",
   "summary",
   "title"
  ]
 },
 "app/api/sessions/route.ts": {
  "methods": [
   "PATCH",
   "POST"
  ],
  "getWrites": false,
  "sha256": "a11dfcc76d9c59664ddbd8d8238171feab46cae4691b44294aba559079c7e3d4",
  "effects": [
   "CALENDAR",
   "DELETION",
   "FINANCE",
   "LEDGER",
   "PUSH",
   "SETTINGS"
  ],
  "fields": [
   "addToCalendar",
   "calendarEventId",
   "cost",
   "date",
   "endIso",
   "endTime",
   "end_time",
   "invite",
   "location",
   "notes",
   "paymentStatus",
   "photographer",
   "projectId",
   "sessionType",
   "session_type",
   "showId",
   "startIso",
   "startTime",
   "start_time",
   "status",
   "summary",
   "title"
  ]
 },
 "app/api/shows/[id]/notify-artist/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "715f854bd0055e234c09467cac9928ca25666bb6865b352585fecbcdb1d3fe5f",
  "effects": [
   "DELETION",
   "PUSH",
   "SETTINGS"
  ],
  "fields": []
 },
 "app/api/shows/[id]/notify-dj/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "656cb1780d42bdb7d92c11e1599faadb5c077d979455a6facc5b6afd9e1e9bbf",
  "effects": [
   "DELETION",
   "PUSH",
   "SETTINGS"
  ],
  "fields": []
 },
 "app/api/shows/[id]/payments/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "8d30abbd4f25939ddf91b0da95bb0444b6ba0366e40f09530f0276c754e59955",
  "effects": [
   "DELETION",
   "FINANCE",
   "LEDGER"
  ],
  "fields": [
   "amount",
   "currency",
   "date",
   "method",
   "note"
  ]
 },
 "app/api/shows/[id]/quote-sent/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "559ebb430478896ff4860604084cf6303496517b93a477523848fa565e6d9686",
  "effects": [
   "CALENDAR",
   "DELETION",
   "FINANCE",
   "GOOGLE_TASKS",
   "LEDGER",
   "PUSH",
   "SETTINGS"
  ],
  "fields": [
   "addToCalendar",
   "advance_date",
   "advance_payment",
   "artist",
   "artistPaidDate",
   "artist_client_id",
   "artist_fee",
   "booker_client_id",
   "booker_name",
   "calendar_event_id",
   "closeShow",
   "contact_person",
   "currency",
   "date",
   "deal_type",
   "dj_client_id",
   "dj_fee",
   "dj_name",
   "location",
   "name",
   "notes",
   "payment_method",
   "payment_status",
   "phone",
   "removeFromCalendar",
   "show_price",
   "start_time",
   "status"
  ]
 },
 "app/api/shows/[id]/route.ts": {
  "methods": [
   "DELETE",
   "PATCH"
  ],
  "getWrites": false,
  "sha256": "99028c8731059a62940ffccb4b54d965efda2e492adbae2d7122ba95585c7be0",
  "effects": [
   "CALENDAR",
   "DELETION",
   "FINANCE",
   "GOOGLE_TASKS",
   "LEDGER",
   "PUSH",
   "SETTINGS"
  ],
  "fields": [
   "addToCalendar",
   "advance_date",
   "advance_payment",
   "artist",
   "artistPaidDate",
   "artist_client_id",
   "artist_fee",
   "booker_client_id",
   "booker_name",
   "calendar_event_id",
   "closeShow",
   "contact_person",
   "currency",
   "date",
   "deal_type",
   "dj_client_id",
   "dj_fee",
   "dj_name",
   "location",
   "name",
   "notes",
   "payment_method",
   "payment_status",
   "phone",
   "removeFromCalendar",
   "show_price",
   "start_time",
   "status"
  ]
 },
 "app/api/shows/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "6b92b5d6c2884863a2ddaf4922f8d20935c63dd456077ebc50fd59b22e3d2b62",
  "effects": [
   "CALENDAR",
   "DELETION",
   "FINANCE",
   "GOOGLE_TASKS",
   "LEDGER",
   "PUSH",
   "SETTINGS"
  ],
  "fields": [
   "addToCalendar",
   "advance_date",
   "advance_payment",
   "artist",
   "artistPaidDate",
   "artist_client_id",
   "artist_fee",
   "booker_client_id",
   "booker_name",
   "calendar_event_id",
   "closeShow",
   "contact_person",
   "currency",
   "date",
   "deal_type",
   "dj_client_id",
   "dj_fee",
   "dj_name",
   "location",
   "name",
   "notes",
   "payment_method",
   "payment_status",
   "phone",
   "removeFromCalendar",
   "show_price",
   "start_time",
   "status"
  ]
 },
 "app/api/social/campaigns/[id]/route.ts": {
  "methods": [
   "DELETE",
   "PATCH"
  ],
  "getWrites": false,
  "sha256": "d83be6be75d0a772e3e32606cd1ce9e7b929520b843de5afc692b2109324cac1",
  "effects": [
   "DELETION",
   "FILES",
   "FINANCE",
   "LEDGER"
  ],
  "fields": []
 },
 "app/api/social/campaigns/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "1ecf6dff5f5f85819e339c037b1775af8cd39898b71a47dd0fecace017f863d5",
  "effects": [
   "DELETION",
   "FILES",
   "FINANCE",
   "LEDGER"
  ],
  "fields": []
 },
 "app/api/social/content/[id]/route.ts": {
  "methods": [
   "DELETE",
   "PATCH"
  ],
  "getWrites": false,
  "sha256": "b31aa17ddb325020a6d257cc4ba19da669e26fe01968807cd1df47f955e4a68e",
  "effects": [
   "DELETION",
   "FILES",
   "FINANCE",
   "LEDGER"
  ],
  "fields": []
 },
 "app/api/social/content/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "3eeccb44981caaad2decc500c480344fa8d03cd53720b105407ea1508a36ad0d",
  "effects": [
   "DELETION",
   "FILES",
   "FINANCE",
   "LEDGER"
  ],
  "fields": []
 },
 "app/api/social/files/route.ts": {
  "methods": [
   "DELETE"
  ],
  "getWrites": false,
  "sha256": "09e2aa1ca304113015577fa7ddbe0f319a283ae1d36310c400166f77d7486d64",
  "effects": [
   "DELETION",
   "FILES",
   "FINANCE",
   "LEDGER"
  ],
  "fields": []
 },
 "app/api/social/migrate-paths/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "3564a3ccf282c47361346570eb6f4d18ba5973093f8e81c9c17fff86b7b04221",
  "effects": [
   "DELETION",
   "EXTERNAL_LINK",
   "FILES",
   "FINANCE",
   "LEDGER"
  ],
  "fields": [
   "secret"
  ]
 },
 "app/api/social/promotions/[id]/route.ts": {
  "methods": [
   "DELETE",
   "PATCH"
  ],
  "getWrites": false,
  "sha256": "23e11e41d3531a6ac9d388928621d02069ebff0ba2a371b0832e3a56b7120338",
  "effects": [
   "DELETION",
   "FINANCE",
   "LEDGER"
  ],
  "fields": [
   "actual",
   "channel",
   "name",
   "notes",
   "planned_amount",
   "promo_date",
   "promo_type",
   "status"
  ]
 },
 "app/api/social/promotions/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "9335f1f71e9a2d385f1dd219c6cbeb95ef7e8c9c2c02527e4b910eb0672865ed",
  "effects": [
   "DELETION",
   "FINANCE",
   "LEDGER"
  ],
  "fields": [
   "actual",
   "campaignId",
   "campaign_id",
   "channel",
   "name",
   "notes",
   "planned_amount",
   "promo_date",
   "promo_type",
   "status"
  ]
 },
 "app/api/social/upload/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "db3b9b9671db57e3d79134b8d2850450a47e7fb72bed64b8831b636da1091882",
  "effects": [
   "DELETION",
   "EXTERNAL_LINK",
   "FILES",
   "FINANCE",
   "LEDGER",
   "PUSH",
   "SETTINGS"
  ],
  "fields": []
 },
 "app/api/sound-engineer/[id]/final-files/batch-complete/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "45dfd9b4a35a6d8bca0dd50d8f2ad029781e69fcbef20cb15709178cb3ba28c4",
  "effects": [
   "DELETION",
   "PUSH",
   "SETTINGS"
  ],
  "fields": [
   "batchId"
  ]
 },
 "app/api/sound-engineer/[id]/final-files/chunk/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "20c897ca90b66e33fba456a17dd8c6c188391e8df7b3ac5014c8fb74bc3e5178",
  "effects": [
   "DELETION",
   "EXTERNAL_LINK",
   "FILES",
   "PUSH",
   "SETTINGS"
  ],
  "fields": []
 },
 "app/api/sound-engineer/[id]/final-files/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "1ee8f9f6ce21ef2b77c1679ba6d550b14254cefc274af157f18b8899755bdaea",
  "effects": [
   "DELETION",
   "EXTERNAL_LINK",
   "FILES",
   "PUSH",
   "SETTINGS"
  ],
  "fields": []
 },
 "app/api/sound-engineer/[id]/notify-mix-ready/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "d0b2b804c2946cc6decded4d2e37ea83093a486fc5b0f12a42d2d9acbb38a521",
  "effects": [
   "DELETION",
   "PUSH",
   "SETTINGS"
  ],
  "fields": []
 },
 "app/api/sound-engineer/[id]/notify-notes/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "e1af11e738db541fa9313550185d461992675a3c2ebe1ec656ad9bb1975c7565",
  "effects": [
   "DELETION",
   "PUSH",
   "SETTINGS"
  ],
  "fields": [
   "mixTargetId",
   "mixVersionId"
  ]
 },
 "app/api/sound-engineer/[id]/payment-expense/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "c19f2b9bf9c690acdb9555336ac3b87316353bdbeb7197e25f851d18b2e25764",
  "effects": [
   "DELETION",
   "PUSH",
   "SETTINGS"
  ],
  "fields": []
 },
 "app/api/sound-engineer/[id]/route.ts": {
  "methods": [
   "DELETE",
   "PATCH",
   "POST"
  ],
  "getWrites": false,
  "sha256": "7dc0b6fa50f26c2ac246fdde2d97113890dd90f7baca8a1d38e3d2deb45a95f2",
  "effects": [
   "DELETION",
   "FILES",
   "FINANCE",
   "PUSH",
   "SETTINGS"
  ],
  "fields": []
 },
 "app/api/sound-engineer/[id]/targets/[targetId]/notes/[noteId]/route.ts": {
  "methods": [
   "DELETE",
   "PATCH"
  ],
  "getWrites": false,
  "sha256": "11636af62f37b897d394e83e060dee5890bf749daa57ec4d092da935998bfe80",
  "effects": [
   "DELETION"
  ],
  "fields": [
   "noteText",
   "status"
  ]
 },
 "app/api/sound-engineer/[id]/targets/[targetId]/notes/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "36d337726089daf752cf5a9ea5eb064ca3b7e3141e697d8f4458c8554c836d70",
  "effects": [
   "DELETION"
  ],
  "fields": [
   "noteText"
  ]
 },
 "app/api/sound-engineer/[id]/targets/[targetId]/route.ts": {
  "methods": [
   "DELETE",
   "PATCH"
  ],
  "getWrites": false,
  "sha256": "ae25416dd01d06dcc39d42ff46e140730d7aff1d7e1cd53cf0e13c75bfd8b7fc",
  "effects": [],
  "fields": [
   "name"
  ]
 },
 "app/api/sound-engineer/[id]/targets/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "c06d400b2bca821c3d8270db8f6d9677de1610d88e39ed6f56e35f4074e4c675",
  "effects": [
   "DELETION"
  ],
  "fields": [
   "name"
  ]
 },
 "app/api/sound-engineer/[id]/versions/chunk/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "8a25cbe9a1d3dea611ef42c6b7cf7a1a480724a43ac5159bf78bf8081492635c",
  "effects": [
   "DELETION",
   "EXTERNAL_LINK",
   "FILES",
   "PUSH",
   "SETTINGS"
  ],
  "fields": []
 },
 "app/api/sound-engineer/[id]/versions/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "886850f1944ffe432416ecc4d265b83b39809d4a1f24dc21362addef41358c33",
  "effects": [
   "DELETION",
   "EXTERNAL_LINK",
   "FILES",
   "PUSH",
   "SETTINGS"
  ],
  "fields": []
 },
 "app/api/sound-engineer/[id]/work-materials/chunk/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "5e69df2d27998bc90735014909bad9e35d8337ffeb04dbdc44c0a02742e50929",
  "effects": [
   "DELETION",
   "FILES"
  ],
  "fields": []
 },
 "app/api/sound-engineer/[id]/work-materials/route.ts": {
  "methods": [
   "DELETE",
   "PATCH",
   "POST"
  ],
  "getWrites": false,
  "sha256": "cd379bb37a50baf1796de41938ff5357da710588710577119260e4db175185bd",
  "effects": [
   "DELETION",
   "EXTERNAL_LINK",
   "FILES",
   "FINANCE",
   "LEDGER",
   "PUSH",
   "SETTINGS"
  ],
  "fields": [
   "bpm",
   "instructions",
   "key"
  ]
 },
 "app/api/sound-engineer/comments/[commentId]/attachments/[attachmentId]/route.ts": {
  "methods": [
   "DELETE"
  ],
  "getWrites": false,
  "sha256": "37b30bd8e52e130cf3157fc8c56f234dca0c8ddff63df7a33f11d7b75dccfd7e",
  "effects": [
   "DELETION",
   "FILES",
   "FINANCE",
   "PUSH",
   "SETTINGS"
  ],
  "fields": []
 },
 "app/api/sound-engineer/comments/[commentId]/attachments/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "eeae839b3e84df99f33b5f478086ec0cd1d965fd7ce506faefbc77f74dee8c38",
  "effects": [
   "DELETION",
   "EXTERNAL_LINK",
   "FILES",
   "FINANCE",
   "LEDGER",
   "PUSH",
   "SETTINGS"
  ],
  "fields": []
 },
 "app/api/sound-engineer/comments/[commentId]/route.ts": {
  "methods": [
   "DELETE",
   "PATCH"
  ],
  "getWrites": false,
  "sha256": "01ce16c9991ff80506deaacf198cc9bf85c2bfaa3c3776885c2c49211a636bbb",
  "effects": [
   "DELETION",
   "FILES",
   "FINANCE",
   "PUSH",
   "SETTINGS"
  ],
  "fields": []
 },
 "app/api/sound-engineer/reorder/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "434542e8fc2224bf0c3a5eb6084a7ccb64d95ed496fbf18e250679ba80fea9c0",
  "effects": [
   "DELETION",
   "PUSH",
   "SETTINGS"
  ],
  "fields": [
   "ids"
  ]
 },
 "app/api/sound-engineer/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "0cb7941db703b2817c002356c963e44c261351c8e74010ecbdef037ec43fbe65",
  "effects": [
   "DELETION",
   "PUSH",
   "SETTINGS"
  ],
  "fields": [
   "agreedPrice",
   "amountPaid",
   "currency",
   "engineerName",
   "filesLink",
   "internalDeadline",
   "notes",
   "paymentDate",
   "projectId",
   "sentDate",
   "skipFinanceSync",
   "status",
   "title",
   "workTitle",
   "workType"
  ]
 },
 "app/api/sound-engineer/versions/[versionId]/comments/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "5fcd531bbfb2272ef8f56cbeac0234fba49982c2e5d56494bf4c2d8123f70b23",
  "effects": [
   "DELETION"
  ],
  "fields": [
   "author",
   "commentText",
   "role",
   "timestampSeconds"
  ]
 },
 "app/api/sound-engineer/versions/[versionId]/route.ts": {
  "methods": [
   "DELETE",
   "PATCH"
  ],
  "getWrites": false,
  "sha256": "43980ba036d402b531887b3e74ead0f00115b613e42d4ae5d4ecf967d5cf4e8f",
  "effects": [
   "DELETION",
   "FILES",
   "FINANCE",
   "PUSH",
   "SETTINGS"
  ],
  "fields": []
 },
 "app/api/supplier/steven/comments/[commentId]/route.ts": {
  "methods": [
   "DELETE",
   "PATCH"
  ],
  "getWrites": false,
  "sha256": "af722a667a0d19282cc7e6bdb28d57622f1760c8512cf6d771061f09d8a53bed",
  "effects": [
   "DELETION"
  ],
  "fields": [
   "status"
  ]
 },
 "app/api/supplier/steven/ping/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "305395afde5cda37536b9221b81d188e32c7abe839aa494ab48a5944bac41315",
  "effects": [
   "DELETION",
   "PUSH",
   "SETTINGS"
  ],
  "fields": []
 },
 "app/api/supplier/steven/push-subscribe/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "9b0929b380bfd0000c1b5562607ad25d3687ef9ba93ded3bb7fed10ec9e8298e",
  "effects": [],
  "fields": []
 },
 "app/api/supplier/steven/versions/[versionId]/comments/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "09ca68623930e77f9fc9e8359032c74aeb37e81be7a426dc1d5d74f30b7147f2",
  "effects": [
   "DELETION"
  ],
  "fields": [
   "author",
   "commentText",
   "role",
   "timestampSeconds"
  ]
 },
 "app/api/supplier/steven/work/[id]/final-files/batch-complete/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "0f2bd5cd51228ec9d023a8c2898ffb9f7ab71c6a9fd456414c17a373b009d1d8",
  "effects": [
   "DELETION",
   "PUSH",
   "SETTINGS"
  ],
  "fields": [
   "batchId"
  ]
 },
 "app/api/supplier/steven/work/[id]/final-files/chunk/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "e7016f318392f6ce2fa6f2106c8a2c057d35ac5f204c59b4214c02607689bee1",
  "effects": [
   "DELETION",
   "EXTERNAL_LINK",
   "FILES",
   "PUSH",
   "SETTINGS"
  ],
  "fields": []
 },
 "app/api/supplier/steven/work/[id]/final-files/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "08267235aa982d3ccc93a82ce5ac2e0cd35927bc3844b38c514ef745cc244aa8",
  "effects": [
   "DELETION",
   "EXTERNAL_LINK",
   "FILES",
   "PUSH",
   "SETTINGS"
  ],
  "fields": []
 },
 "app/api/supplier/steven/work/[id]/versions/chunk/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "a1a7340eb28364acf189d98ff6ed0acebb576e7057dd17df0e583ce3ba6f4d27",
  "effects": [
   "DELETION",
   "EXTERNAL_LINK",
   "FILES",
   "PUSH",
   "SETTINGS"
  ],
  "fields": []
 },
 "app/api/supplier/steven/work/[id]/versions/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "a7362e50f25ac5f8528390c9dc7866ef729640ed71bdc16e8586043cafaa4efe",
  "effects": [
   "DELETION",
   "EXTERNAL_LINK",
   "FILES",
   "PUSH",
   "SETTINGS"
  ],
  "fields": []
 },
 "app/api/tasks/[id]/route.ts": {
  "methods": [
   "DELETE",
   "PATCH"
  ],
  "getWrites": false,
  "sha256": "006df8b22edeca4b746a63144b91b349a5564e16b9225261886420bb579d5cfe",
  "effects": [
   "DELETION",
   "GOOGLE_TASKS"
  ],
  "fields": [
   "calendar_event_id",
   "due_date",
   "end_time",
   "notes",
   "related_id",
   "related_type",
   "start_time",
   "status",
   "title"
  ]
 },
 "app/api/tasks/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "bf3f52f0a71ff2531655b6fa40dd2bfd8dd4f544c705b880e60264e64f7040a2",
  "effects": [
   "DELETION"
  ],
  "fields": [
   "due_date",
   "end_time",
   "notes",
   "related_id",
   "related_type",
   "show_id",
   "start_time",
   "status",
   "title"
  ]
 },
 "app/api/transactions/[id]/route.ts": {
  "methods": [
   "DELETE",
   "PATCH"
  ],
  "getWrites": false,
  "sha256": "37dab80a8972a939ba49ff45b0083dfbe03989ef738112a2201dce898c4318b6",
  "effects": [
   "DELETION",
   "FINANCE",
   "LEDGER",
   "SETTINGS"
  ],
  "fields": [
   "agreedPrice",
   "amount",
   "artist",
   "businessUnit",
   "category",
   "currency",
   "date",
   "description",
   "expenseScope",
   "expense_scope",
   "financeException",
   "financeExceptionDate",
   "financeExceptionReason",
   "financialNotes",
   "linkedSessionId",
   "linked_session_id",
   "notes",
   "paymentMethod",
   "paymentStatus",
   "payment_method",
   "payment_status",
   "projectId",
   "project_id",
   "receiptRef",
   "receipt_ref",
   "scope",
   "syncShare",
   "type",
   "unitWriter"
  ]
 },
 "app/api/transactions/[id]/split/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "b96e6f843353d69a420d4bbf1e0fc270af02e92aa28320ebe7bc478d12d4c12a",
  "effects": [
   "DELETION",
   "FINANCE",
   "LEDGER",
   "SETTINGS"
  ],
  "fields": [
   "agreedPrice",
   "amount",
   "artist",
   "businessUnit",
   "category",
   "currency",
   "date",
   "description",
   "expenseScope",
   "expense_scope",
   "financeException",
   "financeExceptionDate",
   "financeExceptionReason",
   "financialNotes",
   "linkedSessionId",
   "linked_session_id",
   "notes",
   "paidAmount",
   "paymentMethod",
   "paymentStatus",
   "payment_method",
   "payment_status",
   "projectId",
   "project_id",
   "receiptRef",
   "receipt_ref",
   "receivedDate",
   "scope",
   "syncShare",
   "type",
   "unitWriter"
  ]
 },
 "app/api/transactions/route.ts": {
  "methods": [
   "PATCH",
   "POST"
  ],
  "getWrites": false,
  "sha256": "13fc08cb7a391ddeae2840d577e9270ad521bcf8c1d387282cae77227aa2e84f",
  "effects": [
   "DELETION",
   "FINANCE",
   "LEDGER",
   "SETTINGS"
  ],
  "fields": [
   "agreedPrice",
   "amount",
   "artist",
   "businessUnit",
   "category",
   "currency",
   "date",
   "description",
   "expenseScope",
   "expense_scope",
   "financeException",
   "financeExceptionDate",
   "financeExceptionReason",
   "financialNotes",
   "linkedSessionId",
   "linked_session_id",
   "notes",
   "paymentMethod",
   "paymentStatus",
   "payment_method",
   "payment_status",
   "projectId",
   "project_id",
   "receiptRef",
   "receipt_ref",
   "scope",
   "syncShare",
   "type",
   "unitWriter"
  ]
 },
 "app/api/vendor/victor/avatar/route.ts": {
  "methods": [
   "PATCH",
   "POST"
  ],
  "getWrites": false,
  "sha256": "7e3d53875e7eb69126890b4b6c5ae1af9e59270baa0e2d083408e3e00f01ba83",
  "effects": [
   "DELETION",
   "FILES",
   "SETTINGS"
  ],
  "fields": [
   "posX",
   "posY",
   "zoom"
  ]
 },
 "app/api/vendor/victor/notify-version-notes/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "81cb517eb74cad66d6437733e90ac8f229d11f0c40251a3b6f1a8b964b13ffd4",
  "effects": [
   "DELETION",
   "EXTERNAL_LINK",
   "FILES",
   "FINANCE",
   "GOOGLE_TASKS",
   "PUSH",
   "SETTINGS"
  ],
  "fields": [
   "artistName",
   "error",
   "error_summary",
   "internalDeadline",
   "note",
   "projectId",
   "projectName",
   "status",
   "title",
   "url",
   "useProjectsLayout",
   "vendorName",
   "versionKey",
   "workId",
   "workTitle"
  ]
 },
 "app/api/vendor/victor/notify-work/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "d7210e558545a6c265cdc2dbf00c935c0a094974e4f521c7365c96b5e42cc93d",
  "effects": [
   "DELETION",
   "EXTERNAL_LINK",
   "FILES",
   "FINANCE",
   "GOOGLE_TASKS",
   "PUSH",
   "SETTINGS"
  ],
  "fields": [
   "artistName",
   "error",
   "error_summary",
   "internalDeadline",
   "note",
   "projectId",
   "projectName",
   "status",
   "title",
   "url",
   "useProjectsLayout",
   "vendorName",
   "workId",
   "workTitle"
  ]
 },
 "app/api/vendor/victor/ping/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "b9732eae815893a6a374b0c8064d1bc8895c6f0fe0798b67dc18bfd56c215863",
  "effects": [
   "PUSH",
   "SETTINGS"
  ],
  "fields": []
 },
 "app/api/vendor/victor/production-link/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "3d05a375ddedb6b19e0562c72cf3a147e75bb936fb6aadc6e22b80d55dd20967",
  "effects": [
   "DELETION",
   "EXTERNAL_LINK",
   "SETTINGS"
  ],
  "fields": [
   "error",
   "error_summary"
  ]
 },
 "app/api/vendor/victor/push-subscribe/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "80c16b92e25896933edd6da2cf6234c97cb5c3583d120c17444df926841510d2",
  "effects": [],
  "fields": []
 },
 "app/api/vendor/victor/salary/route.ts": {
  "methods": [
   "PATCH",
   "POST"
  ],
  "getWrites": false,
  "sha256": "eccb286ff7725a7e1e2d2169053f20485e97489d2cd8b86c3851cb267598de49",
  "effects": [
   "DELETION",
   "EXTERNAL_LINK",
   "FILES",
   "FINANCE",
   "GOOGLE_TASKS",
   "PUSH",
   "SETTINGS"
  ],
  "fields": [
   "artistName",
   "error",
   "error_summary",
   "internalDeadline",
   "note",
   "projectId",
   "projectName",
   "status",
   "title",
   "url",
   "useProjectsLayout",
   "vendorName",
   "workId",
   "workTitle"
  ]
 },
 "app/api/vendor/victor/settings/route.ts": {
  "methods": [
   "PATCH"
  ],
  "getWrites": false,
  "sha256": "ee6e706a057c7f41deeabf532baa9539eca578c074c59a47a5bc8aee54b96e87",
  "effects": [
   "DELETION",
   "SETTINGS"
  ],
  "fields": []
 },
 "app/api/vendor/victor/work/[id]/brief/route.ts": {
  "methods": [
   "DELETE",
   "PATCH",
   "POST"
  ],
  "getWrites": false,
  "sha256": "db7462312ddfa8d093dbeac94a3f1c262a425a253f2d30ff2640a68e2c3c8dcf",
  "effects": [
   "DELETION",
   "EXTERNAL_LINK",
   "FILES",
   "FINANCE",
   "GOOGLE_TASKS",
   "LEDGER",
   "PUSH",
   "SETTINGS"
  ],
  "fields": [
   "artistName",
   "error",
   "error_summary",
   "internalDeadline",
   "note",
   "projectId",
   "projectName",
   "status",
   "title",
   "url",
   "useProjectsLayout",
   "vendorName",
   "workId",
   "workTitle"
  ]
 },
 "app/api/vendor/victor/work/[id]/file/route.ts": {
  "methods": [
   "DELETE"
  ],
  "getWrites": false,
  "sha256": "d2b6101bb57ffbdcd8e2d4be6857802c287caed2bfe92b0b07602cd1f19b516a",
  "effects": [
   "DELETION",
   "EXTERNAL_LINK",
   "FILES",
   "FINANCE",
   "GOOGLE_TASKS",
   "PUSH",
   "SETTINGS"
  ],
  "fields": [
   "fileRef"
  ]
 },
 "app/api/vendor/victor/work/[id]/route.ts": {
  "methods": [
   "DELETE",
   "PATCH"
  ],
  "getWrites": false,
  "sha256": "ca778b750b4f26f67b926021d5dffc8e4a2e7ef8bdadd88826929f43e05e9d1f",
  "effects": [
   "DELETION",
   "EXTERNAL_LINK",
   "FILES",
   "FINANCE",
   "GOOGLE_TASKS",
   "PUSH",
   "SETTINGS"
  ],
  "fields": [
   "artistName",
   "error",
   "error_summary",
   "internalDeadline",
   "note",
   "projectId",
   "projectName",
   "status",
   "title",
   "url",
   "useProjectsLayout",
   "vendorName",
   "workId",
   "workTitle"
  ]
 },
 "app/api/vendor/victor/work/route.ts": {
  "methods": [
   "POST"
  ],
  "getWrites": false,
  "sha256": "6bbc30e1afe3a6b733b548f95627f368afc198d50af9b13192ce85f98b6c0343",
  "effects": [
   "DELETION",
   "SETTINGS"
  ],
  "fields": [
   "dropboxFolder",
   "dropboxShareLink",
   "notes",
   "outcome",
   "projectId",
   "sentDate",
   "status",
   "title",
   "workState"
  ]
 }
};
